// problems.js — Pool centralitzat de problemes MCQ (Corregit i Validat)
// Ús: const PROB_POOL = getProbs('topic');
const PROBLEMS=[
  // ── DIVISIÓ (25) ─────────────────────────────────────────────────────────────
  {topic:'divisio',text:`En Tomàs té <strong>24 pilotes</strong> i les reparteix entre <strong>6 amics</strong> a parts iguals. Quantes pilotes toca a cadascú?`,opts:['4','3','6'],ans:'4'},
  {topic:'divisio',text:`Tenim <strong>35 galetes</strong> i les posem en bosses de <strong>5</strong> galetes. Quantes bosses fem?`,opts:['7','6','40'],ans:'7'},
  {topic:'divisio',text:`Una granja té <strong>45 ous</strong> i els posa en cartrons de <strong>9</strong>. Quants cartrons plens hi ha?`,opts:['5','4','6'],ans:'5'},
  {topic:'divisio',text:`En Pere té <strong>28 euros</strong>. Cada gelat val <strong>4 euros</strong>. Quants gelats pot comprar?`,opts:['7','8','24'],ans:'7'},
  {topic:'divisio',text:`Hi ha <strong>54 alumnes</strong> que van en autobusos de <strong>9 places</strong>. Quants autobusos calen?`,opts:['6','5','7'],ans:'6'},
  {topic:'divisio',text:`Una pastissera fa <strong>36 pastes</strong> i les posa en safates de <strong>6</strong>. Quantes safates omple?`,opts:['6','30','42'],ans:'6'},
  {topic:'divisio',text:`Tenim <strong>49 globus</strong> per repartir entre <strong>7 taules</strong>. Quants globus hi ha a cada taula?`,opts:['7','6','8'],ans:'7'},
  {topic:'divisio',text:`Tenim <strong>72 cartes</strong> i les repartim entre <strong>8 jugadors</strong> a parts iguals. Quantes cartes rep cada jugador?`,opts:['9','8','10'],ans:'9'},
  {topic:'divisio',text:`Una prestatgeria té <strong>40 llibres</strong> repartits en <strong>5 prestatges</strong> iguals. Quants llibres hi ha a cada prestatge?`,opts:['8','7','9'],ans:'8'},
  {topic:'divisio',text:`Tenim <strong>63 euros</strong> per comprar regals de <strong>9 euros</strong> cadascun. Quants regals podem comprar?`,opts:['7','6','8'],ans:'7'},
  {topic:'divisio',text:`Tenim <strong>29 llapis</strong> per repartir en grups de <strong>5</strong>. Quants grups plens fem i quants llapis sobren?`,opts:['5 grups i sobren 4','6 grups i sobren 1','4 grups i sobren 9'],ans:'5 grups i sobren 4'},
  {topic:'divisio',text:`Hi ha <strong>23 alumnes</strong> per hacer equips de <strong>4</strong>. Quants equips complets hi ha i quants alumnes sobren?`,opts:['5 equips i sobren 3','4 equips i sobren 7','6 equips i sobren 1'],ans:'5 equips i sobren 3'},
  {topic:'divisio',text:`Tenim <strong>38 galetes</strong> per posar en caixes de <strong>6</strong>. Quantes caixes plenes fem i quantes galetes sobren?`,opts:['6 caixes i sobren 2','5 caixes i sobren 8','7 caixes i sobren 0'],ans:'6 caixes i sobren 2'},
  {topic:'divisio',text:`Tenim <strong>47 euros</strong> per comprar joguines de <strong>8 euros</strong>. Quantes joguines podem comprar i quants euros sobren?`,opts:['5 joguines i sobren 7','6 joguines i sobren 1','4 joguines i sobren 15'],ans:'5 joguines i sobren 7'},
  {topic:'divisio',text:`Un pagès té <strong>32 pomes</strong> i les vol posar en bosses de <strong>4</strong> pomes cada una. Quantes bosses farà?`,opts:['8','7','9'],ans:'8'},
  {topic:'divisio',text:`Per fer un joc de taula necessitem repartir <strong>81 fitxes</strong> entre <strong>9 jugadors</strong>. Quantes fitxes rep cadascú?`,opts:['9','8','7'],ans:'9'},
  {topic:'divisio',text:`Al pati hi ha <strong>30 nens</strong> que volen jugar a bàsquet. Si formen equips de <strong>5 nens</strong>, quants equips sortiran?`,opts:['6','5','7'],ans:'6'},
  {topic:'divisio',text:`En un magatzem hi ha <strong>56 ampolles</strong> d'aigua en caixes de <strong>7</strong> ampolles. Quantes caixes hi ha en total?`,opts:['8','9','7'],ans:'8'},
  {topic:'divisio',text:`La professora vol repartir <strong>18 colors</strong> entre <strong>3 alumnes</strong> de manera igualitària. Quants colors tindrà cada alumne?`,opts:['6','5','4'],ans:'6'},
  {topic:'divisio',text:`En una floristeria hi ha <strong>21 roses</strong> per hacer rams de <strong>3 roses</strong> cada un. Quants rams es poden fer?`,opts:['7','6','8'],ans:'7'},
  {topic:'divisio',text:`Un obrador prepara <strong>42 magdalenes</strong> i les col·loca en caixes de <strong>6</strong> unitats. Quantes caixes omplen?`,opts:['7','8','6'],ans:'7'},
  {topic:'divisio',text:`Tenim <strong>19 caramels</strong> i els volem repartir entre <strong>3 amics</strong>. Quants en rep cadascú i quants en sobren?`,opts:['6 caramels i en sobra 1','5 caramels i en sobren 4','6 caramels i en sobren 2'],ans:'6 caramels i en sobra 1'},
  {topic:'divisio',text:`Una colla de <strong>6 amics</strong> vol repartir-se <strong>50 cromos</strong> a parts iguals. Quants cromos rep cadascú i quants en sobren?`,opts:['8 cromos i en sobren 2','8 cromos i en sobren 4','7 cromos i en sobren 8'],ans:'8 cromos i en sobren 2'},
  {topic:'divisio',text:`En un aniversari hi ha <strong>17 globus</strong> per col·locar en <strong>4 columnes</strong> iguals. Quants globus hi haurà per columna i quants en sobren?`,opts:['4 globus i en sobra 1','4 globus i en sobren 3','3 globus i en sobren 5'],ans:'4 globus i en sobra 1'},
  {topic:'divisio',text:`La mare compra <strong>26 iogurts</strong>. A casa en mengem <strong>3 cada dia</strong>. Quants dies complets duraran i quants en sobraran?`,opts:['8 dies i en sobren 2','7 dies i en sobren 5','9 dies i en sobra 0'],ans:'8 dies i en sobren 2'},

  // ── MULTIPLICACIÓ (25) ───────────────────────────────────────────────────────
  {topic:'multiplicacio',text:`Una capsa té <strong>6 files</strong> de <strong>8 bombons</strong>. Quants bombons hi ha en total?`,opts:['48','42','54'],ans:'48'},
  {topic:'multiplicacio',text:`La <strong>Sara</strong> llegeix <strong>15 pàgines</strong> cada dia. Quantes pàgines llegeix en <strong>7 dies</strong>?`,opts:['105','95','112'],ans:'105'},
  {topic:'multiplicacio',text:`Un autobús té <strong>9 files</strong> de <strong>4 seients</strong>. Quants seients té l'autobús?`,opts:['36','32','40'],ans:'36'},
  {topic:'multiplicacio',text:`Un paquet de cromos té <strong>8 cromos</strong>. Si en compres <strong>12 paquets</strong>, quants cromos tens?`,opts:['96','88','104'],ans:'96'},
  {topic:'multiplicacio',text:`Un granger recull <strong>24 ous</strong> cada dia. Quants ous recull en una <strong>setmana</strong> (7 dies)?`,opts:['168','154','182'],ans:'168'},
  {topic:'multiplicacio',text:`Cada taula de classe té <strong>2 cadires</strong>. Si hi ha <strong>15 taules</strong>, quantes cadires hi ha?`,opts:['30','28','32'],ans:'30'},
  {topic:'multiplicacio',text:`Un cotxe fa <strong>120 km</strong> en una hora. Quants km farà en <strong>4 hores</strong>?`,opts:['480','420','520'],ans:'480'},
  {topic:'multiplicacio',text:`Una ampolla d'aigua costa <strong>85 cèntims</strong>. Quant costen <strong>6 ampolles</strong>?`,opts:['5,10 €','4,80 €','5,40 €'],ans:'5,10 €'},
  {topic:'multiplicacio',text:`Hi ha <strong>365 dies</strong> en un any. Quants dies hi ha in <strong>3 anys</strong>?`,opts:['1.095','1.050','1.100'],ans:'1.095'},
  {topic:'multiplicacio',text:`Una classe té <strong>28 alumnes</strong>. Si cada alumne porta <strong>3 llapis</strong>, quants llapis hi ha in total?`,opts:['84','82','90'],ans:'84'},
  {topic:'multiplicacio',text:`Un rectangle mesura <strong>13 cm</strong> d'ample i <strong>7 cm</strong> d'alt. Quina és la seva àrea?`,opts:['91 cm²','84 cm²','98 cm²'],ans:'91 cm²'},
  {topic:'multiplicacio',text:`La <strong>Sara</strong> estalvia <strong>50 cèntims</strong> cada setmana. Quant tindrà al cap de <strong>12 setmanes</strong>?`,opts:['6 €','5 €','7 €'],ans:'6 €'},
  {topic:'multiplicacio',text:`En una sabateria hi ha <strong>9 prestatges</strong> amb <strong>11 parells</strong> de sabates a cadascun. Quants parells de sabates hi ha?`,opts:['99','90','110'],ans:'99'},
  {topic:'multiplicacio',text:`Un hort té <strong>6 rengles</strong> de tomaqueres. Si a cada rengle hi ha <strong>14 tomaqueres</strong>, quantes n'hi ha en total?`,opts:['84','74','94'],ans:'84'},
  {topic:'multiplicacio',text:`Una capsa de pintures conté <strong>24 llapis de colors</strong>. Quants llapis hi haurà en <strong>5 capses</strong> iguals?`,opts:['120','100','140'],ans:'120'},
  {topic:'multiplicacio',text:`Per fer una disfressa es necessiten <strong>4 botons</strong>. Quants botons necessitarem per fer <strong>35 disfresses</strong>?`,opts:['140','120','150'],ans:'140'},
  {topic:'multiplicacio',text:`Un bitllet de tren costa <strong>18 euros</strong>. Quant costaran els bitllets de <strong>5 amics</strong> que viatgen junts?`,opts:['90','80','100'],ans:'90'},
  {topic:'multiplicacio',text:`En un parc hi ha <strong>15 arbres</strong>, i cadascun té <strong>6 nius</strong> d'ocell. Quants nius hi ha al parc?`,opts:['90','85','95'],ans:'90'},
  {topic:'multiplicacio',text:`Cada dia de la setmana d'escola (<strong>5 dies</strong>), en Marc camina <strong>250 metres</strong>. Quants metres fa de dilluns a divendres?`,opts:['1.250','1.000','1.500'],ans:'1.250'},
  {topic:'multiplicacio',text:`Un àlbum té <strong>20 pàgines</strong> i a cada pàgina hi caben <strong>8 cromos</strong>. Quants cromos es poden enganxar en total?`,opts:['160','120','180'],ans:'160'},
  {topic:'multiplicacio',text:`Una pastisseria ven safates de dolços. Si cada safata té <strong>12 pastes</strong> i en venen <strong>8</strong>, quantes pastes han venut?`,opts:['96','84','108'],ans:'96'},
  {topic:'multiplicacio',text:`En una cursa ciclista es fan <strong>4 voltes</strong> a un circuit de <strong>15 quilòmetres</strong>. Quants quilòmetres corren en total?`,opts:['60','50','70'],ans:'60'},
  {topic:'multiplicacio',text:`Un cinema té <strong>14 files</strong> de cadira. Si a cada fila hi ha <strong>10 seients</strong>, quants seients hi ha a la sala?`,opts:['140','144','104'],ans:'140'},
  {topic:'multiplicacio',text:`Una llibreta petita costa <strong>75 cèntims</strong>. Quant costaran <strong>4 llibretes</strong>?`,opts:['3,00 €','2,50 €','3,50 €'],ans:'3,00 €'},
  {topic:'multiplicacio',text:`Un paquet de xiclets té <strong>5 xiclets</strong>. Si en comprem <strong>22 paquets</strong>, quants xiclets tindrem en total?`,opts:['110','100','120'],ans:'110'},

  // ── DINERS (25) ──────────────────────────────────────────────────────────────
  {topic:'diners',text:`La <strong>Maria</strong> té <strong>2 €</strong> i en gasta <strong>75 cèntims</strong>. Quant li queda?`,opts:['1,25 €','1,75 €','1,50 €'],ans:'1,25 €'},
  {topic:'diners',text:`Un gelat costa <strong>1,20 €</strong>. En <strong>Pau</strong> en compra <strong>3</strong>. Quant paga en total?`,opts:['3,60 €','3,20 €','4,20 €'],ans:'3,60 €'},
  {topic:'diners',text:`La <strong>Sara</strong> té <strong>500 cèntims</strong>. Expressa-ho en euros.`,opts:['5 €','50 €','0,50 €'],ans:'5 €'},
  {topic:'diners',text:`Un croissant costa <strong>85 cèntims</strong>. Pagues amb <strong>1 €</strong>. Quant és el canvi?`,opts:['15 cèntims','25 cèntims','5 cèntims'],ans:'15 cèntims'},
  {topic:'diners',text:`La <strong>Laia</strong> té 1 moneda de <strong>2 €</strong>, 2 monedes de <strong>50 cèntims</strong> i 1 de <strong>20 cèntims</strong>. Quant té en total?`,opts:['3,20 €','2,70 €','3,70 €'],ans:'3,20 €'},
  {topic:'diners',text:`Un llibre costa <strong>8,50 €</strong>. Pagues amb un bitllet de <strong>10 €</strong>. Quant et tornen?`,opts:['1,50 €','2,50 €','1 €'],ans:'1,50 €'},
  {topic:'diners',text:`Quants cèntims hi ha en <strong>3,45 €</strong>?`,opts:['345 cèntims','34 cèntims','3.450 cèntims'],ans:'345 cèntims'},
  {topic:'diners',text:`La <strong>botiga</strong> té llapis a <strong>40 cèntims</strong> i bolígrafs a <strong>65 cèntims</strong>. Quant costen <strong>un llapis i un bolígraf</strong>?`,opts:['1,05 €','95 cèntims','1,15 €'],ans:'1,05 €'},
  {topic:'diners',text:`En <strong>Marc</strong> vol comprar una pilota que costa <strong>4,50 €</strong>. Té <strong>2 €</strong> estalviats i la seva mare li dóna <strong>3 €</strong> més. Té prou diners?`,opts:['Sí, li sobren 50 cèntims','No, li falten 50 cèntims','Sí, li sobren 1,50 €'],ans:'Sí, li sobren 50 cèntims'},
  {topic:'diners',text:`Una entrada al cinema costa <strong>6,75 €</strong>. Quants cèntims és això?`,opts:['675 cèntims','67 cèntims','6.750 cèntims'],ans:'675 cèntims'},
  {topic:'diners',text:`La <strong>Marta</strong> compra un suc per <strong>1,30 €</strong> i un entrepà per <strong>2,80 €</strong>. Paga amb un bitllet de <strong>5 €</strong>. Quant li tornen?`,opts:['90 cèntims','1,10 €','1,90 €'],ans:'90 cèntims'},
  {topic:'diners',text:`Quants euros i cèntims són <strong>830 cèntims</strong>?`,opts:['8,30 €','83,00 €','0,83 €'],ans:'8,30 €'},
  {topic:'diners',text:`En <strong>Jordi</strong> estalvia <strong>50 cèntims</strong> cada dia. Al cap d'una setmana (<strong>7 dies</strong>), quants diners té?`,opts:['3,50 €','5 €','7 €'],ans:'3,50 €'},
  {topic:'diners',text:`Una revista costa <strong>2,95 €</strong>. Pagues amb un bitllet de <strong>5 €</strong>. Quant és el canvi?`,opts:['2,05 €','1,95 €','2,50 €'],ans:'2,05 €'},
  {topic:'diners',text:`Tens un bitllet de <strong>20 €</strong> i compres una llibreta de <strong>4,20 €</strong>. Quant et queda?`,opts:['15,80 €','16,20 €','15,20 €'],ans:'15,80 €'},
  {topic:'diners',text:`Si un paquet de cromos costa <strong>1,15 €</strong>, quant costaran <strong>2 paquets</strong>?`,opts:['2,30 €','2,20 €','2,40 €'],ans:'2,30 €'},
  {topic:'diners',text:`En Lluc té 3 monedes de <strong>20 cèntims</strong> i 2 monedes de <strong>10 cèntims</strong>. Quants diners té en total?`,opts:['80 cèntims','70 cèntims','60 cèntims'],ans:'80 cèntims'},
  {topic:'diners',text:`Una joguina val <strong>12,40 €</strong>. Paguem amb un bitllet de <strong>20 €</strong>. Quant ens han de tornar?`,opts:['7,60 €','8,60 €','7,40 €'],ans:'7,60 €'},
  {topic:'diners',text:`Quantes monedes de <strong>20 cèntims</strong> necessitem per tenir exactament <strong>1 euro</strong>?`,opts:['5 monedes','4 monedes','6 monedes'],ans:'5 monedes'},
  {topic:'diners',text:`La Joana té <strong>4,50 €</strong> i compra una bossa de pipes de <strong>80 cèntims</strong>. Quants diners li queden?`,opts:['3,70 €','3,90 €','4,10 €'],ans:'3,70 €'},
  {topic:'diners',text:`Un estoig costa <strong>5,65 €</strong>. Quants cèntims val en total?`,opts:['565 cèntims','56 cèntims','5.650 cèntims'],ans:'565 cèntims'},
  {topic:'diners',text:`En Biel compra dues gomes d'esborrar. Cadascuna val <strong>45 cèntims</strong>. Si paga amb <strong>1 €</strong>, quant li sobra?`,opts:['10 cèntims','90 cèntims','5 cèntims'],ans:'10 cèntims'},
  {topic:'diners',text:`Una entrada per a la piscina municipal costa <strong>3,25 €</strong> per a nens. Quant costaran les entrades de <strong>2 nens</strong>?`,opts:['6,50 €','6,25 €','7,00 €'],ans:'6,50 €'},
  {topic:'diners',text:`Quants diners són <strong>3 bitllets de 5 €</strong> i <strong>4 monedes de 50 cèntims</strong>?`,opts:['17,00 €','16,50 €','15,50 €'],ans:'17,00 €'},
  {topic:'diners',text:`Un retolador val <strong>1,35 €</strong>. Si en compres <strong>2</strong>, quant hauràs de pagar?`,opts:['2,70 €','2,60 €','2,80 €'],ans:'2,70 €'},

  // ── ESTADÍSTICA (25) ─────────────────────────────────────────────────────────
  {topic:'estadistica',text:`Al gràfic de la classe, <strong>12 nens</strong> prefereixen futbol i <strong>8 nens</strong> prefereixen natació. Quants nens prefereixen futbol <strong>més</strong> que natació?`,opts:['4 nens','6 nens','2 nens'],ans:'4 nens'},
  {topic:'estadistica',text:`El gràfic mostra que la botiga va vendre <strong>25 pomes el dilluns</strong> i <strong>15 pomes el dimarts</strong>. Quantes pomes va vendre entre els dos dies?`,opts:['40 pomes','35 pomes','45 pomes'],ans:'40 pomes'},
  {topic:'estadistica',text:`En una enquesta, <strong>30 alumnes</strong> van triar el seu color favorit. <strong>12</strong> van triar blau, <strong>10</strong> vermell i la resta verd. Quants van triar verd?`,opts:['8 alumnes','10 alumnes','6 alumnes'],ans:'8 alumnes'},
  {topic:'estadistica',text:`Una sèrie comença a <strong>3</strong> i cada terme <strong>multiplica per 2</strong>. Quin és el <strong>5è terme</strong>?`,opts:['48','32','64'],ans:'48'},
  {topic:'estadistica',text:`El gràfic mostra que la biblioteca va prestar <strong>40 llibres el dilluns, 35 el dimarts i 45 el dimecres</strong>. Quants llibres va prestar en total?`,opts:['120 llibres','110 llibres','130 llibres'],ans:'120 llibres'},
  {topic:'estadistica',text:`Una sèrie suma <strong>+7</strong> cada vegada i comença a <strong>5</strong>. Quin és el <strong>6è terme</strong>?`,opts:['40','42','35'],ans:'40'},
  {topic:'estadistica',text:`Al gràfic hi ha <strong>5 categories</strong>. La més gran té <strong>50 unitats</strong> i la més petita té <strong>15</strong>. Quina és la diferència?`,opts:['35','25','45'],ans:'35'},
  {topic:'estadistica',text:`Una sèrie baixa de <strong>100 de 8 en 8</strong>. El primer terme és <strong>100</strong>. Quin és el <strong>4t terme</strong>?`,opts:['76','68','72'],ans:'76'},
  {topic:'estadistica',text:`En el gràfic de fruites: <strong>Pomes=30, Peres=20, Maduixes=25</strong>. Quantes fruites hi ha en total?`,opts:['75 fruites','65 fruites','80 fruites'],ans:'75 fruites'},
  {topic:'estadistica',text:`La sèrie és: <strong>2, 6, 18, 54...</strong> Quin és el terme que segueix?`,opts:['162','108','72'],ans:'162'},
  {topic:'estadistica',text:`Al gràfic, el <strong>dimecres</strong> es van llegir <strong>18 pàgines</strong>. El <strong>dijous</strong> se'n van llegir el <strong>doble</strong>. Quantes pàgines es van llegir el dijous?`,opts:['36 pàgines','24 pàgines','30 pàgines'],ans:'36 pàgines'},
  {topic:'estadistica',text:`Una sèrie creix de <strong>+15 en +15</strong> i comença a <strong>10</strong>. Quin és el <strong>5è terme</strong>?`,opts:['70','65','75'],ans:'70'},
  {topic:'estadistica',text:`En una enquesta sobre mascotes, <strong>15 persones</strong> tenen gos, <strong>12</strong> tenen gat i <strong>3</strong> tenen ocells. Quantes persones tenen gos o gat?`,opts:['27 persones','15 persones','30 persones'],ans:'27 persones'},
  {topic:'estadistica',text:`Una sèrie de nombres comença al <strong>4</strong> i va sumant <strong>+6</strong> cada vegada. Quin és el <strong>4t terme</strong>?`,opts:['22','16','28'],ans:'22'},
  {topic:'estadistica',text:`Mirant un gràfic de barres, la barra de dilluns arriba al <strong>20</strong>, la de dimarts al <strong>30</strong> i la de dimecres al <strong>10</strong>. Quin dia es va registrar el valor més baix?`,opts:['Dimecres','Dilluns','Dimarts'],ans:'Dimecres'},
  {topic:'estadistica',text:`Completa la sèrie lògica: <strong>50, 45, 40, 35...</strong> Quin nombre ve a continuació?`,opts:['30','25','35'],ans:'30'},
  {topic:'estadistica',text:`En un gràfic de sectors, la meitat de la classe (<strong>15 alumnes</strong>) prefereix gelat de xocolata. Quants alumnes hi ha en total a la classe?`,opts:['30 alumnes','25 alumnes','20 alumnes'],ans:'30 alumnes'},
  {topic:'estadistica',text:`Una sèrie numèrica comença al <strong>1</strong> i es va multiplicant per <strong>3</strong> a cada pas. Quin és el <strong>4t terme</strong>?`,opts:['27','9','81'],ans:'27'},
  {topic:'estadistica',text:`El dilluns plouen <strong>5 mm</strong>, el dimarts <strong>12 mm</strong> i el dimecres <strong>0 mm</strong>. Quants mil·límetres ha plogut entre els tres dies?`,opts:['17 mm','12 mm','7 mm'],ans:'17 mm'},
  {topic:'estadistica',text:`La sèrie és: <strong>10, 20, 40, 80...</strong> Quin és el cinquè terme (el doble de l'anterior)?`,opts:['160','120','200'],ans:'160'},
  {topic:'estadistica',text:`En un recompte de cotxes, s'han vist <strong>8 cotxes blancs, 5 de negres i 7 de vermells</strong>. Quants cotxes es van comptar en total?`,opts:['20 cotxes','15 cotxes','18 cotxes'],ans:'20 cotxes'},
  {topic:'estadistica',text:`Una sèrie numèrica comença al <strong>100</strong> i va restant <strong>-12</strong> cada vegada. Quin és el <strong>3r terme</strong>?`,opts:['76','88','64'],ans:'76'},
  {topic:'estadistica',text:`En un gràfic sobre el menjar de la cantina, <strong>45 nens</strong> prefereixen macarrons i <strong>15 nens</strong> arròs. Quantes vegades més agrada el plat de macarrons respecte a l'arròs?`,opts:['3 vegades més','2 vegades més','4 vegades més'],ans:'3 vegades més'},
  {topic:'estadistica',text:`Continua la sèrie: <strong>3, 7, 11, 15...</strong> Quin nombre és el següent?`,opts:['19','18','21'],ans:'19'},
  {topic:'estadistica',text:`En un gràfic, la barra de gener marca <strong>14 unitats</strong> i la de febrer en marca el <strong>triple</strong>. Quantes unitats té el mes de febrer?`,opts:['42 unitats','28 unitats','36 unitats'],ans:'42 unitats'},

  // ── GEOMETRIA (25) ───────────────────────────────────────────────────────────
  {topic:'geometria',text:`La <strong>porta</strong> del col·legi és un rectangle de <strong>2 m</strong> d'ample i <strong>3 m</strong> d'alt. Quant mesura el seu perímetre?`,opts:['10 m','6 m','5 m'],ans:'10 m'},
  {topic:'geometria',text:`La <strong>pissarra</strong> de classe és un rectangle de <strong>4 m</strong> d'ample i <strong>2 m</strong> d'alt. Quina és la seva àrea?`,opts:['8 m²','12 m²','6 m²'],ans:'8 m²'},
  {topic:'geometria',text:`Un triangle té angles de <strong>70°</strong> i <strong>60°</strong>. Quant mesura el tercer angle?`,opts:['50°','40°','70°'],ans:'50°'},
  {topic:'geometria',text:`El jardí de l'escola és un quadrat de <strong>5 m</strong> de costat. Quant mesura la tanca (perímetre)?`,opts:['20 m','25 m','15 m'],ans:'20 m'},
  {topic:'geometria',text:`Un triangle rectangle té un angle de <strong>90°</strong> i un altre de <strong>35°</strong>. Quant mesura el tercer?`,opts:['55°','45°','65°'],ans:'55°'},
  {topic:'geometria',text:`La <strong>catifa</strong> del menjador mesura <strong>3 m</strong> × <strong>4 m</strong>. Quina és la seva àrea?`,opts:['12 m²','14 m²','7 m²'],ans:'12 m²'},
  {topic:'geometria',text:`Un triangle equilàter té tots els costats de <strong>6 cm</strong>. Quant mesura el seu perímetre?`,opts:['18 cm','12 cm','24 cm'],ans:'18 cm'},
  {topic:'geometria',text:`La <strong>taula de ping-pong</strong> mesura <strong>5 m</strong> × <strong>3 m</strong>. Quina àrea té?`,opts:['15 m²','16 m²','8 m²'],ans:'15 m²'},
  {topic:'geometria',text:`Un angle de <strong>130°</strong> és un angle...`,opts:['Obtús','Pla','Agut'],ans:'Obtús'},
  {topic:'geometria',text:`Una <strong>habitació quadrada</strong> té <strong>4 m</strong> de costat. Quant mesura el seu perímetre?`,opts:['16 m','8 m','12 m'],ans:'16 m'},
  {topic:'geometria',text:`Un foli rectangular fa <strong>20 cm</strong> d'ample i <strong>30 cm</strong> de llarg. Quin és el seu perímetre?`,opts:['100 cm','50 cm','600 cm'],ans:'100 cm'},
  {topic:'geometria',text:`Quants costats té un polígon anomenat <strong>hexàgon</strong>?`,opts:['6','5','8'],ans:'6'},
  {topic:'geometria',text:`Un quadrat té una àrea de <strong>36 cm²</strong>. Quant fa de llarg el seu costat?`,opts:['6 cm','9 cm','4 cm'],ans:'6 cm'},
  {topic:'geometria',text:`Un angle que mesura exactament <strong>90°</strong> és un angle...`,opts:['Recte','Agut','Obtús'],ans:'Recte'},
  {topic:'geometria',text:`Una llibreta quadrada té <strong>10 cm</strong> de costat. Quina és la seva àrea?`,opts:['100 cm²','40 cm²','20 cm²'],ans:'100 cm²'},
  {topic:'geometria',text:`Si un polígon té <strong>5 costats</strong> i 5 vèrtexs, com s'anomena?`,opts:['Pentàgon','Heptàgon','Quadrilàter'],ans:'Pentàgon'},
  {topic:'geometria',text:`Un triangle té tres costats que mesuren <strong>5 cm, 5 cm i 8 cm</strong>. Com és segon els seus costats?`,opts:['Isòsceles','Equilàter','Escalè'],ans:'Isòsceles'},
  {topic:'geometria',text:`Un rectangle té una base de <strong>10 cm</strong> i una altura de <strong>4 cm</strong>. Quina és la seva àrea?`,opts:['40 cm²','28 cm²','14 cm²'],ans:'40 cm²'},
  {topic:'geometria',text:`Un angle de <strong>45°</strong> és un angle...`,opts:['Agut','Obtús','Recte'],ans:'Agut'},
  {topic:'geometria',text:`Quants vèrtexs té un cub en total?`,opts:['8','6','12'],ans:'8'},
  {topic:'geometria',text:`Un triangle escalè té costats de <strong>4 cm, 5 cm i 6 cm</strong>. Quin és el seu perímetre?`,opts:['15 cm','12 cm','18 cm'],ans:'15 cm'},
  {topic:'geometria',text:`Com es diuen les línies que mai no es creuen, per molt que s'allarguin?`,opts:['Paral·leles','Perpendiculars','Secants'],ans:'Paral·leles'},
  {topic:'geometria',text:`Una rajola quadrada mesura <strong>30 cm</strong> de costat. Quin és el seu perímetre?`,opts:['120 cm','90 cm','60 cm'],ans:'120 cm'},
  {topic:'geometria',text:`Una capsa de sabates té forma de...`,opts:['Prisma rectangular (Prisme)','Cilindre','Esfera'],ans:'Prisma rectangular (Prisme)'},
  {topic:'geometria',text:`Un angle pla és un angle que fa exactament...`,opts:['180°','90°','360°'],ans:'180°'},

  // ── MESURES DE LONGITUD (25) ─────────────────────────────────────────────────
  {topic:'longitud',text:`La <strong>Marta</strong> té una cinta de <strong>3 m</strong>. En fa servir <strong>75 cm</strong>. Quants centímetres li queden?`,opts:['225 cm','150 cm','275 cm'],ans:'225 cm'},
  {topic:'longitud',text:`En <strong>Joan</strong> fa un recorregut de <strong>2 km</strong> i <strong>500 m</strong> més. Quants metres ha recorregut?`,opts:['2500 m','2050 m','3000 m'],ans:'2500 m'},
  {topic:'longitud',text:`Una taula fa <strong>120 cm</strong> de llarg i un banc fa <strong>85 cm</strong>. Quant sumen les dues mesures?`,opts:['205 cm','195 cm','215 cm'],ans:'205 cm'},
  {topic:'longitud',text:`Una serp fa <strong>2 m</strong> i <strong>30 cm</strong>. Quants centímetres fa en total?`,opts:['230 cm','203 cm','220 cm'],ans:'230 cm'},
  {topic:'longitud',text:`La distància de casa a l'escola és <strong>1 km</strong> i <strong>200 m</strong>. Quants metres és?`,opts:['1200 m','1020 m','1002 m'],ans:'1200 m'},
  {topic:'longitud',text:`El <strong>Pol</strong> té una corda de <strong>5 m</strong> i en talla <strong>180 cm</strong>. Quants centímetres de corda li queden?`,opts:['320 cm','370 cm','280 cm'],ans:'320 cm'},
  {topic:'longitud',text:`Un gràfic fa <strong>450 cm</strong> de llarg. Quants metres i centímetres fa?`,opts:['4 m i 50 cm','45 m i 0 cm','4 m i 5 cm'],ans:'4 m i 50 cm'},
  {topic:'longitud',text:`La <strong>Sara</strong> camina <strong>3 km</strong> cada dia. Quants metres camina en <strong>2 dies</strong>?`,opts:['6000 m','3200 m','600 m'],ans:'6000 m'},
  {topic:'longitud',text:`Una piscina olímpica fa <strong>50 m</strong>. Quants centímetres fa?`,opts:['5000 cm','500 cm','5500 cm'],ans:'5000 cm'},
  {topic:'longitud',text:`Un coet vola a <strong>8 km</strong> d'alçada. Quants metres és?`,opts:['8000 m','800 m','80000 m'],ans:'8000 m'},
  {topic:'longitud',text:`Una cinta de <strong>2 m 60 cm</strong> es talla en dues parts iguals. Quant fa cada part?`,opts:['130 cm','260 cm','120 cm'],ans:'130 cm'},
  {topic:'longitud',text:`L'alçada d'un edifici és de <strong>1200 cm</strong>. Quants metres fa?`,opts:['12 m','120 m','100 m'],ans:'12 m'},
  {topic:'longitud',text:`En <strong>Marc</strong> té una corda de <strong>4 m</strong>. La talla en trossos de <strong>50 cm</strong>. Quants trossos obté?`,opts:['8 trossos','4 trossos','6 trossos'],ans:'8 trossos'},
  {topic:'longitud',text:`La carretera de poble a poble fa <strong>3 km 400 m</strong>. Quants metres és en total?`,opts:['3400 m','3040 m','3004 m'],ans:'3400 m'},
  {topic:'longitud',text:`Un regle d'escola mesura <strong>30 cm</strong>. Quants mil·límetres són?`,opts:['300 mm','30 mm','3.000 mm'],ans:'300 mm'},
  {topic:'longitud',text:`Un saltador de llargada fa un salt de <strong>4 m i 15 cm</strong>. Quants centímetres ha saltat en total?`,opts:['415 cm','405 cm','450 cm'],ans:'415 cm'},
  {topic:'longitud',text:`Un llibre té un gruix de <strong>20 mm</strong>. Quants centímetres mesura aquest gruix?`,opts:['2 cm','200 cm','20 cm'],ans:'2 cm'},
  {topic:'longitud',text:`Una formiga recorre una distància de <strong>3 metres</strong>. Quants mil·límetres ha caminat?`,opts:['3.000 mm','300 mm','30 mm'],ans:'3.000 mm'},
  {topic:'longitud',text:`El camí del bosc fa <strong>1.500 m</strong>. Quants quilòmetres i metres són?`,opts:['1 km i 500 m','15 km','1 km i 50 m'],ans:'1 km i 500 m'},
  {topic:'longitud',text:`Una tanca de fusta fa <strong>600 cm</strong> de llargària. Expressa aquesta mesura en metres.`,opts:['6 m','60 m','0,6 m'],ans:'6 m'},
  {topic:'longitud',text:`La llibreta de matemàtiques fa <strong>25 cm</strong> de llarg. Quants mil·límetres fa?`,opts:['250 mm','25 mm','2.500 mm'],ans:'250 mm'},
  {topic:'longitud',text:`Un filferro mesura <strong>7 m i 5 cm</strong>. Quants centímetres són en total?`,opts:['705 cm','750 cm','75 cm'],ans:'705 cm'},
  {topic:'longitud',text:`Un atleta corre <strong>5.000 metres</strong> a la pista. Quants quilòmetres ha fet?`,opts:['5 km','50 km','500 km'],ans:'5 km'},
  {topic:'longitud',text:`Una goma elàstica es pot estirar fins a <strong>40 cm</strong>. Quants mil·límetres és això?`,opts:['400 mm','40 mm','4.000 mm'],ans:'400 mm'},
  {topic:'longitud',text:`Un tauler de fusta fa <strong>300 cm</strong> i en tallem un tros de <strong>1 m</strong>. Quants metres de tauler queden?`,opts:['2 m','200 m','1 m'],ans:'2 m'},

  // ── VALOR POSICIONAL (25) ────────────────────────────────────────────────────
  {topic:'valor_posicional',text:`El número <strong>34.567</strong> té <strong>quantes desenes de miler</strong>?`,opts:['3','4','5'],ans:'3'},
  {topic:'valor_posicional',text:`El número <strong>128.045</strong> té <strong>quantes centenes</strong>?`,opts:['0','1','8'],ans:'0'},
  {topic:'valor_posicional',text:`Quant val el dígit <strong>7</strong> al número <strong>47.823</strong>?`,opts:['7.000','700','70'],ans:'7.000'},
  {topic:'valor_posicional',text:`Quin número és: <strong>50.000 + 3.000 + 200 + 40 + 1</strong>?`,opts:['53.241','53.421','53.240'],ans:'53.241'},
  {topic:'valor_posicional',text:`Quin número és: <strong>200.000 + 6.000 + 300 + 5</strong>?`,opts:['206.305','260.035','206.350'],ans:'206.305'},
  {topic:'valor_posicional',text:`Al número <strong>85.204</strong>, quin dígit ocupa el lloc de les <strong>centenes</strong>?`,opts:['2','5','8'],ans:'2'},
  {topic:'valor_posicional',text:`Quin número és: <strong>4 desenes de miler + 3 centenes + 7 unitats</strong>?`,opts:['40.307','43.007','40.037'],ans:'40.307'},
  {topic:'valor_posicional',text:`Quant val el dígit <strong>9</strong> al número <strong>390.412</strong>?`,opts:['90.000','9.000','900'],ans:'90.000'},
  {topic:'valor_posicional',text:`El número <strong>508.030</strong> té <strong>quantes unitats de miler</strong>?`,opts:['8','5','0'],ans:'8'},
  {topic:'valor_posicional',text:`Quin número és: <strong>3 centenes de miler + 5 desenes + 2 unitats</strong>?`,opts:['300.052','300.520','305.002'],ans:'300.052'},
  {topic:'valor_posicional',text:`Al número <strong>14.592</strong>, quin valor té la xifra <strong>4</strong>?`,opts:['4.000','400','40.000'],ans:'4.000'},
  {topic:'valor_posicional',text:`Quin lloc ocupa el número <strong>6</strong> en la xifra <strong>76.104</strong>?`,opts:['Unitats de miler','Centenes','Desenes de miler'],ans:'Unitats de miler'},
  {topic:'valor_posicional',text:`Descompon el número <strong>8.402</strong> en forma de suma:`,opts:['8.000 + 400 + 2','8.000 + 40 + 2','800 + 40 + 2'],ans:'8.000 + 400 + 2'},
  {topic:'valor_posicional',text:`Quin número es forma amb <strong>6 centenes, 2 desenes i 9 unitats</strong>?`,opts:['629','692','269'],ans:'629'},
  {topic:'valor_posicional',text:`Al número <strong>905.341</strong>, quina xifra ocupa les <strong>desenes de miler</strong>?`,opts:['0','9','5'],ans:'0'},
  {topic:'valor_posicional',text:`Quin és el valor del dígit <strong>5</strong> al número <strong>531.024</strong>?`,opts:['500.000','50.000','5.000'],ans:'500.000'},
  {topic:'valor_posicional',text:`Quin número és: <strong>70.000 + 800 + 30</strong>?`,opts:['70.830','78.030','70.803'],ans:'70.830'},
  {topic:'valor_posicional',text:`Al número <strong>62.385</strong>, quin dígit està en la posició de les <strong>unitats</strong>?`,opts:['5','8','6'],ans:'5'},
  {topic:'valor_posicional',text:`Quantes unitats valen <strong>3 desenes de miler</strong>?`,opts:['30.000','3.000','300.000'],ans:'30.000'},
  {topic:'valor_posicional',text:`Quin d'aquests números té un <strong>8</strong> al lloc de les centenes?`,opts:['2.845','8.120','4.582'],ans:'2.845'},
  {topic:'valor_posicional',text:`Quin número obtenim si sumem <strong>1 unitat de miler</strong> al número <strong>45.300</strong>?`,opts:['46.300','45.400','55.300'],ans:'46.300'},
  {topic:'valor_posicional',text:`Al número <strong>273.415</strong>, quina xifra representa les <strong>centenes de miler</strong>?`,opts:['2','7','3'],ans:'2'},
  {topic:'valor_posicional',text:`Quin número es forma amb <strong>2 U. de miler + 5 C + 4 D + 8 U</strong>?`,opts:['2.548','25.480','20.548'],ans:'2.548'},
  {topic:'valor_posicional',text:`Si en el número <strong>15.932</strong> canviem el 5 per un 0, quin número ens queda?`,opts:['10.932','15.032','50.932'],ans:'10.932'},
  {topic:'valor_posicional',text:`Quantes centenes senceres hi ha en el número <strong>1.200</strong>?`,opts:['12','120','2'],ans:'12'},

  // ── PROBLEMES: SUMES I RESTES (25) ──────────────────────────────────────────
  {topic:'sumes_restes',text:`La <strong>Maria</strong> té <strong>234</strong> cromos i en rep <strong>127</strong> més. Quants cromos té ara?`,opts:['361 cromos','307 cromos','371 cromos'],ans:'361 cromos'},
  {topic:'sumes_restes',text:`En <strong>Pau</strong> tenia <strong>500 €</strong> i en gasta <strong>178 €</strong>. Quants euros li queden?`,opts:['322 €','378 €','312 €'],ans:'322 €'},
  {topic:'sumes_restes',text:`A la classe hi ha <strong>28 nens</strong>. En surten <strong>9</strong>. Quants queden a classe?`,opts:['19 nens','17 nens','21 nens'],ans:'19 nens'},
  {topic:'sumes_restes',text:`Una botiga tenia <strong>560 pomes</strong>. Ven <strong>234</strong>. Quantes pomes li queden?`,opts:['326 pomes','336 pomes','316 pomes'],ans:'326 pomes'},
  {topic:'sumes_restes',text:`En <strong>Marc</strong> porta <strong>275 cromos</strong> i en dona <strong>132</strong> al seu germà. Quants li queden?`,opts:['143 cromos','153 cromos','133 cromos'],ans:'143 cromos'},
  {topic:'sumes_restes',text:`Al parc hi ha <strong>58 ocells</strong>. En volen <strong>23</strong>. Quants ocells queden al parc?`,opts:['35 ocells','45 ocells','25 ocells'],ans:'35 ocells'},
  {topic:'sumes_restes',text:`L'escola té <strong>324 alumnes</strong>. N'arriben <strong>48</strong> nous. Quants alumnes hi ha en total?`,opts:['372 alumnes','362 alumnes','382 alumnes'],ans:'372 alumnes'},
  {topic:'sumes_restes',text:`La <strong>iaia</strong> tenia <strong>480 botons</strong>. En regala <strong>195</strong>. Quants botons li queden?`,opts:['285 botons','295 botons','275 botons'],ans:'285 botons'},
  {topic:'sumes_restes',text:`En <strong>Tom</strong> tenia <strong>96 punts</strong> al joc i en perd <strong>37</strong>. Quants punts té ara?`,opts:['59 punts','69 punts','49 punts'],ans:'59 punts'},
  {topic:'sumes_restes',text:`Una prestatgeria té <strong>145 llibres</strong>. N'afegim <strong>38</strong>. Quants llibres hi ha?`,opts:['183 llibres','173 llibres','193 llibres'],ans:'183 llibres'},
  {topic:'sumes_restes',text:`El <strong>supermercat</strong> ven <strong>412 ampolles</strong> el dilluns i <strong>287</strong> el dimarts. Quantes ampolles ha venut en total?`,opts:['699 ampolles','689 ampolles','709 ampolles'],ans:'699 ampolles'},
  {topic:'sumes_restes',text:`Una caixa tenia <strong>350 llàpissos</strong>. En treiem <strong>126</strong>. Quants llàpissos queden?`,opts:['224 llàpissos','234 llàpissos','214 llàpissos'],ans:'224 llàpissos'},
  {topic:'sumes_restes',text:`En un formiguer hi havia <strong>670 formigues</strong>. En surten <strong>245</strong> a buscar menjar. Quantes formigues queden dins?`,opts:['425 formigues','435 formigues','415 formigues'],ans:'425 formigues'},
  {topic:'sumes_restes',text:`La Laura té un trencaclosques de <strong>1.000 peces</strong>. Ja n'ha col·locat <strong>650</strong>. Quantes peces li queden per posar?`,opts:['350 peces','450 peces','250 peces'],ans:'350 peces'},
  {topic:'sumes_restes',text:`En un avió viatgen <strong>184 passatgers</strong>. En una escala en baixen <strong>52</strong>. Quants passatgers queden a l'avió?`,opts:['132 passatgers','122 passatgers','142 passatgers'],ans:'132 passatgers'},
  {topic:'sumes_restes',text:`Una pastisseria fa <strong>125 bunyols</strong> de xocolata i <strong>190</strong> de crema. Quants bunyols fa en total?`,opts:['315 bunyols','305 bunyols','325 bunyols'],ans:'315 bunyols'},
  {topic:'sumes_restes',text:`El pare ha collit <strong>435 llimones</strong> i la mare en cull <strong>182</strong> més. Quantes llimones tenen juntes?`,opts:['617 llimones','517 llimones','627 llimones'],ans:'617 llimones'},
  {topic:'sumes_restes',text:`Un cinema té <strong>250 seients</strong>. Si s'omplen <strong>168 seients</strong>, quants queden de buits?`,opts:['82 seients','92 seients','72 seients'],ans:'82 seients'},
  {topic:'sumes_restes',text:`Una parada de fruita té <strong>318 taronges</strong>. En venen <strong>140</strong> durant el matí. Quantes en queden per la tarda?`,opts:['178 taronges','168 taronges','188 taronges'],ans:'178 taronges'},
  {topic:'sumes_restes',text:`En una biblioteca hi ha <strong>890 llibres</strong> d'aventures. Se'n presten <strong>235</strong>. Quants en queden a les prestatgeries?`,opts:['655 llibres','665 llibres','645 llibres'],ans:'655 llibres'},
  {topic:'sumes_restes',text:`En una cursa hi participen <strong>456 corredors</strong> adults i <strong>123</strong> de joves. Quants corredors hi ha en total?`,opts:['579 corredors','569 corredors','589 corredors'],ans:'579 corredors'},
  {topic:'sumes_restes',text:`La Clàudia té <strong>75 cèntims</strong> i en troba <strong>60</strong> més a la bossa. Quants cèntims té ara?`,opts:['135 cèntims','125 cèntims','145 cèntims'],ans:'135 cèntims'},
  {topic:'sumes_restes',text:`Un camió transporta <strong>800 caixes</strong> de llet. En deixa <strong>350</strong> al primer súper. Quantes caixes li queden?`,opts:['450 caixes','550 caixes','400 caixes'],ans:'450 caixes'},
  {topic:'sumes_restes',text:`En un dipòsit hi ha <strong>920 litres</strong> d'aigua. Se'n gasten <strong>415 litres</strong> per regar. Quants litres queden?`,opts:['505 litres','515 litres','495 litres'],ans:'505 litres'},
  {topic:'sumes_restes',text:`Un ramader té <strong>134 ovelles</strong> blanques i <strong>88</strong> ovelles negres. Quantes ovelles té en total?`,opts:['222 ovelles','212 ovelles','224 ovelles'],ans:'222 ovelles'},

  // ── PROBLEMES: MULTIPLICACIÓ I DIVISIÓ (25) ──────────────────────────────────
  {topic:'mult_div',text:`La <strong>Sara</strong> compra <strong>6 paquets</strong> de cromos. Cada paquet té <strong>8 cromos</strong>. Quants cromos té?`,opts:['48 cromos','42 cromos','56 cromos'],ans:'48 cromos'},
  {topic:'mult_div',text:`En una classe hi ha <strong>4 files</strong> de <strong>7 cadires</strong>. Quantes cadires hi ha en total?`,opts:['28 cadires','24 cadires','32 cadires'],ans:'28 cadires'},
  {topic:'mult_div',text:`Repartim <strong>72 llàpissos</strong> entre <strong>9 nens</strong> a parts iguals. Quants llàpissos rep cada nen?`,opts:['8 llàpissos','7 llàpissos','9 llàpissos'],ans:'8 llàpissos'},
  {topic:'mult_div',text:`Una granja té <strong>8 gallines</strong>. Cada gallina pon <strong>5 ous</strong> al dia. Quants ous ponen totes juntes?`,opts:['40 ous','48 ous','35 ous'],ans:'40 ous'},
  {topic:'mult_div',text:`Comprem <strong>5 llibres</strong> a <strong>12 €</strong> cadascun. Quant paguem en total?`,opts:['60 €','50 €','70 €'],ans:'60 €'},
  {topic:'mult_div',text:`Tenim <strong>84 taronges</strong> i les posem en caixes de <strong>7</strong>. Quantes caixes fem?`,opts:['12 caixes','14 caixes','10 caixes'],ans:'12 caixes'},
  {topic:'mult_div',text:`En <strong>Marc</strong> llegeix <strong>9 pàgines</strong> cada dia. Quantes pàgines llegeix en <strong>8 dies</strong>?`,opts:['72 pàgines','63 pàgines','81 pàgines'],ans:'72 pàgines'},
  {topic:'mult_div',text:`Una caixa porta <strong>6 ampolles</strong>. Quantes ampolles hi ha en <strong>7 caixes</strong>?`,opts:['42 ampolles','36 ampolles','48 ampolles'],ans:'42 ampolles'},
  {topic:'mult_div',text:`Tenim <strong>90 fotocòpies</strong> per repartir en carpetes de <strong>9</strong>. Quantes carpetes necessitem?`,opts:['10 carpetes','9 carpetes','11 carpetes'],ans:'10 carpetes'},
  {topic:'mult_div',text:`En <strong>Pol</strong> estalvia <strong>7 €</strong> cada setmana. Quants euros estalviarà en <strong>6 setmanes</strong>?`,opts:['42 €','35 €','49 €'],ans:'42 €'},
  {topic:'mult_div',text:`Una escola té <strong>6 classes</strong> amb <strong>25 alumnes</strong> cadascuna. Quants alumnes té l'escola?`,opts:['150 alumnes','130 alumnes','160 alumnes'],ans:'150 alumnes'},
  {topic:'mult_div',text:`Tenim <strong>56 pastanagues</strong> per repartir entre <strong>7 conills</strong>. Quantes rep cada conill?`,opts:['8 pastanagues','7 pastanagues','9 pastanagues'],ans:'8 pastanagues'},
  {topic:'mult_div',text:`Un repartidor porta <strong>8 caixes</strong> amb <strong>12 sucs</strong> a cadascuna. Quants sucs porta en total?`,opts:['96 sucs','86 sucs','106 sucs'],ans:'96 sucs'},
  {topic:'mult_div',text:`Tenim <strong>48 caramels</strong> i els volem repartir en bosses de <strong>6 caramels</strong> cadascuna. Quantes bosses farem?`,opts:['8 bosses','7 bosses','9 bosses'],ans:'8 bosses'},
  {topic:'mult_div',text:`En una sabateria venen <strong>5 parells</strong> de sabates a <strong>30 €</strong> cada parell. Quant han guanyat?`,opts:['150 €','120 €','180 €'],ans:'150 €'},
  {topic:'mult_div',text:`Si una setmana té <strong>7 dies</strong>, quants dies hi ha en <strong>12 setmanes</strong>?`,opts:['84 dies','74 dies','94 dies'],ans:'84 dies'},
  {topic:'mult_div',text:`Una guarderia té <strong>36 joguines</strong> per desar en <strong>4 calaixos</strong> iguals. Quantes joguines van a cada calaix?`,opts:['9 joguines','8 joguines','7 joguines'],ans:'9 joguines'},
  {topic:'mult_div',text:`Un teatre ven <strong>9 entrades</strong> a un preu de <strong>15 €</strong> cadascuna. Quants diners recapta?`,opts:['135 €','125 €','145 €'],ans:'135 €'},
  {topic:'mult_div',text:`Per fer una truita de patates gran es fan servir <strong>6 ous</strong>. Si tenim <strong>54 ous</strong>, quantes truites podem cuinar?`,opts:['9 truites','8 truites','10 truites'],ans:'9 truites'},
  {topic:'mult_div',text:`Una fàbrica posa <strong>10 xiclets</strong> a cada paquet. Quants xiclets hi ha en <strong>25 paquets</strong>?`,opts:['250 xiclets','200 xiclets','300 xiclets'],ans:'250 xiclets'},
  {topic:'mult_div',text:`En un magatzem es volen col·locar <strong>64 cadires</strong> en files de <strong>8</strong> cadires. Quantes files sortiran?`,opts:['8 files','7 files','9 files'],ans:'8 files'},
  {topic:'mult_div',text:`Cada llibre d'una col·lecció costa <strong>8 €</strong>. Si en comprem <strong>11</strong>, quants euros ens costarà?`,opts:['88 €','80 €','96 €'],ans:'88 €'},
  {topic:'mult_div',text:`Un pastor vol agrupar <strong>35 cabres</strong> en tancats de <strong>5 cabres</strong> cadascun. Quants tancats necessita?`,opts:['7 tancats','6 tancats','8 tancats'],ans:'7 tancats'},
  {topic:'mult_div',text:`Una florista fa <strong>12 rams</strong> de flors. Si utilitza <strong>6 flors</strong> per ram, quantes flors necessita?`,opts:['72 flors','62 flors','82 flors'],ans:'72 flors'},
  {topic:'mult_div',text:`En un hort es col·loquen <strong>40 plantes</strong> de bleda en <strong>5 línies</strong> de cultiu iguals. Quantes plantes hi ha per línia?`,opts:['8 plantes','7 plantes','9 plantes'],ans:'8 plantes'},

  // ── PROBLEMES: FRACCIONS (25) ────────────────────────────────────────────────
  {topic:'fraccions_contexte',text:`Una pizza té <strong>8 trossos</strong>. La Sara en menja <strong>3</strong> i en Marc en menja <strong>2</strong>. Quants trossos han menjat entre tots dos?`,opts:['5 trossos','4 trossos','6 trossos'],ans:'5 trossos'},
  {topic:'fraccions_contexte',text:`La <strong>Sara</strong> té <strong>20 cromos</strong> i en dona <strong>1/4</strong> al seu germà. Quants cromos dona?`,opts:['5 cromos','4 cromos','10 cromos'],ans:'5 cromos'},
  {topic:'fraccions_contexte',text:`De <strong>30 nens</strong>, <strong>1/3</strong> porten barret. Quants nens porten barret?`,opts:['10 nens','15 nens','6 nens'],ans:'10 nens'},
  {topic:'fraccions_contexte',text:`Tenim <strong>16 boles</strong>. <strong>3/4</strong> són vermelles. Quantes boles vermelles hi ha?`,opts:['12 boles','8 boles','4 boles'],ans:'12 boles'},
  {topic:'fraccions_contexte',text:`Un pastís es divideix en <strong>6 parts iguals</strong>. En mengem <strong>2 parts</strong>. Quines parts queden?`,opts:['4 parts','3 parts','5 parts'],ans:'4 parts'},
  {topic:'fraccions_contexte',text:`La <strong>Sara</strong> té <strong>24 galetes</strong>. En menja <strong>1/2</strong>. Quantes galetes ha menjat?`,opts:['12 galetes','8 galetes','6 galetes'],ans:'12 galetes'},
  {topic:'fraccions_contexte',text:`Un cub té <strong>6 cares</strong>. Pintem <strong>1/3</strong> de les cares. Quantes cares pintem?`,opts:['2 cares','3 cares','4 cares'],ans:'2 cares'},
  {topic:'fraccions_contexte',text:`Una cinta de <strong>30 cm</strong> es divideix en <strong>5 parts iguals</strong>. Quant fa cada part?`,opts:['6 cm','5 cm','7 cm'],ans:'6 cm'},
  {topic:'fraccions_contexte',text:`Tenim <strong>3/5</strong> d'una cinta de <strong>25 cm</strong>. Quants centímetres és?`,opts:['15 cm','10 cm','20 cm'],ans:'15 cm'},
  {topic:'fraccions_contexte',text:`La <strong>Sara</strong> menja <strong>2/8</strong> d'una pizza. El seu germà menja <strong>3/8</strong>. Quina fracció han menjat entre tots dos?`,opts:['5/8','4/8','6/8'],ans:'5/8'},
  {topic:'fraccions_contexte',text:`Tenim <strong>40 boletes</strong>. <strong>1/4</strong> són blaves, <strong>1/2</strong> vermelles i la resta verdes. Quantes boletes verdes hi ha?`,opts:['10 boletes','15 boletes','20 boletes'],ans:'10 boletes'},
  {topic:'fraccions_contexte',text:`Un grup de <strong>12 amics</strong> va al parc. <strong>1/2</strong> d'ells va amb bicicleta. Quants amics van en bici?`,opts:['6 amics','4 amics','3 amics'],ans:'6 amics'},
  {topic:'fraccions_contexte',text:`Un pastís s'ha dividit en <strong>5 parts iguals</strong>. Si l'Arnau en menja <strong>1/5</strong> i la Irene <strong>2/5</strong>, quina fracció de pastís queda?`,opts:['2/5','3/5','1/5'],ans:'2/5'},
  {topic:'fraccions_contexte',text:`En una cistella hi ha <strong>18 pomes</strong>. Si <strong>1/3</strong> són pomes verdes, quantes pomes verdes hi ha?`,opts:['6 pomes','5 pomes','9 pomes'],ans:'6 pomes'},
  {topic:'fraccions_contexte',text:`Tinc <strong>15 euros</strong> i en gasto <strong>2/3</strong> per comprar un llibre. Quants euros em costa el llibre?`,opts:['10 euros','5 euros','6 euros'],ans:'10 euros'},
  {topic:'fraccions_contexte',text:`Una xocolatina està dividida en <strong>10 trossos iguals</strong>. Si en dono <strong>4/10</strong> a un amic, quina fracció de xocolatina em queda?`,opts:['6/10','4/10','5/10'],ans:'6/10'},
  {topic:'fraccions_contexte',text:`En un aquari hi ha <strong>28 peixos</strong>. Si <strong>1/4</strong> dels peixos són de color taronja, quants peixos taronges hi ha?`,opts:['7 peixos','6 peixos','8 peixos'],ans:'7 peixos'},
  {topic:'fraccions_contexte',text:`La mare talla un pa de pessic en <strong>8 trossos iguals</strong>. Si ens mengem <strong>4 trossos</strong>, quina fracció representa la meitat (1/2) del pa de pessic?`,opts:['4/8','2/8','6/8'],ans:'4/8'},
  {topic:'fraccions_contexte',text:`En una bossa hi ha <strong>32 caramels</strong>. Els nens es mengen <strong>1/2</strong> dels caramels. Quants caramels queden a la bossa?`,opts:['16 caramels','12 caramels','20 caramels'],ans:'16 caramels'},
  {topic:'fraccions_contexte',text:`Un llibre té <strong>50 pàgines</strong>. Si la Núria ja n'ha llegit <strong>3/5</strong> parts, quantes pàgines ha llegit?`,opts:['30 pàgines','20 pàgines','25 pàgines'],ans:'30 pàgines'},
  {topic:'fraccions_contexte',text:`Un hort té <strong>24 plantes</strong>. Si <strong>1/3</strong> són enciams i la resta són tomaqueres, quantes plantes són tomaqueres?`,opts:['16 plantes','8 plantes','12 plantes'],ans:'16 plantes'},
  {topic:'fraccions_contexte',text:`De <strong>20 alumnes</strong> de la classe, <strong>2/5</strong> fan extraescolar de música. Quants alumnes fan música?`,opts:['8 alumnes','4 alumnes','10 alumnes'],ans:'8 alumnes'},
  {topic:'fraccions_contexte',text:`Un pintor necessita pintar una tanca. Si el matí en pinta <strong>2/7</strong> i la tarda en pinta <strong>3/7</strong>, quina fracció de la tanca ha pintat en total?`,opts:['5/7','6/7','4/7'],ans:'5/7'},
  {topic:'fraccions_contexte',text:`Tinc una capsa amb <strong>12 retoladors</strong>. Si <strong>3/4</strong> d'ells funcionen perfectament, quants retoladors funcionen?`,opts:['9 retoladors','6 retoladors','8 retoladors'],ans:'9 retoladors'},
  {topic:'fraccions_contexte',text:`Una pizza es talla en <strong>4 parts iguals</strong>. Ens mengem les <strong>4 parts</strong>. Quina fracció representa la pizza sencera?`,opts:['4/4','1/4','3/4'],ans:'4/4'},

  // ── PROBLEMES: MESURES I DINERS (25) ────────────────────────────────────────
  {topic:'mesures_diners',text:`Una ampolla de <strong>2 L</strong> es buida en gots de <strong>250 ml</strong>. Quants gots s'omplen?`,opts:['8 gots','6 gots','10 gots'],ans:'8 gots'},
  {topic:'mesures_diners',text:`La <strong>Maria</strong> compra <strong>3 m</strong> de cinta i en fa servir <strong>120 cm</strong>. Quants centímetres li queden?`,opts:['180 cm','150 cm','200 cm'],ans:'180 cm'},
  {topic:'mesures_diners',text:`Tenim <strong>4 ampolles</strong> de <strong>750 ml</strong>. Quants litres tenim en total?`,opts:['3 L','4 L','2 L'],ans:'3 L'},
  {topic:'mesures_diners',text:`La distància entre dues ciutats és de <strong>45 km</strong>. Quants metres és?`,opts:['45 000 m','4 500 m','450 m'],ans:'45 000 m'},
  {topic:'mesures_diners',text:`Una corda de <strong>3 m</strong> es talla en trossos de <strong>50 cm</strong>. Quants trossos n'obtenim?`,opts:['6 trossos','5 trossos','8 trossos'],ans:'6 trossos'},
  {topic:'mesures_diners',text:`En <strong>Joan</strong> té <strong>5 €</strong>. Compra un suc que val <strong>1,50 €</strong>. Quant canvi rep?`,opts:['3,50 €','2,50 €','4,50 €'],ans:'3,50 €'},
  {topic:'mesures_diners',text:`Una recepta necessita <strong>250 ml</strong> de llet. Si en tenim <strong>1 L</strong>, quants ml de llet ens sobren?`,opts:['750 ml','500 ml','600 ml'],ans:'750 ml'},
  {topic:'mesures_diners',text:`Comprem <strong>3 iogurts</strong> a <strong>0,80 €</strong> cadascun. Quant paguem?`,opts:['2,40 €','2,00 €','3,00 €'],ans:'2,40 €'},
  {topic:'mesures_diners',text:`Un recipient té <strong>5 L</strong> d'aigua. N'aboquem <strong>2 L i 500 ml</strong>. Quants mil·lilitres queden?`,opts:['2 500 ml','3 000 ml','2 000 ml'],ans:'2 500 ml'},
  {topic:'mesures_diners',text:`La <strong>Sara</strong> porta <strong>10 €</strong>. Compra un llapis per <strong>1,20 €</strong> i un quadern per <strong>2,50 €</strong>. Quant li queda?`,opts:['6,30 €','7,30 €','5,30 €'],ans:'6,30 €'},
  {topic:'mesures_diners',text:`Una piscina fa <strong>25 m</strong>. La Sara la neda <strong>4 vegades</strong>. Quants metres ha nedat en total?`,opts:['100 m','80 m','120 m'],ans:'100 m'},
  {topic:'mesures_diners',text:`Comprem <strong>6 pomes</strong> a <strong>0,35 €</strong> cadascuna. Quant paguem?`,opts:['2,10 €','1,80 €','2,40 €'],ans:'2,10 €'},
  {topic:'mesures_diners',text:`Un bric de suc té <strong>1 L</strong> de capacitat. Omplim <strong>2 gots de 200 ml</strong> cadascun. Quants mil·lilitres de suc queden al bric?`,opts:['600 ml','800 ml','500 ml'],ans:'600 ml'},
  {topic:'mesures_diners',text:`La Laura compra <strong>2 kg</strong> de patates. Si 1 kg costa <strong>1,40 €</strong>, quant ha de pagar en total?`,opts:['2,80 €','2,40 €','3,00 €'],ans:'2,80 €'},
  {topic:'mesures_diners',text:`Un paquet de farina pesa <strong>1 kg</strong>. Si fem servir <strong>400 g</strong> per fer un pa de pessic, quants grams queden?`,opts:['600 g','500 g','400 g'],ans:'600 g'},
  {topic:'mesures_diners',text:`En Lluc té <strong>4,20 €</strong> i es gasta <strong>2,50 €</strong> en una joguina de plàstic. Quants diners li queden?`,opts:['1,70 €','2,70 €','1,50 €'],ans:'1,70 €'},
  {topic:'mesures_diners',text:`Quantes ampolles de <strong>500 ml</strong> es poden omplir amb un garrafó de <strong>3 litres</strong> d'aigua?`,opts:['6 ampolles','5 ampolles','4 ampolles'],ans:'6 ampolles'},
  {topic:'mesures_diners',text:`Anem a comprar i portem un bitllet de <strong>20 €</strong>. La compra costa <strong>14,35 €</strong>. Quant ens tornaran de canvi?`,opts:['5,65 €','6,65 €','5,35 €'],ans:'5,65 €'},
  {topic:'mesures_diners',text:`Un formatge sencer pesa <strong>2 kg i 500 g</strong>. Quants grams pesa en total?`,opts:['2.500 g','2.050 g','250 g'],ans:'2.500 g'},
  {topic:'mesures_diners',text:`Una ampolla d'aigua té <strong>1 L i mig</strong> (1.500 ml). Si en bevem <strong>600 ml</strong>, quants mil·lilitres queden?`,opts:['900 ml','800 ml','1.000 ml'],ans:'900 ml'},
  {topic:'mesures_diners',text:`Comprem <strong>4 llibretes</strong> de <strong>2,10 €</strong> cada una. Si paguem amb un bitllet de <strong>10 €</strong>, quant ens tornen?`,opts:['1,60 €','2,40 €','1,80 €'],ans:'1,60 €'},
  {topic:'mesures_diners',text:`En una bossa hi ha <strong>3 paquets de gominoles</strong> que pesen <strong>250 g cadascun</strong>. Quin és el pes total en grams?`,opts:['750 g','500 g','1.000 g'],ans:'750 g'},
  {topic:'mesures_diners',text:`Un cordill de <strong>5 m</strong> es talla a la meitat de manera exacta. Quants centímetres fa cada meitat?`,opts:['250 cm','200 cm','150 cm'],ans:'250 cm'},
  {topic:'mesures_diners',text:`Un quilo de maduixes costa <strong>3,60 €</strong>. Quant costarà <strong>mig quilo</strong> de maduixes?`,opts:['1,80 €','1,50 €','2,00 €'],ans:'1,80 €'},
  {topic:'mesures_diners',text:`Tinc <strong>3 monedes de 2 €</strong> i compro un retolador de <strong>4,15 €</strong>. Quants diners em sobren?`,opts:['1,85 €','2,15 €','1,35 €'],ans:'1,85 €'},

  // ── PROBLEMES: DOS PASSOS (25) ───────────────────────────────────────────────
  {topic:'dos_passos',text:`La <strong>Sara</strong> té <strong>45 cromos</strong>. Li regalen <strong>3 paquets</strong> de <strong>8 cromos</strong> cadascun. Quants cromos té ara?`,opts:['69 cromos','53 cromos','61 cromos'],ans:'69 cromos'},
  {topic:'dos_passos',text:`A la botiga hi ha <strong>96 pomes</strong>. Es posen en bosses de <strong>6</strong>. Es venen <strong>5 bosses</strong>. Quantes pomes queden?`,opts:['66 pomes','56 pomes','76 pomes'],ans:'66 pomes'},
  {topic:'dos_passos',text:`En <strong>Marc</strong> estalvia <strong>8 €</strong> cada setmana durant <strong>5 setmanes</strong>. Llavors gasta <strong>22 €</strong> en un joc. Quants euros li queden?`,opts:['18 €','28 €','10 €'],ans:'18 €'},
  {topic:'dos_passos',text:`Una granja té <strong>7 vaques</strong>. Cada vaca dona <strong>20 L</strong> de llet. Es venen <strong>3 bidons</strong> de <strong>25 L</strong>. Quants litres queden?`,opts:['65 L','70 L','55 L'],ans:'65 L'},
  {topic:'dos_passos',text:`La <strong>Sara</strong> llegeix <strong>12 pàgines</strong> al dia durant <strong>5 dies</strong>. Llavors llegeix <strong>8 pàgines</strong> més. Quantes pàgines ha llegit en total?`,opts:['68 pàgines','60 pàgines','72 pàgines'],ans:'68 pàgines'},
  {topic:'dos_passos',text:`Una botiga rep <strong>4 caixes</strong> de <strong>30 ampolles</strong>. Ven <strong>75 ampolles</strong>. Quantes ampolles li queden?`,opts:['45 ampolles','35 ampolles','55 ampolles'],ans:'45 ampolles'},
  {topic:'dos_passos',text:`En <strong>Pol</strong> té <strong>3 paquets</strong> de <strong>10 galetes</strong>. En menja <strong>1/2</strong> de totes. Quantes galetes menja?`,opts:['15 galetes','10 galetes','20 galetes'],ans:'15 galetes'},
  {topic:'dos_passos',text:`A l'excursió hi participen <strong>6 classes</strong> de <strong>24 alumnes</strong>. Si cada autobús porta <strong>48 persones</strong>, quants autobusos es necessiten?`,opts:['3 autobusos','4 autobusos','2 autobusos'],ans:'3 autobusos'},
  {topic:'dos_passos',text:`La <strong>Sara</strong> té <strong>5 € i 60 cèntims</strong>. Compra <strong>4 cromos</strong> a <strong>0,75 €</strong> cadascun. Quant li queda?`,opts:['2,60 €','1,60 €','3,60 €'],ans:'2,60 €'},
  {topic:'dos_passos',text:`Una recepta per a <strong>4 persones</strong> necessita <strong>200 g</strong> de farina. Si en fem per a <strong>8 persones</strong>, quants grams necessitem? Si cada paquet té <strong>500 g</strong>, quants paquets obrim?`,opts:['1 paquet','2 paquets','3 paquets'],ans:'1 paquet'},
  {topic:'dos_passos',text:`Un pastisser fa <strong>60 pastes</strong> de matí. En ven <strong>42</strong> i després en fa <strong>20</strong> més a la tarda. Quantes pastes té ara?`,opts:['38 pastes','48 pastes','28 pastes'],ans:'38 pastes'},
  {topic:'dos_passos',text:`La Clara compra <strong>3 llibres a 15 € cadascun</strong>. Si paga amb un bitllet de <strong>50 €</strong>, quants diners li han de tornar?`,opts:['5 €','15 €','10 €'],ans:'5 €'},
  {topic:'dos_passos',text:`En un hort es cullen <strong>80 quilos de taronges</strong>. En separen <strong>20 quilos</strong> per fer suc a casa, i la resta es posa en bosses de <strong>5 quilos</strong> per vendre. Quantes bosses fan?`,opts:['12 bosses','10 bosses','15 bosses'],ans:'12 bosses'},
  {topic:'dos_passos',text:`La Joana té <strong>4 capses amb 12 llapis de colors</strong> a cadascuna. Si en perd <strong>6</strong> llapis al pati, quants llapis li queden en total?`,opts:['42 llapis','48 llapis','38 llapis'],ans:'42 llapis'},
  {topic:'dos_passos',text:`A l'autobús escolar hi pugen <strong>35 nens</strong>. A la primera parada en baixen <strong>12</strong> i a la segona en pugen <strong>7</strong> de nous. Quants nens hi ha ara a l'autobús?`,opts:['30 nens','25 nens','28 nens'],ans:'30 nens'},
  {topic:'dos_passos',text:`Un granger té <strong>8 nius</strong> i a cada niu hi ha <strong>6 ous</strong>. Si fa servir <strong>12 ous</strong> per cuinar un gran sopar, quants ous li queden?`,opts:['36 ous','48 ous','24 ous'],ans:'36 ous'},
  {topic:'dos_passos',text:`En Pere té <strong>30 €</strong>. Compra 2 entrades de cinema que costen <strong>8 € cada una</strong>. Quants diners li queden després de pagar?`,opts:['14 €','16 €','22 €'],ans:'14 €'},
  {topic:'dos_passos',text:`Una botiga de roba rep <strong>5 capses amb 10 samarretes cadascuna</strong>. Si ja n'han venut <strong>15</strong> samarretes, quantes samarretes queden al magatzem?`,opts:['35 samarretes','50 samarretes','40 samarretes'],ans:'35 samarretes'},
  {topic:'dos_passos',text:`En Marc compra <strong>4 llibretes a 2 € cada una</strong> i <strong>3 bolígrafs a 1 € cada un</strong>. Quants diners gasta en total?`,opts:['11 €','10 €','12 €'],ans:'11 €'},
  {topic:'dos_passos',text:`Un tren comença el viatge amb <strong>120 passatgers</strong>. A la primera estació en baixen <strong>40</strong> i a la segona en baixen <strong>30</strong> més. Quants passatgers queden al tren?`,opts:['50 passatgers','60 passatgers','70 passatgers'],ans:'50 passatgers'},
  {topic:'dos_passos',text:`La Maria té <strong>3 bitllets de 10 €</strong>. Es compra una samarreta de <strong>18 €</strong>. Quants diners li sobren?`,opts:['12 €','2 €','22 €'],ans:'12 €'},
  {topic:'dos_passos',text:`Tenim <strong>48 globus</strong> d'aigua. Se'n trenquen <strong>8</strong> abans de començar. Els que queden es reparteixen entre <strong>5 nens</strong>. Quants globus rep cada un?`,opts:['8 globus','10 globus','9 globus'],ans:'8 globus'},
  {topic:'dos_passos',text:`En Biel llegeix un llibre de <strong>100 pàgines</strong>. Si llegeix <strong>15 pàgines cada dia durant 6 dies</strong>, quantes pàgines li queden per acabar el llibre?`,opts:['10 pàgines','20 pàgines','5 pàgines'],ans:'10 pàgines'},
  {topic:'dos_passos',text:`Un repartidor porta <strong>3 caixes de refrescos amb 20 ampolles cadascuna</strong>. Si reparteix <strong>45 ampolles</strong> a un bar, quantes ampolles li queden al camió?`,opts:['15 ampolles','25 ampolles','20 ampolles'],ans:'15 ampolles'},
  {topic:'dos_passos',text:`A la biblioteca de l'escola hi ha <strong>4 prestatges amb 25 llibres cada un</strong>. Avui els nens s'han emportat <strong>30 llibres</strong> en préstec. Quants llibres queden allà?`,opts:['70 llibres','100 llibres','80 llibres'],ans:'70 llibres'},
];

function getProbs(topic){return PROBLEMS.filter(p=>p.topic===topic);}