// problems.js — Pool centralitzat de problemes MCQ
// Ús: const PROB_POOL = getProbs('topic');
const PROBLEMS=[
  // ── DIVISIÓ (14) ─────────────────────────────────────────────────────────────
  {topic:'divisio',text:`En Tomàs té <strong>24 pilotes</strong> i les reparteix entre <strong>6 amics</strong> a parts iguals. Quantes pilotes toca a cadascú?`,opts:['4','3','6'],ans:'4'},
  {topic:'divisio',text:`Tenim <strong>35 galetes</strong> i les posem en bosses de <strong>5</strong> galetes. Quantes bosses fem?`,opts:['7','6','40'],ans:'7'},
  {topic:'divisio',text:`Una granja té <strong>45 ous</strong> i els posa en cartrons de <strong>9</strong>. Quants cartrons plens hi ha?`,opts:['5','4','6'],ans:'5'},
  {topic:'divisio',text:`En Pere té <strong>28 euros</strong>. Cada gelat val <strong>4 euros</strong>. Quants gelats pot comprar?`,opts:['7','8','24'],ans:'7'},
  {topic:'divisio',text:`Hi ha <strong>54 alumnes</strong> que van en autobusos de <strong>9 places</strong>. Quants autobusos calen?`,opts:['6','5','7'],ans:'6'},
  {topic:'divisio',text:`Una pastissera fa <strong>36 pastes</strong> i les posa en safates de <strong>6</strong>. Quantes safates omple?`,opts:['6','30','42'],ans:'6'},
  {topic:'divisio',text:`Tenim <strong>49 globus</strong> per repartir entre <strong>7 taules</strong>. Quants globus hi ha a cada taula?`,opts:['7','6','8'],ans:'7'},
  {topic:'divisio',text:`Tenim <strong>72 cartes</strong> i les repartim entre <strong>8 jugadors</strong> a parts iguals. Quantes cartes rep cada jugador?`,opts:['9','8','10'],ans:'9'},
  {topic:'divisio',text:`Una prestatgeria té <strong>40 llibres</strong> repartits en <strong>5 prestatges</strong> iguals. Quants llibres hi ha a cada prestatge?`,opts:['8','7','9'],ans:'8'},
  {topic:'divisio',text:`Tenim <strong>63 euros</strong> per comprar regals de <strong>9 euros</strong> cadascun. Quants regals podem comprar?`,opts:['7','6','8'],ans:'7'},
  {topic:'divisio',text:`Tenim <strong>29 llapis</strong> per repartir en grups de <strong>5</strong>. Quants grups plens fem i quants llapis sobren?`,opts:['5 grups i sobren 4','6 grups i sobren 1','4 grups i sobren 9'],ans:'5 grups i sobren 4'},
  {topic:'divisio',text:`Hi ha <strong>23 alumnes</strong> per fer equips de <strong>4</strong>. Quants equips complets hi ha i quants alumnes sobren?`,opts:['5 equips i sobren 3','4 equips i sobren 7','6 equips i sobren 1'],ans:'5 equips i sobren 3'},
  {topic:'divisio',text:`Tenim <strong>38 galetes</strong> per posar en caixes de <strong>6</strong>. Quantes caixes plenes fem i quantes galetes sobren?`,opts:['6 caixes i sobren 2','5 caixes i sobren 8','7 caixes i sobren 0'],ans:'6 caixes i sobren 2'},
  {topic:'divisio',text:`Tenim <strong>47 euros</strong> per comprar joguines de <strong>8 euros</strong>. Quantes joguines podem comprar i quants euros sobren?`,opts:['5 joguines i sobren 7','6 joguines i sobren 1','4 joguines i sobren 15'],ans:'5 joguines i sobren 7'},

  // ── MULTIPLICACIÓ (12) ───────────────────────────────────────────────────────
  {topic:'multiplicacio',text:`Una capsa té <strong>6 files</strong> de <strong>8 bombons</strong>. Quants bombons hi ha en total?`,opts:['48','42','54'],ans:'48'},
  {topic:'multiplicacio',text:`La <strong>Sara</strong> llegeix <strong>15 pàgines</strong> cada dia. Quantes pàgines llegeix en <strong>7 dies</strong>?`,opts:['105','95','112'],ans:'105'},
  {topic:'multiplicacio',text:`Un autobús té <strong>9 files</strong> de <strong>4 seients</strong>. Quants seients té l'autobús?`,opts:['36','32','40'],ans:'36'},
  {topic:'multiplicacio',text:`Un paquet de cromos té <strong>8 cromos</strong>. Si en compres <strong>12 paquets</strong>, quants cromos tens?`,opts:['96','88','104'],ans:'96'},
  {topic:'multiplicacio',text:`Un granger recull <strong>24 ous</strong> cada dia. Quants ous recull en una <strong>setmana</strong> (7 dies)?`,opts:['168','154','182'],ans:'168'},
  {topic:'multiplicacio',text:`Cada taula de classe té <strong>2 cadires</strong>. Si hi ha <strong>15 taules</strong>, quantes cadires hi ha?`,opts:['30','28','32'],ans:'30'},
  {topic:'multiplicacio',text:`Un cotxe fa <strong>120 km</strong> en una hora. Quants km farà en <strong>4 hores</strong>?`,opts:['480','420','520'],ans:'480'},
  {topic:'multiplicacio',text:`Una ampolla d'aigua costa <strong>85 cèntims</strong>. Quant costen <strong>6 ampolles</strong>?`,opts:['5,10 €','4,80 €','5,40 €'],ans:'5,10 €'},
  {topic:'multiplicacio',text:`Hi ha <strong>365 dies</strong> en un any. Quants dies hi ha en <strong>3 anys</strong>?`,opts:['1.095','1.050','1.100'],ans:'1.095'},
  {topic:'multiplicacio',text:`Una classe té <strong>28 alumnes</strong>. Si cada alumne porta <strong>3 llapis</strong>, quants llapis hi ha en total?`,opts:['84','82','90'],ans:'84'},
  {topic:'multiplicacio',text:`Un rectangle mesura <strong>13 cm</strong> d'ample i <strong>7 cm</strong> d'alt. Quina és la seva àrea?`,opts:['91 cm²','84 cm²','98 cm²'],ans:'91 cm²'},
  {topic:'multiplicacio',text:`La <strong>Sara</strong> estalvia <strong>50 cèntims</strong> cada setmana. Quant tindrà al cap de <strong>12 setmanes</strong>?`,opts:['6 €','5 €','7 €'],ans:'6 €'},

  // ── DINERS (14) ──────────────────────────────────────────────────────────────
  {topic:'diners',text:`La <strong>Maria</strong> té <strong>2 €</strong> i en gasta <strong>75 cèntims</strong>. Quant li queda?`,opts:['1,25 €','1,75 €','1,50 €'],ans:'1,25 €'},
  {topic:'diners',text:`Un gelat costa <strong>1,20 €</strong>. En <strong>Pau</strong> en compra <strong>3</strong>. Quant paga en total?`,opts:['3,60 €','3,20 €','4,20 €'],ans:'3,60 €'},
  {topic:'diners',text:`La <strong>Sara</strong> té <strong>500 cèntims</strong>. Expressa-ho en euros.`,opts:['5 €','50 €','0,50 €'],ans:'5 €'},
  {topic:'diners',text:`Un croissant costa <strong>85 cèntims</strong>. Pagues amb <strong>1 €</strong>. Quant és el canvi?`,opts:['15 cèntims','25 cèntims','5 cèntims'],ans:'15 cèntims'},
  {topic:'diners',text:`La <strong>Laia</strong> té 1 moneda de <strong>2 €</strong>, 2 monedes de <strong>50 cèntims</strong> i 1 de <strong>20 cèntims</strong>. Quant té en total?`,opts:['3,20 €','2,70 €','3,70 €'],ans:'3,20 €'},
  {topic:'diners',text:`Un llibre costa <strong>8,50 €</strong>. Pagues amb un bitllet de <strong>10 €</strong>. Quant et tornen?`,opts:['1,50 €','2,50 €','1 €'],ans:'1,50 €'},
  {topic:'diners',text:`Quants cèntims hi ha en <strong>3,45 €</strong>?`,opts:['345 cèntims','34 cèntims','3.450 cèntims'],ans:'345 cèntims'},
  {topic:'diners',text:`La <strong>botiga</strong> té llapis a <strong>40 cèntims</strong> i bolígrafs a <strong>65 cèntims</strong>. Quant costen <strong>un llapis i un bolígraf</strong>?`,opts:['1,05 €','95 cèntims','1,15 €'],ans:'1,05 €'},
  {topic:'diners',text:`En <strong>Marc</strong> vol comprar una pilota que costa <strong>4,50 €</strong>. Té <strong>2 €</strong> estalviats i la seva mare li dóna <strong>3 €</strong> més. Té prou diners?`,opts:['Sí, li sobren 50 cèntims','No, li falten 50 cèntims','Sí, li sobren 1,50 €'],ans:'Sí, li sobren 50 cèntims'},
  {topic:'diners',text:`Una entrada al cinema costa <strong>6,75 €</strong>. Quants cèntims és això?`,opts:['675 cèntims','67 cèntims','6.750 cèntims'],ans:'675 cèntims'},
  {topic:'diners',text:`La <strong>Marta</strong> compra un suc per <strong>1,30 €</strong> i un entrepà per <strong>2,80 €</strong>. Paga amb un bitllet de <strong>5 €</strong>. Quant li tornen?`,opts:['90 cèntims','1,10 €','1,90 €'],ans:'90 cèntims'},
  {topic:'diners',text:`Quants euros i cèntims són <strong>830 cèntims</strong>?`,opts:['8,30 €','83,00 €','0,83 €'],ans:'8,30 €'},
  {topic:'diners',text:`En <strong>Jordi</strong> estalvia <strong>50 cèntims</strong> cada dia. Al cap d'una setmana (<strong>7 dies</strong>), quants diners té?`,opts:['3,50 €','5 €','7 €'],ans:'3,50 €'},
  {topic:'diners',text:`Una revista costa <strong>2,95 €</strong>. Pagues amb un bitllet de <strong>5 €</strong>. Quant és el canvi?`,opts:['2,05 €','1,95 €','2,50 €'],ans:'2,05 €'},

  // ── ESTADÍSTICA (12) ─────────────────────────────────────────────────────────
  {topic:'estadistica',text:`Al gràfic de la classe, <strong>12 nens</strong> prefereixen futbol i <strong>8 nens</strong> prefereixen natació. Quants nens prefereixen futbol <strong>més</strong> que natació?`,opts:['4 nens','6 nens','2 nens'],ans:'4 nens'},
  {topic:'estadistica',text:`El gràfic mostra que la botiga va vendre <strong>25 pomes el dilluns</strong> i <strong>15 pomes el dimarts</strong>. Quantes pomes va vendre entre els dos dies?`,opts:['40 pomes','35 pomes','45 pomes'],ans:'40 pomes'},
  {topic:'estadistica',text:`En una enquesta, <strong>30 alumnes</strong> van triar el seu color favorit. <strong>12</strong> van triar blau, <strong>10</strong> vermell i la resta verd. Quants van triar verd?`,opts:['8 alumnes','10 alumnes','6 alumnes'],ans:'8 alumnes'},
  {topic:'estadistica',text:`Una sèrie comença a <strong>3</strong> i cada terme <strong>multiplica per 2</strong>. Quin és el <strong>5è terme</strong>?`,opts:['48','32','64'],ans:'48'},
  {topic:'estadistica',text:`El gràfic mostra que la biblioteca va prestar <strong>40 llibres el dilluns, 35 el dimarts i 45 el dimecres</strong>. Quants llibres va prestar en total?`,opts:['120 llibres','110 llibres','130 llibres'],ans:'120 llibres'},
  {topic:'estadistica',text:`Una sèrie suma <strong>+7</strong> cada vegada i comença a <strong>5</strong>. Quin és el <strong>6è terme</strong>?`,opts:['40','42','35'],ans:'40'},
  {topic:'estadistica',text:`Al gràfic hi ha <strong>5 categories</strong>. La més gran té <strong>50 unitats</strong> i la més petita té <strong>15</strong>. Quina és la diferència?`,opts:['35','25','45'],ans:'35'},
  {topic:'estadistica',text:`Una sèrie baixa de <strong>100 de 8 en 8</strong>. El primer terme és <strong>100</strong>. Quin és el <strong>4t terme</strong>?`,opts:['76','68','72'],ans:'76'},
  {topic:'estadistica',text:`En el gràfic de fruites: <strong>Pomes=30, Peres=20, Maduixes=25</strong>. Quantes fruites hi ha en total?`,opts:['75 fruites','65 fruites','80 fruites'],ans:'75 fruites'},
  {topic:'estadistica',text:`La sèrie és: <strong>2, 6, 18, 54...</strong> Quin és el terme que segueix?`,opts:['162','108','72'],ans:'162'},
  {topic:'estadistica',text:`Al gràfic, el <strong>dimecres</strong> es van llegir <strong>18 pàgines</strong>. El <strong>dijous</strong> se'n van llegir el <strong>doble</strong>. Quantes pàgines es van llegir el dijous?`,opts:['36 pàgines','24 pàgines','30 pàgines'],ans:'36 pàgines'},
  {topic:'estadistica',text:`Una sèrie creix de <strong>+15 en +15</strong> i comença a <strong>10</strong>. Quin és el <strong>5è terme</strong>?`,opts:['70','65','75'],ans:'70'},

  // ── GEOMETRIA (10) ───────────────────────────────────────────────────────────
  {topic:'geometria',text:`La <strong>porta</strong> del col·legi és un rectangle de <strong>2 m</strong> d'ample i <strong>3 m</strong> d'alt. Quant mesura el seu perímetre?`,opts:['10 m','6 m','5 m'],ans:'10 m'},
  {topic:'geometria',text:`La <strong>pissarra</strong> de classe és un rectangle de <strong>4 m</strong> d'ample i <strong>2 m</strong> d'alt. Quina és la seva àrea?`,opts:['8 m²','12 m²','6 m²'],ans:'8 m²'},
  {topic:'geometria',text:`Un triangle té angles de <strong>70°</strong> i <strong>60°</strong>. Quant mesura el tercer angle?`,opts:['50°','40°','70°'],ans:'50°'},
  {topic:'geometria',text:`El jardí de l'escola és un quadrat de <strong>5 m</strong> de costat. Quant mesura la tanca (perímetre)?`,opts:['20 m','25 m','15 m'],ans:'20 m'},
  {topic:'geometria',text:`Un triangle rectangle té un angle de <strong>90°</strong> i un altre de <strong>35°</strong>. Quant mesura el tercer?`,opts:['55°','45°','65°'],ans:'55°'},
  {topic:'geometria',text:`La <strong>catifa</strong> del menjador mesura <strong>3 m</strong> × <strong>4 m</strong>. Quina és la seva àrea?`,opts:['12 m²','14 m²','7 m²'],ans:'12 m²'},
  {topic:'geometria',text:`Un triangle equilàter té tots els costats de <strong>6 cm</strong>. Quant mesura el seu perímetre?`,opts:['18 cm','12 cm','24 cm'],ans:'18 cm'},
  {topic:'geometria',text:`La <strong>taula de ping-pong</strong> mesura <strong>5 m</strong> × <strong>3 m</strong>. Quina àrea té?`,opts:['15 m²','16 m²','8 m²'],ans:'15 m²'},
  {topic:'geometria',text:`Un angle de <strong>130°</strong> és un angle...`,opts:['Obtús','Pla','Agut'],ans:'Obtús'},
  {topic:'geometria',text:`Una <strong>habitació quadrada</strong> té <strong>4 m</strong> de costat. Quant mesura el seu perímetre?`,opts:['16 m','8 m','12 m'],ans:'16 m'},

  // ── MESURES DE LONGITUD (14) ─────────────────────────────────────────────────
  {topic:'longitud',text:`La <strong>Marta</strong> té una cinta de <strong>3 m</strong>. En fa servir <strong>75 cm</strong>. Quants centímetres li queden?`,opts:['225 cm','150 cm','275 cm'],ans:'225 cm'},
  {topic:'longitud',text:`En <strong>Joan</strong> fa un recorregut de <strong>2 km</strong> i <strong>500 m</strong> més. Quants metres ha recorregut?`,opts:['2500 m','2050 m','3000 m'],ans:'2500 m'},
  {topic:'longitud',text:`Una taula fa <strong>120 cm</strong> de llarg i un banc fa <strong>85 cm</strong>. Quant sumen les dues mesures?`,opts:['205 cm','195 cm','215 cm'],ans:'205 cm'},
  {topic:'longitud',text:`Una serp fa <strong>2 m</strong> i <strong>30 cm</strong>. Quants centímetres fa en total?`,opts:['230 cm','203 cm','220 cm'],ans:'230 cm'},
  {topic:'longitud',text:`La distància de casa a l'escola és <strong>1 km</strong> i <strong>200 m</strong>. Quants metres és?`,opts:['1200 m','1020 m','1002 m'],ans:'1200 m'},
  {topic:'longitud',text:`El <strong>Pol</strong> té una corda de <strong>5 m</strong> i en talla <strong>180 cm</strong>. Quants centímetres de corda li queden?`,opts:['320 cm','370 cm','280 cm'],ans:'320 cm'},
  {topic:'longitud',text:`Un jardí fa <strong>450 cm</strong> de llarg. Quants metres i centímetres fa?`,opts:['4 m i 50 cm','45 m i 0 cm','4 m i 5 cm'],ans:'4 m i 50 cm'},
  {topic:'longitud',text:`La <strong>Sara</strong> camina <strong>3 km</strong> cada dia. Quants metres camina en <strong>2 dies</strong>?`,opts:['6000 m','3200 m','600 m'],ans:'6000 m'},
  {topic:'longitud',text:`Una piscina olímpica fa <strong>50 m</strong>. Quants centímetres fa?`,opts:['5000 cm','500 cm','5500 cm'],ans:'5000 cm'},
  {topic:'longitud',text:`Un coet vola a <strong>8 km</strong> d'alçada. Quants metres és?`,opts:['8000 m','800 m','80000 m'],ans:'8000 m'},
  {topic:'longitud',text:`Una cinta de <strong>2 m 60 cm</strong> es talla en dues parts iguals. Quant fa cada part?`,opts:['130 cm','260 cm','120 cm'],ans:'130 cm'},
  {topic:'longitud',text:`L'alçada d'un edifici és de <strong>1200 cm</strong>. Quants metres fa?`,opts:['12 m','120 m','1,2 m'],ans:'12 m'},
  {topic:'longitud',text:`En <strong>Marc</strong> té una corda de <strong>4 m</strong>. La talla en trossos de <strong>50 cm</strong>. Quants trossos obté?`,opts:['8 trossos','4 trossos','6 trossos'],ans:'8 trossos'},
  {topic:'longitud',text:`La carretera de poble a poble fa <strong>3 km 400 m</strong>. Quants metres és en total?`,opts:['3400 m','3040 m','3004 m'],ans:'3400 m'},

  // ── VALOR POSICIONAL (10) ────────────────────────────────────────────────────
  {topic:'valor_posicional',text:`El número <strong>34.567</strong> té <strong>quantes desenes de miler</strong>?`,opts:['3','4','5'],ans:'3'},
  {topic:'valor_posicional',text:`El número <strong>128.045</strong> té <strong>quantes centenes</strong>?`,opts:['0','1','8'],ans:'0'},
  {topic:'valor_posicional',text:`Quant val el dígit <strong>7</strong> al número <strong>47.823</strong>?`,opts:['7.000','700','70'],ans:'7.000'},
  {topic:'valor_posicional',text:`Quin número és: <strong>50.000 + 3.000 + 200 + 40 + 1</strong>?`,opts:['53.241','53.421','53.240'],ans:'53.241'},
  {topic:'valor_posicional',text:`Quin número és: <strong>200.000 + 6.000 + 300 + 5</strong>?`,opts:['206.305','260.035','206.350'],ans:'206.305'},
  {topic:'valor_posicional',text:`Al número <strong>85.204</strong>, quin dígit ocupa el lloc de les <strong>centenes</strong>?`,opts:['2','5','8'],ans:'2'},
  {topic:'valor_posicional',text:`Quin número és: <strong>4 desenes de miler + 3 centenes + 7 unitats</strong>?`,opts:['40.307','43.007','40.037'],ans:'40.307'},
  {topic:'valor_posicional',text:`Quant val el dígit <strong>9</strong> al número <strong>390.412</strong>?`,opts:['90.000','9.000','900'],ans:'90.000'},
  {topic:'valor_posicional',text:`El número <strong>508.030</strong> té <strong>quantes unitats de miler</strong>?`,opts:['8','5','0'],ans:'8'},
  {topic:'valor_posicional',text:`Quin número és: <strong>3 centenes de miler + 5 desenes + 2 unitats</strong>?`,opts:['300.052','300.520','305.002'],ans:'300.052'},

  // ── PROBLEMES: SUMES I RESTES (12) ──────────────────────────────────────────
  {topic:'sumes_restes',text:`La <strong>Maria</strong> té <strong>234</strong> cromos i en rep <strong>127</strong> més. Quants cromos té ara?`,opts:['361 cromos','307 cromos','371 cromos'],ans:'361 cromos'},
  {topic:'sumes_restes',text:`En <strong>Pau</strong> tenia <strong>500 €</strong> i en gasta <strong>178 €</strong>. Quants euros li queden?`,opts:['322 €','378 €','312 €'],ans:'322 €'},
  {topic:'sumes_restes',text:`A la classe hi ha <strong>28 nens</strong>. En surten <strong>9</strong>. Quants queden a classe?`,opts:['19 nens','17 nens','21 nens'],ans:'19 nens'},
  {topic:'sumes_restes',text:`Una botiga tenia <strong>560 pomes</strong>. Ven <strong>234</strong>. Quantes pomes li queden?`,opts:['326 pomes','336 pomes','316 pomes'],ans:'326 pomes'},
  {topic:'sumes_restes',text:`En <strong>Marc</strong> porta <strong>275 cromos</strong> i en dona <strong>132</strong> al seu germà. Quants li queden?`,opts:['143 cromos','153 cromos','133 cromos'],ans:'143 cromos'},
  {topic:'sumes_restes',text:`Al parc hi ha <strong>58 ocells</strong>. En volen <strong>23</strong>. Quants ocells queden al parc?`,opts:['35 ocells','45 ocells','25 ocells'],ans:'35 ocells'},
  {topic:'sumes_restes',text:`L'escola té <strong>324 alumnes</strong>. N'arriben <strong>48</strong> nous. Quants alumnes hi ha en total?`,opts:['372 alumnes','362 alumnes','382 alumnes'],ans:'372 alumnes'},
  {topic:'sumes_restes',text:`La <strong>iaia</strong> tenia <strong>480 botons</strong>. En regala <strong>195</strong>. Quants botons li queden?`,opts:['285 botons','295 botons','275 botons'],ans:'285 botons'},
  {topic:'sumes_restes',text:`En <strong>Tom</strong> tenia <strong>96 punts</strong> al joc i en perd <strong>37</strong>. Quants punts té ara?`,opts:['59 punts','69 punts','49 punts'],ans:'59 punts'},
  {topic:'sumes_restes',text:`Una prestatgeria té <strong>145 llibres</strong>. N'afegim <strong>38</strong>. Quants llibres hi ha?`,opts:['183 llibres','173 llibres','193 llibres'],ans:'183 llibres'},
  {topic:'sumes_restes',text:`El <strong>supermercat</strong> ven <strong>412 ampolles</strong> el dilluns i <strong>287</strong> el dimarts. Quantes ampolles ha venut en total?`,opts:['699 ampolles','689 ampolles','709 ampolles'],ans:'699 ampolles'},
  {topic:'sumes_restes',text:`Una caixa tenia <strong>350 llàpissos</strong>. En treiem <strong>126</strong>. Quants llàpissos queden?`,opts:['224 llàpissos','234 llàpissos','214 llàpissos'],ans:'224 llàpissos'},

  // ── PROBLEMES: MULTIPLICACIÓ I DIVISIÓ (12) ──────────────────────────────────
  {topic:'mult_div',text:`La <strong>Sara</strong> compra <strong>6 paquets</strong> de cromos. Cada paquet té <strong>8 cromos</strong>. Quants cromos té?`,opts:['48 cromos','42 cromos','56 cromos'],ans:'48 cromos'},
  {topic:'mult_div',text:`En una classe hi ha <strong>4 files</strong> de <strong>7 cadires</strong>. Quantes cadires hi ha en total?`,opts:['28 cadires','24 cadires','32 cadires'],ans:'28 cadires'},
  {topic:'mult_div',text:`Repartim <strong>72 llàpissos</strong> entre <strong>9 nens</strong> a parts iguals. Quants llàpissos rep cada nen?`,opts:['8 llàpissos','7 llàpissos','9 llàpissos'],ans:'8 llàpissos'},
  {topic:'mult_div',text:`Una granja té <strong>8 gallines</strong>. Cada gallina pon <strong>5 ous</strong> al dia. Quants ous ponen totes juntes?`,opts:['40 ous','48 ous','35 ous'],ans:'40 ous'},
  {topic:'mult_div',text:`Comprem <strong>5 llibres</strong> a <strong>12 €</strong> cadascun. Quant paguem en total?`,opts:['60 €','50 €','70 €'],ans:'60 €'},
  {topic:'mult_div',text:`Tenim <strong>84 taronges</strong> i les posem en caixes de <strong>7</strong>. Quantes caixes fem?`,opts:['12 caixes','14 caixes','10 caixes'],ans:'12 caixes'},
  {topic:'mult_div',text:`En <strong>Marc</strong> llegeix <strong>9 pàgines</strong> cada dia. Quantes pàgines llegeix en <strong>8 dies</strong>?`,opts:['72 pàgines','63 pàgines','81 pàgines'],ans:'72 pàgines'},
  {topic:'mult_div',text:`Una caixa porta <strong>6 ampolles</strong>. Quantes ampolles hi ha en <strong>7 caixes</strong>?`,opts:['42 ampolles','36 ampolles','48 ampolles'],ans:'42 ampolles'},
  {topic:'mult_div',text:`Tenim <strong>90 fotocòpies</strong> per repartir en carpetes de <strong>9</strong>. Quantes carpetes necessitem?`,opts:['10 carpetes','9 carpetes','11 carpetes'],ans:'10 carpetes'},
  {topic:'mult_div',text:`En <strong>Pol</strong> estalvia <strong>7 €</strong> cada setmana. Quants euros estalviarà en <strong>6 setmanes</strong>?`,opts:['42 €','35 €','49 €'],ans:'42 €'},
  {topic:'mult_div',text:`Una escola té <strong>6 classes</strong> amb <strong>25 alumnes</strong> cadascuna. Quants alumnes té l'escola?`,opts:['150 alumnes','130 alumnes','160 alumnes'],ans:'150 alumnes'},
  {topic:'mult_div',text:`Tenim <strong>56 pastanagues</strong> per repartir entre <strong>7 conills</strong>. Quantes rep cada conill?`,opts:['8 pastanagues','7 pastanagues','9 pastanagues'],ans:'8 pastanagues'},

  // ── PROBLEMES: FRACCIONS (11) ────────────────────────────────────────────────
  {topic:'fraccions_contexte',text:`Una pizza té <strong>8 trossos</strong>. La Sara en menja <strong>3</strong> i en Marc en menja <strong>2</strong>. Quants trossos han menjat entre tots dos?`,opts:['5 trossos','4 trossos','6 trossos'],ans:'5 trossos'},
  {topic:'fraccions_contexte',text:`La <strong>Sara</strong> té <strong>20 cromos</strong> i en dona <strong>1/4</strong> al seu germà. Quants cromos dona?`,opts:['5 cromos','4 cromos','10 cromos'],ans:'5 cromos'},
  {topic:'fraccions_contexte',text:`De <strong>30 nens</strong>, <strong>1/3</strong> porten barret. Quants nens porten barret?`,opts:['10 nens','15 nens','6 nens'],ans:'10 nens'},
  {topic:'fraccions_contexte',text:`Tenim <strong>16 boles</strong>. <strong>3/4</strong> són vermelles. Quantes boles vermelles hi ha?`,opts:['12 boles','8 boles','4 boles'],ans:'12 boles'},
  {topic:'fraccions_contexte',text:`Un pastís es divideix en <strong>6 parts iguals</strong>. En mengem <strong>2 parts</strong>. Quines parts queden?`,opts:['4 parts','3 parts','5 parts'],ans:'4 parts'},
  {topic:'fraccions_contexte',text:`La <strong>Sara</strong> té <strong>24 galetes</strong>. En menja <strong>1/2</strong>. Quantes galetes ha menjat?`,opts:['12 galetes','8 galetes','6 galetes'],ans:'12 galetes'},
  {topic:'fraccions_contexte',text:`Un cub té <strong>6 cares</strong>. Pintem <strong>1/3</strong> de les cares. Quantes cares pintem?`,opts:['2 cares','3 cares','4 cares'],ans:'2 cares'},
  {topic:'fraccions_contexte',text:`Una cinta de <strong>30 cm</strong> es divideix en <strong>5 parts iguals</strong>. Quant fa cada part?`,opts:['6 cm','5 cm','7 cm'],ans:'6 cm'},
  {topic:'fraccions_contexte',text:`Tenim <strong>3/5</strong> d'una cinta de <strong>25 cm</strong>. Quants centímetres és?`,opts:['15 cm','10 cm','20 cm'],ans:'15 cm'},
  {topic:'fraccions_contexte',text:`La <strong>Sara</strong> menja <strong>2/8</strong> d'una pizza. El seu germà menja <strong>3/8</strong>. Quina fracció han menjat entre tots dos?`,opts:['5/8','4/8','6/8'],ans:'5/8'},
  {topic:'fraccions_contexte',text:`Tenim <strong>40 boletes</strong>. <strong>1/4</strong> són blaves, <strong>1/2</strong> vermelles i la resta verdes. Quantes boletes verdes hi ha?`,opts:['10 boletes','15 boletes','20 boletes'],ans:'10 boletes'},

  // ── PROBLEMES: MESURES I DINERS (12) ────────────────────────────────────────
  {topic:'mesures_diners',text:`Una ampolla de <strong>2 L</strong> es buida en gots de <strong>250 ml</strong>. Quants gots s'omplen?`,opts:['8 gots','6 gots','10 gots'],ans:'8 gots'},
  {topic:'mesures_diners',text:`La <strong>Maria</strong> compra <strong>3 m</strong> de cinta i en fa servir <strong>120 cm</strong>. Quants centímetres li queden?`,opts:['180 cm','150 cm','200 cm'],ans:'180 cm'},
  {topic:'mesures_diners',text:`Tenim <strong>4 ampolles</strong> de <strong>750 ml</strong>. Quants litres tenim en total?`,opts:['3 L','4 L','2 L'],ans:'3 L'},
  {topic:'mesures_diners',text:`La distància entre dues ciutats és de <strong>45 km</strong>. Quants metres és?`,opts:['45 000 m','4 500 m','450 m'],ans:'45 000 m'},
  {topic:'mesures_diners',text:`Una corda de <strong>3 m</strong> es talla en trossos de <strong>50 cm</strong>. Quants trossos n'obtenim?`,opts:['6 trossos','5 trossos','8 trossos'],ans:'6 trossos'},
  {topic:'mesures_diners',text:`En <strong>Joan</strong> té <strong>5 €</strong>. Compra un suc que val <strong>1,50 €</strong>. Quant canvi rep?`,opts:['3,50 €','2,50 €','4,50 €'],ans:'3,50 €'},
  {topic:'mesures_diners',text:`Una recepta necessita <strong>250 ml</strong> de llet. Si en tenim <strong>1 L</strong>, quants ml de llet ens sobren?`,opts:['750 ml','500 ml','600 ml'],ans:'750 ml'},
  {topic:'mesures_diners',text:`Comprem <strong>3 iogurts</strong> a <strong>0,80 €</strong> cadascun. Quant paguem?`,opts:['2,40 €','2,00 €','3,00 €'],ans:'2,40 €'},
  {topic:'mesures_diners',text:`Un recipient té <strong>5 L</strong> d'aigua. N'aboquem <strong>2 L i 500 ml</strong>. Quants mil·lilitres queden?`,opts:['2 500 ml','3 000 ml','2 000 ml'],ans:'2 500 ml'},
  {topic:'mesures_diners',text:`La <strong>Sara</strong> porta <strong>10 €</strong>. Compra un llapis per <strong>1,20 €</strong> i un quadern per <strong>2,50 €</strong>. Quant li queda?`,opts:['6,30 €','7,30 €','5,30 €'],ans:'6,30 €'},
  {topic:'mesures_diners',text:`Una piscina fa <strong>25 m</strong>. La Sara la neda <strong>4 vegades</strong>. Quants metres ha nedat en total?`,opts:['100 m','80 m','120 m'],ans:'100 m'},
  {topic:'mesures_diners',text:`Comprem <strong>6 pomes</strong> a <strong>0,35 €</strong> cadascuna. Quant paguem?`,opts:['2,10 €','1,80 €','2,40 €'],ans:'2,10 €'},

  // ── PROBLEMES: DOS PASSOS (10) ───────────────────────────────────────────────
  {topic:'dos_passos',text:`La <strong>Sara</strong> té <strong>45 cromos</strong>. Li regalen <strong>3 paquets</strong> de <strong>8 cromos</strong> cadascun. Quants cromos té ara?`,opts:['69 cromos','53 cromos','61 cromos'],ans:'69 cromos'},
  {topic:'dos_passos',text:`A la botiga hi ha <strong>96 pomes</strong>. Es posen en bosses de <strong>6</strong>. Es venen <strong>5 bosses</strong>. Quantes pomes queden?`,opts:['66 pomes','56 pomes','76 pomes'],ans:'66 pomes'},
  {topic:'dos_passos',text:`En <strong>Marc</strong> estalvia <strong>8 €</strong> cada setmana durant <strong>5 setmanes</strong>. Llavors gasta <strong>22 €</strong> en un joc. Quants euros li queden?`,opts:['18 €','28 €','10 €'],ans:'18 €'},
  {topic:'dos_passos',text:`Una granja té <strong>7 vaques</strong>. Cada vaca dona <strong>20 L</strong> de llet. Es venen <strong>3 bidons</strong> de <strong>25 L</strong>. Quants litres queden?`,opts:['65 L','70 L','55 L'],ans:'65 L'},
  {topic:'dos_passos',text:`La <strong>Sara</strong> llegeix <strong>12 pàgines</strong> al dia durant <strong>5 dies</strong>. Llavors llegeix <strong>8 pàgines</strong> més. Quantes pàgines ha llegit en total?`,opts:['68 pàgines','60 pàgines','72 pàgines'],ans:'68 pàgines'},
  {topic:'dos_passos',text:`Una botiga rep <strong>4 caixes</strong> de <strong>30 ampolles</strong>. Ven <strong>75 ampolles</strong>. Quantes ampolles li queden?`,opts:['45 ampolles','35 ampolles','55 ampolles'],ans:'45 ampolles'},
  {topic:'dos_passos',text:`En <strong>Pol</strong> té <strong>3 paquets</strong> de <strong>10 galetes</strong>. En menja <strong>1/2</strong> de totes. Quantes galetes menja?`,opts:['15 galetes','10 galetes','20 galetes'],ans:'15 galetes'},
  {topic:'dos_passos',text:`A l'excursió hi participen <strong>6 classes</strong> de <strong>24 alumnes</strong>. Si cada autobús porta <strong>48 persones</strong>, quants autobusos es necessiten?`,opts:['3 autobusos','4 autobusos','2 autobusos'],ans:'3 autobusos'},
  {topic:'dos_passos',text:`La <strong>Sara</strong> té <strong>5 € i 60 cèntims</strong>. Compra <strong>4 cromos</strong> a <strong>0,75 €</strong> cadascun. Quant li queda?`,opts:['2,60 €','1,60 €','3,60 €'],ans:'2,60 €'},
  {topic:'dos_passos',text:`Una recepta per a <strong>4 persones</strong> necessita <strong>200 g</strong> de farina. Si en fem per a <strong>8 persones</strong>, quants grams necessitem? Si cada paquet té <strong>500 g</strong>, quants paquets obrim?`,opts:['1 paquet','2 paquets','3 paquets'],ans:'1 paquet'},
];

function getProbs(topic){return PROBLEMS.filter(p=>p.topic===topic);}
