// morfologia_data.js — pools de dades per a catala_morfologia.html

const PLURAL_POOL = [
  // Del PDF (acts. 1, 8)
  {s:'calaix',   p:'calaixos',    w:['calaixs','caixes','caixetes']},
  {s:'cordó',    p:'cordons',     w:['cordós','cordes','cordones']},
  {s:'faldilla', p:'faldilles',   w:['faldillas','faldillos','faldills']},
  {s:'disc',     p:'discos',      w:['discs','disques','disces']},
  {s:'músic',    p:'músics',      w:['musicos','músiques','musicots']},
  {s:'masia',    p:'masies',      w:['masias','masions','masieses']},
  {s:'figa',     p:'figues',      w:['figas','figes','figons']},
  {s:'gos',      p:'gossos',      w:['gosos','goss','goses']},
  {s:'braç',     p:'braços',      w:['braçs','brassos','bracets']},
  {s:'tros',     p:'trossos',     w:['trosos','tross','trossets']},
  {s:'pastís',   p:'pastissos',   w:['pastiss','pastises','pastisos']},
  {s:'peix',     p:'peixos',      w:['peixs','peixes','peixetes']},
  {s:'camió',    p:'camions',     w:['camiós','camiones','camioses']},
  {s:'país',     p:'països',      w:['paiss','paisos','paisses']},
  {s:'llapis',   p:'llapis',      w:['llapises','llapissos','llapiss']},
  // Ampliació
  {s:'avió',     p:'avions',      w:['avios','aviós','avioles']},
  {s:'arbre',    p:'arbres',      w:['arbros','arbresos','arbrejos']},
  {s:'cotxe',    p:'cotxes',      w:['cotxos','cotxesos','cotxis']},
  {s:'gat',      p:'gats',        w:['gatos','gatoes','gatsos']},
  {s:'nen',      p:'nens',        w:['nenos','nenes','nenis']},
  {s:'flor',     p:'flors',       w:['flores','florsos','floris']},
  {s:'dent',     p:'dents',       w:['dentes','dentos','dentses']},
  {s:'color',    p:'colors',      w:['colores','colorsos','colorets']},
  {s:'nas',      p:'nassos',      w:['nass','nasos','nases']},
  {s:'peu',      p:'peus',        w:['pies','peues','peuns']},
  {s:'ull',      p:'ulls',        w:['ullos','ulos','ulles']},
  {s:'guix',     p:'guixos',      w:['guixs','guixes','guixets']},
  {s:'ós',       p:'ossos',       w:['óss','osos','oses']},
  {s:'globus',   p:'globus',      w:['globusos','globuss','globussos']},
  {s:'llauna',   p:'llaunes',     w:['llaunas','llaunos','llaunis']},
];

const ACCENT_POOL = [
  // Agudes (tònic a la darrera síl·laba)
  {syl:'ca · mí',         t:'aguda'},
  {syl:'bal · có',        t:'aguda'},
  {syl:'pas · tís',       t:'aguda'},
  {syl:'jar · dí',        t:'aguda'},
  {syl:'ca · fè',         t:'aguda'},
  {syl:'cor · dó',        t:'aguda'},
  {syl:'ca · lor',        t:'aguda'},
  {syl:'a · mor',         t:'aguda'},
  {syl:'a · vi · ó',      t:'aguda'},
  {syl:'bo · tó',         t:'aguda'},
  // Planes (tònic a la penúltima síl·laba)
  {syl:'tau · la',        t:'plana'},
  {syl:'por · ta',        t:'plana'},
  {syl:'fes · ta',        t:'plana'},
  {syl:'ar · bre',        t:'plana'},
  {syl:'lla · pis',       t:'plana'},
  {syl:'mes · tre',       t:'plana'},
  {syl:'cot · xe',        t:'plana'},
  {syl:'car · ta',        t:'plana'},
  {syl:'ne · na',         t:'plana'},
  {syl:'pis · ta',        t:'plana'},
  {syl:'fi · nes · tra',  t:'plana'},
  {syl:'es · co · la',    t:'plana'},
  // Esdrúixoles (tònic a l'antepenúltima síl·laba)
  {syl:'mú · si · ca',    t:'esdrúixola'},
  {syl:'pà · gi · na',    t:'esdrúixola'},
  {syl:'à · li · ga',     t:'esdrúixola'},
  {syl:'gà · bi · a',     t:'esdrúixola'},
  {syl:'mà · qui · na',   t:'esdrúixola'},
  {syl:'fà · bri · ca',   t:'esdrúixola'},
  {syl:'rà · pi · da',    t:'esdrúixola'},
  {syl:'pràc · ti · ca',  t:'esdrúixola'},
];
const ACCENT_OPTS = ['aguda', 'plana', 'esdrúixola'];

const ANTON_POOL = [
  // Del PDF (act. 3)
  {w:'trista',      a:'alegre',       wrong:['silenciosa','poruca','xerraire']},
  {w:'xerraire',    a:'callat',       wrong:['alegre','agradable','trist']},
  {w:'silenciós',   a:'sorollós',     wrong:['valent','callat','agradable']},
  {w:'poruc',       a:'valent',       wrong:['sorollós','alegre','callat']},
  {w:'agradable',   a:'desagradable', wrong:['silenciós','valent','xerraire']},
  // Ampliació
  {w:'alt',         a:'baix',         wrong:['gran','ràpid','fort']},
  {w:'ràpid',       a:'lent',         wrong:['alt','petit','calent']},
  {w:'calent',      a:'fred',         wrong:['suau','dur','tou']},
  {w:'gran',        a:'petit',        wrong:['ràpid','fort','fred']},
  {w:'fort',        a:'dèbil',        wrong:['lent','gran','petit']},
  {w:'net',         a:'brut',         wrong:['tou','dur','lent']},
  {w:'dur',         a:'tou',          wrong:['net','alt','fred']},
  {w:'vell',        a:'jove',         wrong:['brut','dèbil','lent']},
  {w:'obert',       a:'tancat',       wrong:['fred','net','dur']},
  {w:'llarg',       a:'curt',         wrong:['ample','petit','baix']},
  {w:'ple',         a:'buit',         wrong:['petit','fred','dur']},
  {w:'prim',        a:'gros',         wrong:['llarg','gran','fred']},
  {w:'feliç',       a:'trist',        wrong:['jove','baix','dèbil']},
  {w:'fàcil',       a:'difícil',      wrong:['fred','ric','gran']},
  {w:'nou',         a:'vell',         wrong:['fred','gran','ric']},
  {w:'fosc',        a:'clar',         wrong:['ric','gran','lent']},
  {w:'ample',       a:'estret',       wrong:['petit','baix','lent']},
  {w:'dolç',        a:'amarg',        wrong:['fred','ràpid','petit']},
  {w:'ric',         a:'pobre',        wrong:['petit','fosc','lent']},
  {w:'lluny',       a:'prop',         wrong:['fosc','ric','petit']},
  {w:'primer',      a:'últim',        wrong:['petit','gran','llarg']},
  {w:'fred',        a:'calent',       wrong:['ric','baix','lent']},
  {w:'gros',        a:'prim',         wrong:['llarg','baix','fosc']},
  {w:'dret',        a:'torçat',       wrong:['dur','fosc','petit']},
  {w:'clar',        a:'fosc',         wrong:['ràpid','gran','fred']},
];

const ART_POOL = [
  // Del PDF (act. 8)
  {s:'la ceba',      p:'les cebes',     w:['la cebes','els cebes','les ceba']},
  {s:'la magrana',   p:'les magranes',  w:['la magranes','els magranes','les magrana']},
  {s:'la pruna',     p:'les prunes',    w:['la prunes','els prunes','les pruna']},
  {s:'la cirera',    p:'les cireres',   w:['la cireres','els cireres','les cirera']},
  {s:'la pera',      p:'les peres',     w:['la peres','els peres','les pera']},
  {s:'la maduixa',   p:'les maduixes',  w:['la maduixes','els maduixes','les maduixa']},
  {s:"l'ametlla",    p:'les ametlles',  w:["l'ametlles",'els ametlles','les ametlla']},
  {s:'la taula',     p:'les taules',    w:['la taules','els taules','les taula']},
  {s:'la porta',     p:'les portes',    w:['la portes','els portes','les porta']},
  {s:"l'escola",     p:'les escoles',   w:["l'escoles",'els escoles','les escola']},
  {s:'la pilota',    p:'les pilotes',   w:['la pilotes','els pilotes','les pilota']},
  {s:"l'àguila",     p:'les àguiles',   w:["l'àguiles",'els àguiles','les àguila']},
  // Ampliació
  {s:'la nena',      p:'les nenes',     w:['la nenes','els nenes','les nena']},
  {s:'la bossa',     p:'les bosses',    w:['la bosses','els bosses','les bossa']},
  {s:'la gallina',   p:'les gallines',  w:['la gallines','els gallines','les gallina']},
  {s:'la cadira',    p:'les cadires',   w:['la cadires','els cadires','les cadira']},
  {s:'la casa',      p:'les cases',     w:['la cases','els cases','les casa']},
  {s:'la flor',      p:'les flors',     w:['la flors','els flors','les flor']},
  {s:'la finestra',  p:'les finestres', w:['la finestres','els finestres','les finestra']},
  {s:"l'ovella",     p:'les ovelles',   w:["l'ovelles",'els ovelles','les ovella']},
  {s:"l'abella",     p:'les abelles',   w:["l'abelles",'els abelles','les abella']},
  {s:"l'oca",        p:'les oques',     w:["l'oques",'els oques','les oca']},
  {s:"l'orella",     p:'les orelles',   w:["l'orelles",'els orelles','les orella']},
  {s:'la cançó',     p:'les cançons',   w:['la cançons','els cançons','les cançó']},
  {s:'la campana',   p:'les campanes',  w:['la campanes','els campanes','les campana']},
];

const VB_POOL = [
  // Del PDF (act. 12)
  {word:'am_ulància', ans:'B', full:'ambulància',  hint:'amb- (al costat de) porta B'},
  {word:'con_ersa',   ans:'V', full:'conversa',    hint:'con- + vocal sol portar V'},
  {word:'o_rador',    ans:'B', full:'obrador',     hint:'ob- porta B'},
  {word:'sa_iesa',    ans:'V', full:'saviesa',     hint:'Savi i derivats porten V'},
  {word:'_lanc',      ans:'B', full:'blanc',       hint:'La paraula blanc comença amb B'},
  {word:'canta_a',    ans:'V', full:'cantava',     hint:"L'imperfet (-ava) porta V"},
  {word:'no_embre',   ans:'V', full:'novembre',    hint:'Novembre i febrer porten V'},
  {word:'_icicleta',  ans:'B', full:'bicicleta',   hint:'Bici- comença amb B'},
  {word:'_iatge',     ans:'V', full:'viatge',      hint:'Viatge i derivats porten V'},
  {word:'ha_er',      ans:'V', full:'haver',       hint:"L'auxiliar haver porta V"},
  {word:'o_rir',      ans:'B', full:'obrir',       hint:'ob- porta B'},
  {word:'sa_i',       ans:'V', full:'savi',        hint:'Savi i derivats porten V'},
  {word:'_estit',     ans:'V', full:'vestit',      hint:'Vestit (roba) porta V'},
  {word:'_eure',      ans:'V', full:'veure',       hint:'Veure porta V; beure porta B'},
  {word:'escri_ia',   ans:'V', full:'escrivia',    hint:"L'imperfet porta V"},
  {word:'_ota',       ans:'B', full:'bota',        hint:'Bota (calçat/barril) porta B'},
  {word:'_oca',       ans:'B', full:'boca',        hint:'Boca porta B'},
  {word:'a_is',       ans:'V', full:'avis',        hint:'Avi (avi/àvia) i derivats porten V'},
  // Ampliació
  {word:'_erd',       ans:'V', full:'verd',        hint:'El color verd porta V'},
  {word:'_arri',      ans:'B', full:'barri',       hint:'Barri (zona de la ciutat) porta B'},
  {word:'_ida',       ans:'V', full:'vida',        hint:'Vida porta V'},
  {word:'_olant',     ans:'V', full:'volant',      hint:'Volar i derivats porten V'},
  {word:'can_i',      ans:'V', full:'canvi',       hint:'Canvi i derivats porten V'},
  {word:'pro_a',      ans:'V', full:'prova',       hint:'Prova porta V'},
  {word:'esta_le',    ans:'B', full:'estable',     hint:'Les paraules en -ble porten B'},
  {word:'acti_itat',  ans:'V', full:'activitat',   hint:'Actiu i derivats porten V'},
  {word:'auto_ús',    ans:'B', full:'autobús',     hint:'Autobús porta B'},
  {word:'cla_ell',    ans:'V', full:'clavell',     hint:'Clavell (flor) porta V'},
  {word:'_entall',    ans:'V', full:'ventall',     hint:'Vent i derivats porten V'},
  {word:'su_marí',    ans:'B', full:'submarí',     hint:'Sub- (sota) sempre porta B'},
];

const CAT_POOL = [
  // Del PDF (act. 13)
  {w:'menjo',        cat:'verb',     exp:'Menjar és un verb (acció).'},
  {w:'crispetes',    cat:'nom',      exp:'Crispetes és un nom (cosa).'},
  {w:'rocoses',      cat:'adjectiu', exp:'Rocoses descriu una qualitat.'},
  {w:'taula',        cat:'nom',      exp:'Taula és un nom (cosa).'},
  {w:'amaguen',      cat:'verb',     exp:'Amagar és un verb (acció).'},
  {w:'lluminós',     cat:'adjectiu', exp:'Lluminós descriu una qualitat.'},
  {w:'escric',       cat:'verb',     exp:'Escriure és un verb (acció).'},
  {w:'cansats',      cat:'adjectiu', exp:'Cansats descriu un estat.'},
  {w:'finestra',     cat:'nom',      exp:'Finestra és un nom (cosa).'},
  {w:'somio',        cat:'verb',     exp:'Somiar és un verb (acció).'},
  {w:'alegre',       cat:'adjectiu', exp:'Alegre descriu una qualitat.'},
  {w:'amic',         cat:'nom',      exp:'Amic és un nom (persona).'},
  {w:'comprèn',      cat:'verb',     exp:'Comprendre és un verb (acció).'},
  {w:'intel·ligent', cat:'adjectiu', exp:'Intel·ligent descriu una qualitat.'},
  {w:'biblioteca',   cat:'nom',      exp:'Biblioteca és un nom (lloc).'},
  {w:'corren',       cat:'verb',     exp:'Córrer és un verb (acció).'},
  {w:'vermell',      cat:'adjectiu', exp:'Vermell és un adjectiu de color.'},
  {w:'música',       cat:'nom',      exp:'Música és un nom.'},
  {w:'salten',       cat:'verb',     exp:'Saltar és un verb (acció).'},
  {w:'suau',         cat:'adjectiu', exp:'Suau descriu una qualitat.'},
  // Ampliació — verbs
  {w:'llegeix',      cat:'verb',     exp:'Llegir és un verb (acció).'},
  {w:'escolta',      cat:'verb',     exp:'Escoltar és un verb (acció).'},
  {w:'dibuixa',      cat:'verb',     exp:'Dibuixar és un verb (acció).'},
  {w:'neda',         cat:'verb',     exp:'Nedar és un verb (acció).'},
  {w:'pensa',        cat:'verb',     exp:'Pensar és un verb (acció).'},
  {w:'vola',         cat:'verb',     exp:'Volar és un verb (acció).'},
  // Ampliació — noms
  {w:'cotxe',        cat:'nom',      exp:'Cotxe és un nom (cosa).'},
  {w:'sol',          cat:'nom',      exp:'Sol és un nom (astre).'},
  {w:'jardí',        cat:'nom',      exp:'Jardí és un nom (lloc).'},
  {w:'pedra',        cat:'nom',      exp:'Pedra és un nom (cosa).'},
  {w:'núvol',        cat:'nom',      exp:'Núvol és un nom (fenomen natural).'},
  {w:'cadira',       cat:'nom',      exp:'Cadira és un nom (cosa).'},
  // Ampliació — adjectius
  {w:'petit',        cat:'adjectiu', exp:'Petit descriu una mida.'},
  {w:'rodó',         cat:'adjectiu', exp:'Rodó descriu una forma.'},
  {w:'fresc',        cat:'adjectiu', exp:'Fresc descriu una qualitat.'},
  {w:'difícil',      cat:'adjectiu', exp:'Difícil descriu una qualitat.'},
  {w:'net',          cat:'adjectiu', exp:'Net descriu un estat.'},
  {w:'valent',       cat:'adjectiu', exp:'Valent descriu una qualitat.'},
];
const CAT_OPTS = ['nom', 'verb', 'adjectiu'];

// base: paraula SENSE accent (forma que es mostra a l'alumne)
// full: forma correcta (amb accent o sense si no en necessita)
// w:    2 opcions incorrectes (amb accent erroni o mal col·locat)
const TIPUSACC_POOL = [
  // Cal accent OBERT (à, è, ò)
  {base:'cafe',    full:'cafè',    w:['café','cafe'],       hint:"cafè porta accent obert (è) — so obert"},
  {base:'pero',    full:'però',    w:['peró','pero'],       hint:"però porta accent obert (ò) — so obert"},
  {base:'rapid',   full:'ràpid',   w:['rápid','rapid'],     hint:"ràpid porta accent obert (à)"},
  {base:'frances', full:'francès', w:['francés','frances'], hint:"francès porta accent obert (è)"},
  {base:'angles',  full:'anglès',  w:['anglés','angles'],   hint:"anglès porta accent obert (è)"},
  {base:'magic',   full:'màgic',   w:['mágic','magic'],     hint:"màgic porta accent obert (à)"},
  {base:'bestia',  full:'bèstia',  w:['béstia','bestia'],   hint:"bèstia porta accent obert (è)"},
  {base:'pagina',  full:'pàgina',  w:['página','pagina'],   hint:"pàgina porta accent obert (à)"},
  // Cal accent TANCAT (é, í, ó, ú)
  {base:'cami',    full:'camí',    w:['càmi','cami'],       hint:"camí porta accent tancat (í) — la í és sempre tancada"},
  {base:'pastis',  full:'pastís',  w:['pàstis','pastis'],   hint:"pastís porta accent tancat (í) — la í és sempre tancada"},
  {base:'cordo',   full:'cordó',   w:['còrdo','cordo'],     hint:"cordó porta accent tancat (ó) — la ó de cordó és tancada"},
  {base:'boto',    full:'botó',    w:['bòto','boto'],       hint:"botó porta accent tancat (ó)"},
  {base:'tambe',   full:'també',   w:['tambè','tambe'],     hint:"també porta accent tancat (é)"},
  {base:'musica',  full:'música',  w:['musíca','musica'],   hint:"música porta accent tancat (ú) — és esdrúixola"},
  {base:'jardi',   full:'jardí',   w:['jàrdi','jardi'],     hint:"jardí porta accent tancat (í)"},
  {base:'balco',   full:'balcó',   w:['balcò','balco'],     hint:"balcó porta accent tancat (ó)"},
  // Cap accent escrit (paraules planes i agudes que no el necessiten)
  {base:'porta',   full:'porta',   w:['pòrta','pórta'],     hint:"porta és plana en -a: no porta accent escrit"},
  {base:'festa',   full:'festa',   w:['fèsta','fésta'],     hint:"festa és plana en -a: no porta accent"},
  {base:'arbre',   full:'arbre',   w:['àrbre','árbre'],     hint:"arbre és plana en -e: no porta accent"},
  {base:'amic',    full:'amic',    w:['àmic','ámic'],       hint:"amic és aguda en -c: no s'accentua"},
  {base:'mare',    full:'mare',    w:['màre','máre'],       hint:"mare és plana en -e: no porta accent"},
  {base:'camp',    full:'camp',    w:['càmp','cámp'],       hint:"camp és aguda en -p: no s'accentua"},
  {base:'parc',    full:'parc',    w:['pàrc','párc'],       hint:"parc és aguda en -c: no s'accentua"},
];

// _ marca la posició on la h podria anar (sempre al principi o en posició medial)
const HWORDS_POOL = [
  // Porten H inicial
  {word:'_ome',       ans:'h',     full:'home',       hint:'home (persona) sempre s\'escriu amb h'},
  {word:'_ora',       ans:'h',     full:'hora',       hint:'hora s\'escriu amb h'},
  {word:'_erba',      ans:'h',     full:'herba',      hint:'herba s\'escriu amb h'},
  {word:'_ivern',     ans:'h',     full:'hivern',     hint:'hivern (estació freda) s\'escriu amb h'},
  {word:'_ort',       ans:'h',     full:'hort',       hint:'hort (lloc de verdures) s\'escriu amb h'},
  {word:'_ospital',   ans:'h',     full:'hospital',   hint:'hospital s\'escriu amb h'},
  {word:'_otel',      ans:'h',     full:'hotel',      hint:'hotel s\'escriu amb h'},
  {word:'_umit',      ans:'h',     full:'humit',      hint:'humit (moll) s\'escriu amb h'},
  {word:'_istòria',   ans:'h',     full:'història',   hint:'història s\'escriu amb h'},
  {word:'_abitació',  ans:'h',     full:'habitació',  hint:'habitació s\'escriu amb h'},
  {word:'_eroi',      ans:'h',     full:'heroi',      hint:'heroi s\'escriu amb h'},
  {word:'_umà',       ans:'h',     full:'humà',       hint:'humà s\'escriu amb h'},
  {word:'_àmster',    ans:'h',     full:'hàmster',    hint:'hàmster s\'escriu amb h'},
  // Porten H medial (entre vocals)
  {word:'ve_icle',    ans:'h',     full:'vehicle',    hint:'vehicle porta h entre la e i la i'},
  {word:'alco_ol',    ans:'h',     full:'alcohol',    hint:'alcohol porta h entre les dues o'},
  // NO porten H (errors freqüents)
  {word:'_estiu',     ans:'cap h', full:'estiu',      hint:'estiu (estació càlida) NO porta h'},
  {word:'_ovella',    ans:'cap h', full:'ovella',     hint:'ovella (animal) NO porta h'},
  {word:'_orella',    ans:'cap h', full:'orella',     hint:'orella NO porta h'},
  {word:'_ull',       ans:'cap h', full:'ull',        hint:'ull NO porta h'},
  {word:'_abella',    ans:'cap h', full:'abella',     hint:'abella NO porta h'},
  {word:'_ou',        ans:'cap h', full:'ou',         hint:'ou NO porta h'},
  {word:'_onada',     ans:'cap h', full:'onada',      hint:'onada NO porta h'},
  {word:'_oreneta',   ans:'cap h', full:'oreneta',    hint:'oreneta (ocell) NO porta h'},
  {word:'_ase',       ans:'cap h', full:'ase',        hint:'ase (animal) NO porta h'},
  {word:'_illa',      ans:'cap h', full:'illa',       hint:'illa NO porta h'},
  // Ampliació — H inicial
  {word:'_umor',      ans:'h',     full:'humor',      hint:"humor s'escriu amb h"},
  {word:'_ereu',      ans:'h',     full:'hereu',      hint:"hereu (fill gran) s'escriu amb h"},
  {word:'_orror',     ans:'h',     full:'horror',     hint:"horror s'escriu amb h"},
  {word:'_onor',      ans:'h',     full:'honor',      hint:"honor s'escriu amb h"},
  {word:'_elicòpter', ans:'h',     full:'helicòpter', hint:"helicòpter s'escriu amb h"},
  {word:'_ipopòtam',  ans:'h',     full:'hipopòtam',  hint:"hipopòtam s'escriu amb h"},
  {word:'_umitat',    ans:'h',     full:'humitat',    hint:"humitat s'escriu amb h"},
  {word:'_ola',       ans:'h',     full:'hola',       hint:"hola s'escriu amb h"},
  {word:'_abitant',   ans:'h',     full:'habitant',   hint:"habitant s'escriu amb h"},
  // Ampliació — H medial (entre vocals)
  {word:'a_ir',       ans:'h',     full:'ahir',       hint:"ahir (el dia d'ahir) porta h medial"},
  {word:'tot_om',     ans:'h',     full:'tothom',     hint:"tothom porta h: tot + hom (= home)"},
  {word:'sub_asta',   ans:'h',     full:'subhasta',   hint:"subhasta porta h medial"},
  {word:'en_orabona', ans:'h',     full:'enhorabona', hint:"enhorabona porta h medial"},
  // Ampliació — Cap H (errors freqüents)
  {word:'_avui',      ans:'cap h', full:'avui',       hint:"avui (el dia d'avui) NO porta h"},
  {word:'co_et',      ans:'cap h', full:'coet',       hint:"coet (no 'cohet'!) NO porta h"},
  {word:'_orfe',      ans:'cap h', full:'orfe',       hint:"orfe (sense pares) NO porta h"},
  {word:'_os',        ans:'cap h', full:'os',         hint:"os (os del cos) NO porta h"},
];
const HWORDS_OPTS = ['h', 'cap h'];
