const ACTIVITIES = [
  {gerund:'rollerskating',       icon:'🛼', hint:'You put special boots on your feet and glide.'},
  {gerund:'dancing',             icon:'💃', hint:'You move your body to the rhythm of music.'},
  {gerund:'shopping',            icon:'🛒', hint:'You go to the shops and buy things.'},
  {gerund:'playing the violin',  icon:'🎻', hint:'You play a stringed musical instrument with a bow.'},
  {gerund:'painting pictures',   icon:'🎨', hint:'You use colours and a brush to make art.'},
  {gerund:'reading comics',      icon:'📖', hint:'You read illustrated stories with speech bubbles.'},
  {gerund:'collecting stickers', icon:'⭐', hint:'You keep and organise small sticky pictures.'},
  {gerund:'going to museums',    icon:'🏛️', hint:'You visit a place full of art, history or science.'},
  {gerund:'taking photos',       icon:'📷', hint:'You use a camera to capture special moments.'},
  {gerund:'using a computer',    icon:'💻', hint:'You type, browse the internet or play online games.'},
  {gerund:'playing tennis',      icon:'🎾', hint:'You hit a ball over a net using a racket.'},
  {gerund:'watching films',      icon:'🎬', hint:'You sit down and enjoy a movie.'},
  {gerund:'listening to music',  icon:'🎵', hint:'You enjoy songs through headphones or speakers.'},
  {gerund:'cooking',             icon:'🍳', hint:'You prepare and make food in the kitchen.'},
  {gerund:'playing football',     icon:'⚽', hint:'You kick a ball into the other team\'s net.'},
  {gerund:'playing basketball',   icon:'🏀', hint:'You throw a ball through a high hoop.'},
  {gerund:'cycling',              icon:'🚲', hint:'You ride a bicycle for fun or exercise.'},
  {gerund:'swimming',             icon:'🏊', hint:'You move through water using your arms and legs.'},
  {gerund:'running',              icon:'🏃', hint:'You move fast on your feet for exercise.'},
  {gerund:'going to the cinema',  icon:'🎬', hint:'You sit in a dark room and watch a film on a big screen.'},
  {gerund:'going to the library', icon:'📚', hint:'You visit a place where you can borrow books for free.'},
  {gerund:'going to the zoo',     icon:'🦁', hint:'You walk around and see animals from all over the world.'},
  {gerund:'drawing',              icon:'✏️', hint:'You use a pencil or pen to make pictures on paper.'},
  {gerund:'playing video games',  icon:'🎮', hint:'You control characters on a screen using a controller.'},
];

const ANNA = [
  {act:'dancing',            likes:true},
  {act:'rollerskating',      likes:false},
  {act:'taking photos',      likes:true},
  {act:'playing the violin', likes:false},
  {act:'cooking',            likes:true},
  {act:'shopping',           likes:false},
  {act:'going to museums',   likes:true},
  {act:'watching films',     likes:false},
  {act:'listening to music', likes:true},
  {act:'collecting stickers',likes:false},
];

const CHARS = [
  {name:'Josh', acts:{
    'playing tennis':true,'watching films':true,'cooking':true,'using a computer':true,
    'playing football':true,'playing basketball':true,'running':true,'going to the cinema':true,'playing video games':true,
    'shopping':false,'dancing':false,'painting pictures':false,'reading comics':false,'listening to music':false,
    'swimming':false,'cycling':false,'going to the library':false,'going to the zoo':false,'drawing':false,
  }},
  {name:'Lily', acts:{
    'dancing':true,'painting pictures':true,'reading comics':true,'listening to music':true,
    'swimming':true,'cycling':true,'going to the cinema':true,'going to the library':true,'going to the zoo':true,'drawing':true,
    'playing tennis':false,'shopping':false,'using a computer':false,'watching films':false,'cooking':false,
    'playing football':false,'playing basketball':false,'running':false,'playing video games':false,
  }},
  {name:'Sam', acts:{
    'playing football':true,'playing basketball':true,'swimming':true,'running':true,'going to the cinema':true,
    'going to the zoo':true,'using a computer':true,'watching films':true,'reading comics':true,'listening to music':true,
    'playing tennis':false,'cooking':false,'dancing':false,'painting pictures':false,'shopping':false,
    'cycling':false,'going to the library':false,'drawing':false,'playing video games':false,
  }},
  {name:'Emma', acts:{
    'dancing':true,'cooking':true,'painting pictures':true,'swimming':true,'cycling':true,
    'going to the cinema':true,'going to the library':true,'going to the zoo':true,'drawing':true,'listening to music':true,
    'playing tennis':false,'shopping':false,'using a computer':false,'watching films':false,'reading comics':false,
    'playing football':false,'playing basketball':false,'running':false,'playing video games':false,
  }},
];

const CHAR_ACTS = ['playing tennis','watching films','cooking','dancing','painting pictures',
                   'reading comics','shopping','using a computer','listening to music',
                   'playing football','playing basketball','swimming','running','cycling',
                   'going to the cinema','going to the library','going to the zoo','drawing','playing video games'];

const ERROR_POOL = [
  {wrong:'She <em>collecting</em> stickers.',
   correct:"She likes collecting stickers.",
   opts:["She likes collecting stickers.","She like collecting stickers.","She is collecting stickers."]},
  {wrong:'He <em>like</em> dancing.',
   correct:"He likes dancing.",
   opts:["He likes dancing.","He do like dancing.","He is like dancing."]},
  {wrong:'I <em>likes</em> reading comics.',
   correct:"I like reading comics.",
   opts:["I like reading comics.","I am like reading comics.","I do likes reading comics."]},
  {wrong:'Does he <em>likes</em> taking photos?',
   correct:"Does he like taking photos?",
   opts:["Does he like taking photos?","Do he likes taking photos?","Does he is like taking photos?"]},
  {wrong:"She <em>doesn't likes</em> cooking.",
   correct:"She doesn't like cooking.",
   opts:["She doesn't like cooking.","She don't like cooking.","She isn't like cooking."]},
  {wrong:'Do you <em>likes</em> watching films?',
   correct:"Do you like watching films?",
   opts:["Do you like watching films?","Does you like watching films?","Are you like watching films?"]},
  {wrong:"He <em>doesn't</em> dancing.",
   correct:"He doesn't like dancing.",
   opts:["He doesn't like dancing.","He doesn't to dance.","He isn't dancing."]},
  {wrong:'Does she <em>likes</em> painting pictures?',
   correct:"Does she like painting pictures?",
   opts:["Does she like painting pictures?","Do she like painting pictures?","Does she likes painting pictures?"]},
  {wrong:'They <em>likes</em> listening to music.',
   correct:"They like listening to music.",
   opts:["They like listening to music.","They does like listening to music.","They is like listening to music."]},
  {wrong:"Do she <em>like</em> dancing?",
   correct:"Does she like dancing?",
   opts:["Does she like dancing?","Does she likes dancing?","Do she likes dancing?"]},
  {wrong:"He <em>don't</em> like painting pictures.",
   correct:"He doesn't like painting pictures.",
   opts:["He doesn't like painting pictures.","He don't like painting pictures.","He isn't like painting pictures."]},
  {wrong:"Do they <em>likes</em> rollerskating?",
   correct:"Do they like rollerskating?",
   opts:["Do they like rollerskating?","Does they like rollerskating?","Do they likes rollerskating?"]},
  {wrong:"I <em>doesn't</em> like using a computer.",
   correct:"I don't like using a computer.",
   opts:["I don't like using a computer.","I doesn't like using a computer.","I am not like using a computer."]},
  {wrong:"She <em>is like</em> taking photos.",
   correct:"She likes taking photos.",
   opts:["She likes taking photos.","She like taking photos.","She is like taking photos."]},
  {wrong:"Does they <em>like</em> reading comics?",
   correct:"Do they like reading comics?",
   opts:["Do they like reading comics?","Does they like reading comics?","Do they likes reading comics?"]},
  {wrong:'We <em>likes</em> going to museums.',
   correct:"We like going to museums.",
   opts:["We like going to museums.","We does like going to museums.","We is like going to museums."]},
  {wrong:'Does she <em>likes</em> listening to music?',
   correct:"Does she like listening to music?",
   opts:["Does she like listening to music?","Do she like listening to music?","Does she likes listening to music?"]},
  {wrong:'Josh <em>like</em> playing tennis.',
   correct:"Josh likes playing tennis.",
   opts:["Josh likes playing tennis.","Josh like playing tennis.","Josh is likes playing tennis."]},
  {wrong:"He <em>don't</em> like watching films.",
   correct:"He doesn't like watching films.",
   opts:["He doesn't like watching films.","He don't like watching films.","He not like watching films."]},
  {wrong:"She <em>is like</em> listening to music.",
   correct:"She likes listening to music.",
   opts:["She likes listening to music.","She like listening to music.","She does likes listening to music."]},
  {wrong:"Do Josh <em>like</em> using a computer?",
   correct:"Does Josh like using a computer?",
   opts:["Does Josh like using a computer?","Do Josh like using a computer?","Does Josh likes using a computer?"]},
  {wrong:"Lily <em>don't</em> like shopping.",
   correct:"Lily doesn't like shopping.",
   opts:["Lily doesn't like shopping.","Lily don't like shopping.","Lily not likes shopping."]},
  {wrong:"I <em>am like</em> cooking.",
   correct:"I like cooking.",
   opts:["I like cooking.","I likes cooking.","I do likes cooking."]},
  {wrong:"Does you <em>like</em> reading comics?",
   correct:"Do you like reading comics?",
   opts:["Do you like reading comics?","Does you like reading comics?","Do you likes reading comics?"]},
  {wrong:"They <em>doesn't</em> like rollerskating.",
   correct:"They don't like rollerskating.",
   opts:["They don't like rollerskating.","They doesn't like rollerskating.","They not like rollerskating."]},
  {wrong:"She <em>like</em> painting pictures.",
   correct:"She likes painting pictures.",
   opts:["She likes painting pictures.","She like painting pictures.","She do likes painting pictures."]},
  {wrong:"Do he <em>like</em> collecting stickers?",
   correct:"Does he like collecting stickers?",
   opts:["Does he like collecting stickers?","Do he like collecting stickers?","Does he likes collecting stickers?"]},
  {wrong:"I <em>doesn't</em> like going to museums.",
   correct:"I don't like going to museums.",
   opts:["I don't like going to museums.","I doesn't like going to museums.","I not like going to museums."]},
  {wrong:"Anna <em>like</em> dancing.",
   correct:"Anna likes dancing.",
   opts:["Anna likes dancing.","Anna like dancing.","Anna do likes dancing."]},
  {wrong:"Does he <em>likes</em> shopping?",
   correct:"Does he like shopping?",
   opts:["Does he like shopping?","Does he likes shopping?","Do he like shopping?"]},
  {wrong:"She <em>don't</em> like taking photos.",
   correct:"She doesn't like taking photos.",
   opts:["She doesn't like taking photos.","She don't like taking photos.","She isn't like taking photos."]},
  {wrong:"We <em>doesn't</em> like watching films.",
   correct:"We don't like watching films.",
   opts:["We don't like watching films.","We doesn't like watching films.","We is not like watching films."]},
  {wrong:"He <em>don't</em> likes playing the violin.",
   correct:"He doesn't like playing the violin.",
   opts:["He doesn't like playing the violin.","He don't likes playing the violin.","He not like playing the violin."]},
  {wrong:"Do she <em>likes</em> using a computer?",
   correct:"Does she like using a computer?",
   opts:["Does she like using a computer?","Do she likes using a computer?","Does she is like using a computer?"]},
  {wrong:"They <em>likes</em> listening to music.",
   correct:"They like listening to music.",
   opts:["They like listening to music.","They likes listening to music.","They does like listening to music."]},
  {wrong:"She <em>doesn't likes</em> going to museums.",
   correct:"She doesn't like going to museums.",
   opts:["She doesn't like going to museums.","She don't like going to museums.","She is not like going to museums."]},
  {wrong:"I <em>likes</em> cooking.",
   correct:"I like cooking.",
   opts:["I like cooking.","I likes cooking.","I am like cooking."]},
  {wrong:"Do Anna <em>like</em> dancing?",
   correct:"Does Anna like dancing?",
   opts:["Does Anna like dancing?","Do Anna like dancing?","Does Anna likes dancing?"]},
  {wrong:"Josh <em>doesn't likes</em> watching films.",
   correct:"Josh doesn't like watching films.",
   opts:["Josh doesn't like watching films.","Josh don't like watching films.","Josh isn't like watching films."]},
  {wrong:"Lily <em>is like</em> reading comics.",
   correct:"Lily likes reading comics.",
   opts:["Lily likes reading comics.","Lily like reading comics.","Lily is likes reading comics."]},
  {wrong:"Does they <em>likes</em> taking photos?",
   correct:"Do they like taking photos?",
   opts:["Do they like taking photos?","Does they like taking photos?","Do they likes taking photos?"]},
  {wrong:"He <em>is like</em> collecting stickers.",
   correct:"He likes collecting stickers.",
   opts:["He likes collecting stickers.","He like collecting stickers.","He does like collecting stickers."]},
  {wrong:"I <em>don't likes</em> shopping.",
   correct:"I don't like shopping.",
   opts:["I don't like shopping.","I don't likes shopping.","I am not like shopping."]},
  {wrong:"She <em>like</em> using a computer.",
   correct:"She likes using a computer.",
   opts:["She likes using a computer.","She like using a computer.","She is like using a computer."]},
  {wrong:"Do he <em>likes</em> rollerskating?",
   correct:"Does he like rollerskating?",
   opts:["Does he like rollerskating?","Do he likes rollerskating?","Does he is like rollerskating?"]},
  {wrong:"We <em>doesn't like</em> painting pictures.",
   correct:"We don't like painting pictures.",
   opts:["We don't like painting pictures.","We doesn't like painting pictures.","We not like painting pictures."]},
  {wrong:"They <em>don't likes</em> playing tennis.",
   correct:"They don't like playing tennis.",
   opts:["They don't like playing tennis.","They don't likes playing tennis.","They doesn't like playing tennis."]},
  {wrong:"Anna <em>don't</em> like going to museums.",
   correct:"Anna doesn't like going to museums.",
   opts:["Anna doesn't like going to museums.","Anna don't like going to museums.","Anna isn't like going to museums."]},
  {wrong:"Does Lily <em>likes</em> painting pictures?",
   correct:"Does Lily like painting pictures?",
   opts:["Does Lily like painting pictures?","Do Lily like painting pictures?","Does Lily likes painting pictures?"]},
  {wrong:"Josh <em>like</em> cooking.",
   correct:"Josh likes cooking.",
   opts:["Josh likes cooking.","Josh like cooking.","Josh do likes cooking."]},
  {wrong:'He <em>like</em> playing football.',
   correct:"He likes playing football.",
   opts:["He likes playing football.","He like playing football.","He is playing football."]},
  {wrong:"She <em>doesn't likes</em> swimming.",
   correct:"She doesn't like swimming.",
   opts:["She doesn't like swimming.","She don't like swimming.","She isn't like swimming."]},
  {wrong:"Do she <em>like</em> cycling?",
   correct:"Does she like cycling?",
   opts:["Does she like cycling?","Do she like cycling?","Does she likes cycling?"]},
  {wrong:'They <em>likes</em> playing basketball.',
   correct:"They like playing basketball.",
   opts:["They like playing basketball.","They likes playing basketball.","They does like playing basketball."]},
  {wrong:"He <em>don't</em> like running.",
   correct:"He doesn't like running.",
   opts:["He doesn't like running.","He don't like running.","He not likes running."]},
  {wrong:"She <em>is like</em> drawing.",
   correct:"She likes drawing.",
   opts:["She likes drawing.","She like drawing.","She is like drawing."]},
  {wrong:"Does they <em>like</em> going to the cinema?",
   correct:"Do they like going to the cinema?",
   opts:["Do they like going to the cinema?","Does they like going to the cinema?","Do they likes going to the cinema?"]},
  {wrong:"I <em>doesn't</em> like going to the library.",
   correct:"I don't like going to the library.",
   opts:["I don't like going to the library.","I doesn't like going to the library.","I not like going to the library."]},
  {wrong:"Sam <em>like</em> playing video games.",
   correct:"Sam likes playing video games.",
   opts:["Sam likes playing video games.","Sam like playing video games.","Sam do likes playing video games."]},
  {wrong:"Emma <em>don't</em> like playing football.",
   correct:"Emma doesn't like playing football.",
   opts:["Emma doesn't like playing football.","Emma don't like playing football.","Emma isn't like playing football."]},
  {wrong:"Do Josh <em>likes</em> playing football?",
   correct:"Does Josh like playing football?",
   opts:["Does Josh like playing football?","Do Josh like playing football?","Does Josh likes playing football?"]},
  {wrong:"Lily <em>is like</em> cycling.",
   correct:"Lily likes cycling.",
   opts:["Lily likes cycling.","Lily like cycling.","Lily does like cycling."]},
  {wrong:"Does Sam <em>likes</em> going to the zoo?",
   correct:"Does Sam like going to the zoo?",
   opts:["Does Sam like going to the zoo?","Does Sam likes going to the zoo?","Do Sam like going to the zoo?"]},
  {wrong:"We <em>doesn't</em> like running.",
   correct:"We don't like running.",
   opts:["We don't like running.","We doesn't like running.","We is not like running."]},
  {wrong:"Do Emma <em>like</em> drawing?",
   correct:"Does Emma like drawing?",
   opts:["Does Emma like drawing?","Do Emma like drawing?","Does Emma likes drawing?"]},
  {wrong:"I <em>likes</em> going to the zoo.",
   correct:"I like going to the zoo.",
   opts:["I like going to the zoo.","I likes going to the zoo.","I am like going to the zoo."]},
];

const GRAMMAR_POOL = [
  {sent:"Does he ___ dancing?",              opts:["like","likes","liked","liking"],        correct:"like"},
  {sent:"She ___ like cooking.",             opts:["doesn't","don't","isn't","aren't"],     correct:"doesn't"},
  {sent:"I ___ rollerskating.",              opts:["like","likes","is like","am like"],     correct:"like"},
  {sent:"He ___ playing tennis.",            opts:["likes","like","is likes","do likes"],   correct:"likes"},
  {sent:"Do you ___ taking photos?",         opts:["like","likes","liked","liking"],        correct:"like"},
  {sent:"She doesn't ___ shopping.",         opts:["like","likes","liked","liking"],        correct:"like"},
  {sent:"They ___ collecting stickers.",     opts:["like","likes","is like","does like"],   correct:"like"},
  {sent:"Does she ___ painting?",            opts:["like","likes","liked","liking"],        correct:"like"},
  {sent:"We ___ watching films.",            opts:["like","likes","is like","am like"],     correct:"like"},
  {sent:"He ___ like dancing.",              opts:["doesn't","don't","isn't","aren't"],     correct:"doesn't"},
  {sent:"I don't ___ reading comics.",       opts:["like","likes","liked","liking"],        correct:"like"},
  {sent:"She ___ taking photos.",            opts:["likes","like","is likes","do likes"],   correct:"likes"},
  {sent:"Does Lily ___ using a computer?",   opts:["like","likes","liked","liking"],        correct:"like"},
  {sent:"Josh ___ like shopping.",           opts:["doesn't","don't","isn't","aren't"],     correct:"doesn't"},
  {sent:"___ you like dancing?",             opts:["Do","Does","Are","Is"],                 correct:"Do"},
  {sent:"He ___ like cooking.",              opts:["doesn't","don't","isn't","aren't"],     correct:"doesn't"},
  {sent:"They don't ___ watching films.",    opts:["like","likes","liked","liking"],        correct:"like"},
  {sent:"___ she like collecting stickers?", opts:["Does","Do","Is","Are"],                 correct:"Does"},
  {sent:"We ___ playing tennis.",            opts:["like","likes","is like","am like"],     correct:"like"},
  {sent:"She ___ like rollerskating.",       opts:["doesn't","don't","isn't","aren't"],     correct:"doesn't"},
  {sent:"Does he ___ reading comics?",       opts:["like","likes","liked","liking"],        correct:"like"},
  {sent:"Anna ___ going to museums.",        opts:["likes","like","is likes","do like"],    correct:"likes"},
  {sent:"He ___ cooking.",                   opts:["likes","like","is likes","do likes"],   correct:"likes"},
  {sent:"I don't ___ shopping.",             opts:["like","likes","liked","liking"],        correct:"like"},
  {sent:"___ you like dancing?",             opts:["Do","Does","Are","Is"],                 correct:"Do"},
  {sent:"Anna ___ going to museums.",        opts:["likes","like","is likes","do like"],    correct:"likes"},
  {sent:"They ___ like painting pictures.",  opts:["don't","doesn't","aren't","isn't"],     correct:"don't"},
  {sent:"We don't ___ using a computer.",    opts:["like","likes","liked","liking"],        correct:"like"},
  {sent:"___ Josh like watching films?",     opts:["Does","Do","Is","Are"],                 correct:"Does"},
  {sent:"She ___ reading comics.",           opts:["likes","like","is likes","do likes"],   correct:"likes"},
  {sent:"He ___ like collecting stickers.",  opts:["doesn't","don't","isn't","aren't"],     correct:"doesn't"},
  {sent:"___ they like rollerskating?",      opts:["Do","Does","Are","Is"],                 correct:"Do"},
  {sent:"I ___ taking photos.",              opts:["like","likes","is like","am like"],     correct:"like"},
  {sent:"Josh ___ like dancing.",            opts:["doesn't","don't","isn't","aren't"],     correct:"doesn't"},
  {sent:"___ Anna like going to museums?",   opts:["Does","Do","Is","Are"],                 correct:"Does"},
  {sent:"They don't ___ cooking.",           opts:["like","likes","liked","liking"],        correct:"like"},
  {sent:"She ___ like using a computer.",    opts:["doesn't","don't","isn't","aren't"],     correct:"doesn't"},
  {sent:"We ___ listening to music.",        opts:["like","likes","is like","am like"],     correct:"like"},
  {sent:"___ Lily like painting pictures?",  opts:["Does","Do","Is","Are"],                 correct:"Does"},
  {sent:"He ___ rollerskating.",             opts:["likes","like","is likes","do likes"],   correct:"likes"},
  {sent:"You don't ___ shopping.",           opts:["like","likes","liked","liking"],        correct:"like"},
  {sent:"Anna ___ like rollerskating.",      opts:["doesn't","don't","isn't","aren't"],     correct:"doesn't"},
  {sent:"___ he like painting pictures?",    opts:["Does","Do","Is","Are"],                 correct:"Does"},
  {sent:"I ___ like going to museums.",      opts:["don't","doesn't","aren't","isn't"],     correct:"don't"},
  {sent:"She ___ dancing.",                  opts:["likes","like","is likes","do likes"],   correct:"likes"},
  {sent:"We ___ like playing the violin.",   opts:["don't","doesn't","aren't","isn't"],     correct:"don't"},
  {sent:"___ we like watching films?",       opts:["Do","Does","Are","Is"],                 correct:"Do"},
  {sent:"He ___ playing tennis.",            opts:["likes","like","is likes","do likes"],   correct:"likes"},
  {sent:"She ___ like taking photos.",       opts:["doesn't","don't","isn't","aren't"],     correct:"doesn't"},
  {sent:"___ you like cooking?",             opts:["Do","Does","Are","Is"],                 correct:"Do"},
  {sent:"He ___ playing football.",          opts:["likes","like","is likes","do likes"],   correct:"likes"},
  {sent:"She doesn't ___ swimming.",         opts:["like","likes","liked","liking"],        correct:"like"},
  {sent:"___ she like cycling?",             opts:["Does","Do","Is","Are"],                 correct:"Does"},
  {sent:"They ___ playing basketball.",      opts:["like","likes","is like","does like"],   correct:"like"},
  {sent:"He ___ like running.",              opts:["doesn't","don't","isn't","aren't"],     correct:"doesn't"},
  {sent:"I ___ drawing.",                    opts:["like","likes","is like","am like"],     correct:"like"},
  {sent:"___ they like going to the cinema?",opts:["Do","Does","Are","Is"],                correct:"Do"},
  {sent:"She ___ going to the library.",     opts:["likes","like","is likes","do likes"],   correct:"likes"},
  {sent:"Sam ___ playing video games.",      opts:["likes","like","is likes","do likes"],   correct:"likes"},
  {sent:"Emma ___ like playing football.",   opts:["doesn't","don't","isn't","aren't"],     correct:"doesn't"},
  {sent:"___ you like drawing?",             opts:["Do","Does","Are","Is"],                 correct:"Do"},
  {sent:"He ___ like swimming.",             opts:["doesn't","don't","isn't","aren't"],     correct:"doesn't"},
  {sent:"She ___ going to the zoo.",         opts:["likes","like","is likes","do likes"],   correct:"likes"},
  {sent:"___ Sam like cycling?",             opts:["Does","Do","Is","Are"],                 correct:"Does"},
  {sent:"We ___ playing football.",          opts:["like","likes","is like","am like"],     correct:"like"},
  {sent:"Emma ___ like running.",            opts:["doesn't","don't","isn't","aren't"],     correct:"doesn't"},
  {sent:"___ Josh like playing basketball?", opts:["Does","Do","Is","Are"],                 correct:"Does"},
  {sent:"I ___ like going to the cinema.",   opts:["don't","doesn't","aren't","isn't"],     correct:"don't"},
];
