const ACTIVITIES = [
  {gerund:'rollerskating',       icon:'🛼', hint:'You put special boots on your feet and glide.'},
  {gerund:'dancing',             icon:'💃', hint:'You move your body to the rhythm of music.'},
  {gerund:'shopping',            icon:'🛒', hint:'You go to the shops and buy things.'},
  {gerund:'playing the violin',  icon:'🎻', hint:'You play a stringed musical instrument with a bow.'},
  {gerund:'painting pictures',   icon:'🎨', hint:'You use colours and a brush to make art.'},
  {gerund:'reading comics',      icon:'📖', hint:'You read illustrated stories with speech bubbles.'},
  {gerund:'collecting stickers', icon:'⭐', hint:'You keep and organise small sticky pictures.'},
  {gerund:'going to museums',    icon:'🏛️', hint:'You visit a place full of art, history or science.'},
  {gerund:'taking photos',       icon:'📷', hint:'You use a camera to capture special moments.'},
  {gerund:'using a computer',    icon:'💻', hint:'You type, browse the internet or play online games.'},
  {gerund:'playing tennis',      icon:'🎾', hint:'You hit a ball over a net using a racket.'},
  {gerund:'watching films',      icon:'🎬', hint:'You sit down and enjoy a movie.'},
  {gerund:'listening to music',  icon:'🎵', hint:'You enjoy songs through headphones or speakers.'},
  {gerund:'cooking',             icon:'🍳', hint:'You prepare and make food in the kitchen.'},
];

const ANNA = [
  {act:'dancing',            likes:true},
  {act:'rollerskating',      likes:false},
  {act:'taking photos',      likes:true},
  {act:'playing the violin', likes:false},
  {act:'cooking',            likes:true},
  {act:'shopping',           likes:false},
  {act:'going to museums',   likes:true},
  {act:'watching films',     likes:false},
  {act:'listening to music', likes:true},
  {act:'collecting stickers',likes:false},
];

const CHARS = [
  {name:'Josh', acts:{
    'playing tennis':true,'watching films':true,'cooking':true,'using a computer':true,
    'shopping':false,'dancing':false,'painting pictures':false,
    'reading comics':false,'listening to music':false,
  }},
  {name:'Lily', acts:{
    'dancing':true,'painting pictures':true,'reading comics':true,
    'listening to music':true,'going to museums':true,
    'playing tennis':false,'shopping':false,'using a computer':false,
    'watching films':false,'cooking':false,
  }},
];

const CHAR_ACTS = ['playing tennis','watching films','cooking','dancing','painting pictures',
                   'reading comics','shopping','using a computer','listening to music'];

const ERROR_POOL = [
  {wrong:'She <em>collecting</em> stickers.',
   correct:"She likes collecting stickers.",
   opts:["She likes collecting stickers.","She like collecting stickers.","She is collecting stickers."]},
  {wrong:'He <em>like</em> dancing.',
   correct:"He likes dancing.",
   opts:["He likes dancing.","He do like dancing.","He is like dancing."]},
  {wrong:'I <em>likes</em> reading comics.',
   correct:"I like reading comics.",
   opts:["I like reading comics.","I am like reading comics.","I do likes reading comics."]},
  {wrong:'Does he <em>likes</em> taking photos?',
   correct:"Does he like taking photos?",
   opts:["Does he like taking photos?","Do he likes taking photos?","Does he is like taking photos?"]},
  {wrong:"She <em>doesn't likes</em> cooking.",
   correct:"She doesn't like cooking.",
   opts:["She doesn't like cooking.","She don't like cooking.","She isn't like cooking."]},
  {wrong:'Do you <em>likes</em> watching films?',
   correct:"Do you like watching films?",
   opts:["Do you like watching films?","Does you like watching films?","Are you like watching films?"]},
  {wrong:"He <em>doesn't</em> dancing.",
   correct:"He doesn't like dancing.",
   opts:["He doesn't like dancing.","He doesn't to dance.","He isn't dancing."]},
  {wrong:'Does she <em>likes</em> painting pictures?',
   correct:"Does she like painting pictures?",
   opts:["Does she like painting pictures?","Do she like painting pictures?","Does she likes painting pictures?"]},
  {wrong:'They <em>likes</em> listening to music.',
   correct:"They like listening to music.",
   opts:["They like listening to music.","They does like listening to music.","They is like listening to music."]},
  {wrong:"Do she <em>like</em> dancing?",
   correct:"Does she like dancing?",
   opts:["Does she like dancing?","Does she likes dancing?","Do she likes dancing?"]},
  {wrong:"He <em>don't</em> like painting pictures.",
   correct:"He doesn't like painting pictures.",
   opts:["He doesn't like painting pictures.","He don't like painting pictures.","He isn't like painting pictures."]},
  {wrong:"Do they <em>likes</em> rollerskating?",
   correct:"Do they like rollerskating?",
   opts:["Do they like rollerskating?","Does they like rollerskating?","Do they likes rollerskating?"]},
  {wrong:"I <em>doesn't</em> like using a computer.",
   correct:"I don't like using a computer.",
   opts:["I don't like using a computer.","I doesn't like using a computer.","I am not like using a computer."]},
  {wrong:"She <em>is like</em> taking photos.",
   correct:"She likes taking photos.",
   opts:["She likes taking photos.","She like taking photos.","She is like taking photos."]},
  {wrong:"Does they <em>like</em> reading comics?",
   correct:"Do they like reading comics?",
   opts:["Do they like reading comics?","Does they like reading comics?","Do they likes reading comics?"]},
];

const GRAMMAR_POOL = [
  {sent:"Does he ___ dancing?",          opts:["like","likes","liked","liking"],       correct:"like"},
  {sent:"She ___ like cooking.",          opts:["doesn't","don't","isn't","aren't"],    correct:"doesn't"},
  {sent:"I ___ rollerskating.",           opts:["like","likes","is like","am like"],    correct:"like"},
  {sent:"He ___ playing tennis.",         opts:["likes","like","is likes","do likes"],  correct:"likes"},
  {sent:"Do you ___ taking photos?",      opts:["like","likes","liked","liking"],       correct:"like"},
  {sent:"She doesn't ___ shopping.",      opts:["like","likes","liked","liking"],       correct:"like"},
  {sent:"They ___ collecting stickers.",  opts:["like","likes","is like","does like"],  correct:"like"},
  {sent:"Does she ___ painting?",         opts:["like","likes","liked","liking"],       correct:"like"},
  {sent:"We ___ watching films.",         opts:["like","likes","is like","am like"],    correct:"like"},
  {sent:"He ___ like dancing.",           opts:["doesn't","don't","isn't","aren't"],    correct:"doesn't"},
  {sent:"I don't ___ reading comics.",    opts:["like","likes","liked","liking"],       correct:"like"},
  {sent:"She ___ taking photos.",         opts:["likes","like","is likes","do likes"],  correct:"likes"},
  {sent:"Does Lily ___ using a computer?",opts:["like","likes","liked","liking"],       correct:"like"},
  {sent:"Josh ___ like shopping.",        opts:["doesn't","don't","isn't","aren't"],    correct:"doesn't"},
  {sent:"___ you like dancing?",          opts:["Do","Does","Are","Is"],                correct:"Do"},
  {sent:"He ___ like cooking.",           opts:["doesn't","don't","isn't","aren't"],    correct:"doesn't"},
  {sent:"They don't ___ watching films.", opts:["like","likes","liked","liking"],       correct:"like"},
  {sent:"___ she like collecting stickers?", opts:["Does","Do","Is","Are"],            correct:"Does"},
  {sent:"We ___ playing tennis.",         opts:["like","likes","is like","am like"],    correct:"like"},
  {sent:"She ___ like rollerskating.",    opts:["doesn't","don't","isn't","aren't"],    correct:"doesn't"},
  {sent:"Does he ___ reading comics?",    opts:["like","likes","liked","liking"],       correct:"like"},
  {sent:"Anna ___ going to museums.",     opts:["likes","like","is likes","do like"],   correct:"likes"},
];
