const VOCAB_POOL = [
  // Hair texture / length / colour
  {display:'f_ir',      correct:'a', hint:'light coloured hair',                    emoji:'🟡', opts:['a','e','i','u']},
  {display:'d_rk',      correct:'a', hint:'black or brown hair or skin',            emoji:'🟤', opts:['a','e','i','o']},
  {display:'sh_rt',     correct:'o', hint:'not long — e.g. a boy\'s cut',          emoji:'✂️', opts:['a','e','o','u']},
  {display:'l_ng',      correct:'o', hint:'not short — reaches the back',          emoji:'↕️', opts:['a','e','i','o']},
  {display:'c_rly',     correct:'u', hint:'hair with tight spirals',                emoji:'🌀', opts:['a','e','i','u']},
  {display:'str_ight',  correct:'a', hint:'hair with no curls or waves',           emoji:'➡️', opts:['a','e','i','o']},
  {display:'w_vy',      correct:'a', hint:'between curly and straight',            emoji:'〰️', opts:['a','e','i','u']},
  {display:'bl_nde',    correct:'o', hint:'very light hair — another word for fair',emoji:'👱', opts:['a','e','i','o']},
  {display:'br_wn',     correct:'o', hint:'a common hair or eye colour',           emoji:'🟫', opts:['a','e','i','o']},
  {display:'r_dhead',   correct:'e', hint:'someone with orange or red hair',        emoji:'🦰', opts:['a','e','i','o']},
  {display:'br_nette',  correct:'u', hint:'a person with dark brown hair',          emoji:'👩‍🦱', opts:['a','e','i','u']},
  {display:'fr_nge',    correct:'i', hint:'hair that falls over the forehead',      emoji:'💇', opts:['a','e','i','u']},
  {display:'pl_its',    correct:'a', hint:'hair braided into long ropes',          emoji:'🎀', opts:['a','e','i','o']},
  {display:'b_ld',      correct:'a', hint:'no hair on the head at all',            emoji:'👨‍🦲', opts:['a','e','i','o']},
  // Eye colour
  {display:'bl_e',      correct:'u', hint:'a common eye colour like the sky',      emoji:'💙', opts:['a','e','i','u']},
  {display:'gr_en',     correct:'e', hint:'a common eye colour like grass',        emoji:'💚', opts:['a','e','i','o']},
  // Face features
  {display:'gl_sses',   correct:'a', hint:'you wear them on your nose to see well',emoji:'👓', opts:['a','e','i','o']},
  {display:'b_ard',     correct:'e', hint:'hair on a man\'s face/chin',            emoji:'🧔', opts:['a','e','i','o']},
  {display:'p_nytail',  correct:'o', hint:'long hair tied at the back',            emoji:'🎀', opts:['a','e','i','o']},
  {display:'m_ustache', correct:'o', hint:'hair above the upper lip',              emoji:'👨', opts:['a','e','i','o']},
  {display:'fr_ckles',  correct:'e', hint:'small brown spots on the face',         emoji:'😊', opts:['a','e','i','u']},
  // Height
  {display:'t_ll',      correct:'a', hint:'height — the opposite of short',        emoji:'📏', opts:['a','e','i','u']},
  // Build / body
  {display:'sl_m',      correct:'i', hint:'thin and in good shape',                emoji:'🏃', opts:['a','e','i','u']},
  {display:'th_n',      correct:'i', hint:'not fat — very slim',                   emoji:'🌿', opts:['a','e','i','u']},
  {display:'sk_nny',    correct:'i', hint:'very, very thin',                       emoji:'🦴', opts:['a','e','i','u']},
  {display:'f_t',       correct:'a', hint:'the opposite of slim',                  emoji:'🍔', opts:['a','e','i','u']},
  {display:'ch_bby',    correct:'u', hint:'a little round and plump',              emoji:'🐷', opts:['a','e','i','u']},
  {display:'m_scular',  correct:'u', hint:'with big, strong muscles',              emoji:'💪', opts:['a','e','i','u']},
  {display:'st_cky',    correct:'o', hint:'short and broad and strong',            emoji:'🪨', opts:['a','e','i','o']},
  // Complexion
  {display:'p_le',      correct:'a', hint:'very light skin with little colour',    emoji:'👻', opts:['a','e','i','u']},
  {display:'t_nned',    correct:'a', hint:'skin darkened by the sun',              emoji:'☀️', opts:['a','e','i','u']},
  // General look
  {display:'pr_tty',    correct:'e', hint:'nice-looking — usually used for girls', emoji:'😍', opts:['a','e','i','u']},
  {display:'_gly',      correct:'u', hint:'the opposite of beautiful',             emoji:'😬', opts:['a','e','i','u']},
  {display:'h_ndsome',  correct:'a', hint:'good-looking — usually used for boys',  emoji:'😎', opts:['a','e','i','o']},
  {display:'p_tite',    correct:'e', hint:'small and delicate in build',           emoji:'🌸', opts:['a','e','i','u']},
  // Age
  {display:'_ld',       correct:'o', hint:'the opposite of young — many years',   emoji:'👴', opts:['a','e','i','o']},
  {display:'y_ung',     correct:'o', hint:'not old — few years of age',           emoji:'👶', opts:['a','e','i','o']},
  // Senses / abilities
  {display:'bl_nd',     correct:'i', hint:'cannot see — needs a guide dog',       emoji:'🦯', opts:['a','e','i','o']},
  {display:'de_f',      correct:'a', hint:'cannot hear any sounds',               emoji:'🤟', opts:['a','e','i','u']},
  {display:'m_te',      correct:'u', hint:'cannot speak at all',                  emoji:'🤐', opts:['a','e','i','u']},
];

const AVATARS = [
  {id:0, name:'Alex',  pronoun:'he',  emoji:'👦',
   traits:{hair:'short', color:'dark', type:'straight', glasses:false, beard:false, moustache:false, ponytail:false}},
  {id:1, name:'Sara',  pronoun:'she', emoji:'👧',
   traits:{hair:'long',  color:'fair', type:'curly',    glasses:false, beard:false, moustache:false, ponytail:true}},
  {id:2, name:'Tom',   pronoun:'he',  emoji:'👨',
   traits:{hair:'short', color:'fair', type:'wavy',     glasses:true,  beard:false, moustache:true,  ponytail:false}},
  {id:3, name:'Laura', pronoun:'she', emoji:'👩',
   traits:{hair:'long',  color:'dark', type:'straight', glasses:true,  beard:false, moustache:false, ponytail:false}},
  {id:4, name:'Ben',   pronoun:'he',  emoji:'🧔',
   traits:{hair:'short', color:'dark', type:'curly',    glasses:false, beard:true,  moustache:false, ponytail:false}},
  {id:5, name:'Mia',   pronoun:'she', emoji:'👱‍♀️',
   traits:{hair:'long',  color:'fair', type:'wavy',     glasses:true,  beard:false, moustache:false, ponytail:true}},
];

const S4_POOL = [
  {words:["She","has","got","long","fair","curly","hair."],            correct:"She has got long fair curly hair."},
  {words:["Has","he","got","glasses?"],                                correct:"Has he got glasses?"},
  {words:["He","hasn't","got","a","beard."],                           correct:"He hasn't got a beard."},
  {words:["Has","she","got","a","ponytail?"],                          correct:"Has she got a ponytail?"},
  {words:["She","hasn't","got","straight","hair."],                    correct:"She hasn't got straight hair."},
  {words:["Has","he","got","dark","curly","hair?"],                    correct:"Has he got dark curly hair?"},
  {words:["He","has","got","short","wavy","fair","hair."],             correct:"He has got short wavy fair hair."},
  {words:["She","has","got","a","ponytail","and","glasses."],          correct:"She has got a ponytail and glasses."},
  {words:["Has","he","got","a","moustache?"],                          correct:"Has he got a moustache?"},
  {words:["He","hasn't","got","long","dark","hair."],                  correct:"He hasn't got long dark hair."},
  {words:["He","has","got","short","dark","straight","hair."],         correct:"He has got short dark straight hair."},
  {words:["He","hasn't","got","glasses."],                             correct:"He hasn't got glasses."},
  {words:["He","hasn't","got","curly","hair."],                        correct:"He hasn't got curly hair."},
  {words:["Has","he","got","short","dark","hair?"],                    correct:"Has he got short dark hair?"},
  {words:["She","has","got","a","ponytail."],                          correct:"She has got a ponytail."},
  {words:["She","hasn't","got","glasses."],                            correct:"She hasn't got glasses."},
  {words:["Has","she","got","long","fair","hair?"],                    correct:"Has she got long fair hair?"},
  {words:["She","hasn't","got","dark","hair."],                        correct:"She hasn't got dark hair."},
  {words:["He","has","got","a","moustache","and","glasses."],          correct:"He has got a moustache and glasses."},
  {words:["He","hasn't","got","curly","hair."],                        correct:"He hasn't got curly hair."},
  {words:["Has","he","got","a","moustache?"],                          correct:"Has he got a moustache?"},
  {words:["He","has","got","short","fair","wavy","hair."],             correct:"He has got short fair wavy hair."},
  {words:["Has","he","got","glasses?"],                                correct:"Has he got glasses?"},
  {words:["She","has","got","long","dark","straight","hair."],         correct:"She has got long dark straight hair."},
  {words:["She","has","got","glasses."],                               correct:"She has got glasses."},
  {words:["She","hasn't","got","a","ponytail."],                       correct:"She hasn't got a ponytail."},
  {words:["Has","she","got","straight","hair?"],                       correct:"Has she got straight hair?"},
  {words:["She","hasn't","got","fair","hair."],                        correct:"She hasn't got fair hair."},
  {words:["Has","she","got","glasses?"],                               correct:"Has she got glasses?"},
  {words:["He","has","got","a","beard."],                              correct:"He has got a beard."},
  {words:["Has","he","got","a","beard?"],                              correct:"Has he got a beard?"},
  {words:["He","hasn't","got","long","hair."],                         correct:"He hasn't got long hair."},
  {words:["He","has","got","short","dark","curly","hair."],            correct:"He has got short dark curly hair."},
  {words:["He","hasn't","got","a","moustache."],                       correct:"He hasn't got a moustache."},
  {words:["She","has","got","long","fair","wavy","hair."],             correct:"She has got long fair wavy hair."},
  {words:["She","has","got","glasses","and","a","ponytail."],          correct:"She has got glasses and a ponytail."},
  {words:["Has","she","got","wavy","hair?"],                           correct:"Has she got wavy hair?"},
  {words:["She","hasn't","got","dark","hair."],                        correct:"She hasn't got dark hair."},
  {words:["Has","she","got","a","ponytail","and","glasses?"],          correct:"Has she got a ponytail and glasses?"},
  {words:["He","has","got","fair","wavy","hair","and","glasses."],     correct:"He has got fair wavy hair and glasses."},
  {words:["She","hasn't","got","a","beard","or","a","moustache."],     correct:"She hasn't got a beard or a moustache."},
  {words:["Has","he","got","dark","straight","hair?"],                 correct:"Has he got dark straight hair?"},
  {words:["She","has","got","long","curly","hair","and","a","ponytail."], correct:"She has got long curly hair and a ponytail."},
  {words:["He","hasn't","got","wavy","hair."],                         correct:"He hasn't got wavy hair."},
  {words:["Has","she","got","long","dark","straight","hair?"],         correct:"Has she got long dark straight hair?"},
  {words:["He","has","got","glasses","and","a","moustache."],          correct:"He has got glasses and a moustache."},
  {words:["She","hasn't","got","short","hair."],                       correct:"She hasn't got short hair."},
  {words:["Has","he","got","a","beard","and","glasses?"],              correct:"Has he got a beard and glasses?"},
  {words:["He","hasn't","got","fair","hair."],                         correct:"He hasn't got fair hair."},
  {words:["Has","she","got","curly","fair","hair?"],                   correct:"Has she got curly fair hair?"},
];
