const CLOCK_POOL = [
  // o'clock
  {h:1,  m:0,  expr:"It's one o'clock"},
  {h:2,  m:0,  expr:"It's two o'clock"},
  {h:3,  m:0,  expr:"It's three o'clock"},
  {h:4,  m:0,  expr:"It's four o'clock"},
  {h:5,  m:0,  expr:"It's five o'clock"},
  {h:6,  m:0,  expr:"It's six o'clock"},
  {h:7,  m:0,  expr:"It's seven o'clock"},
  {h:8,  m:0,  expr:"It's eight o'clock"},
  {h:9,  m:0,  expr:"It's nine o'clock"},
  {h:10, m:0,  expr:"It's ten o'clock"},
  {h:11, m:0,  expr:"It's eleven o'clock"},
  {h:12, m:0,  expr:"It's twelve o'clock"},
  // quarter past
  {h:1,  m:15, expr:"It's quarter past one"},
  {h:2,  m:15, expr:"It's quarter past two"},
  {h:3,  m:15, expr:"It's quarter past three"},
  {h:4,  m:15, expr:"It's quarter past four"},
  {h:5,  m:15, expr:"It's quarter past five"},
  {h:6,  m:15, expr:"It's quarter past six"},
  {h:7,  m:15, expr:"It's quarter past seven"},
  {h:8,  m:15, expr:"It's quarter past eight"},
  {h:9,  m:15, expr:"It's quarter past nine"},
  {h:10, m:15, expr:"It's quarter past ten"},
  {h:11, m:15, expr:"It's quarter past eleven"},
  {h:12, m:15, expr:"It's quarter past twelve"},
  // half past
  {h:1,  m:30, expr:"It's half past one"},
  {h:2,  m:30, expr:"It's half past two"},
  {h:3,  m:30, expr:"It's half past three"},
  {h:4,  m:30, expr:"It's half past four"},
  {h:5,  m:30, expr:"It's half past five"},
  {h:6,  m:30, expr:"It's half past six"},
  {h:7,  m:30, expr:"It's half past seven"},
  {h:8,  m:30, expr:"It's half past eight"},
  {h:9,  m:30, expr:"It's half past nine"},
  {h:10, m:30, expr:"It's half past ten"},
  {h:11, m:30, expr:"It's half past eleven"},
  {h:12, m:30, expr:"It's half past twelve"},
  // quarter to
  {h:1,  m:45, expr:"It's quarter to two"},
  {h:2,  m:45, expr:"It's quarter to three"},
  {h:3,  m:45, expr:"It's quarter to four"},
  {h:4,  m:45, expr:"It's quarter to five"},
  {h:5,  m:45, expr:"It's quarter to six"},
  {h:6,  m:45, expr:"It's quarter to seven"},
  {h:7,  m:45, expr:"It's quarter to eight"},
  {h:8,  m:45, expr:"It's quarter to nine"},
  {h:9,  m:45, expr:"It's quarter to ten"},
  {h:10, m:45, expr:"It's quarter to eleven"},
  {h:11, m:45, expr:"It's quarter to twelve"},
  {h:12, m:45, expr:"It's quarter to one"},
  // five past / twenty past extras
  {h:1,  m:5,  expr:"It's five past one"},
  {h:3,  m:20, expr:"It's twenty past three"},
];

const EXPR_POOL = [
  {expr:"It's one o'clock",        dig:"1:00"},
  {expr:"It's two o'clock",        dig:"2:00"},
  {expr:"It's three o'clock",      dig:"3:00"},
  {expr:"It's four o'clock",       dig:"4:00"},
  {expr:"It's five o'clock",       dig:"5:00"},
  {expr:"It's six o'clock",        dig:"6:00"},
  {expr:"It's seven o'clock",      dig:"7:00"},
  {expr:"It's eight o'clock",      dig:"8:00"},
  {expr:"It's nine o'clock",       dig:"9:00"},
  {expr:"It's ten o'clock",        dig:"10:00"},
  {expr:"It's eleven o'clock",     dig:"11:00"},
  {expr:"It's twelve o'clock",     dig:"12:00"},
  {expr:"It's quarter past one",   dig:"1:15"},
  {expr:"It's quarter past two",   dig:"2:15"},
  {expr:"It's quarter past three", dig:"3:15"},
  {expr:"It's quarter past five",  dig:"5:15"},
  {expr:"It's quarter past six",   dig:"6:15"},
  {expr:"It's quarter past nine",  dig:"9:15"},
  {expr:"It's quarter past ten",   dig:"10:15"},
  {expr:"It's quarter past eleven",dig:"11:15"},
  {expr:"It's quarter past twelve",dig:"12:15"},
  {expr:"It's half past one",      dig:"1:30"},
  {expr:"It's half past two",      dig:"2:30"},
  {expr:"It's half past three",    dig:"3:30"},
  {expr:"It's half past four",     dig:"4:30"},
  {expr:"It's half past five",     dig:"5:30"},
  {expr:"It's half past six",      dig:"6:30"},
  {expr:"It's half past seven",    dig:"7:30"},
  {expr:"It's half past nine",     dig:"9:30"},
  {expr:"It's half past ten",      dig:"10:30"},
  {expr:"It's half past eleven",   dig:"11:30"},
  {expr:"It's half past twelve",   dig:"12:30"},
  {expr:"It's quarter to two",     dig:"1:45"},
  {expr:"It's quarter to three",   dig:"2:45"},
  {expr:"It's quarter to four",    dig:"3:45"},
  {expr:"It's quarter to five",    dig:"4:45"},
  {expr:"It's quarter to six",     dig:"5:45"},
  {expr:"It's quarter to seven",   dig:"6:45"},
  {expr:"It's quarter to eight",   dig:"7:45"},
  {expr:"It's quarter to nine",    dig:"8:45"},
  {expr:"It's quarter to ten",     dig:"9:45"},
  {expr:"It's quarter to eleven",  dig:"10:45"},
  {expr:"It's quarter to twelve",  dig:"11:45"},
  {expr:"It's quarter to one",     dig:"12:45"},
  {expr:"It's five past one",      dig:"1:05"},
  {expr:"It's twenty past three",  dig:"3:20"},
  {expr:"It's quarter past four",  dig:"4:15"},
  {expr:"It's quarter past seven", dig:"7:15"},
  {expr:"It's quarter past eight", dig:"8:15"},
  {expr:"It's half past eight",    dig:"8:30"},
];

/* Timetable A — used by sections 1–4 */
const MTT = {
  days: ['Monday','Tuesday','Wednesday'],
  times: ['9:00','10:00','11:00'],
  grid: [
    ['Maths','English','Science'],
    ['History','Art','Maths'],
    ['PE','Science','Music'],
  ],
};

const ALL_SUBJ = ['Maths','English','Science','History','Art','PE','Music','Geography','Drama','ICT'];

/* Timetable B — used by sections 5–7 */
const S5 = {
  days: ['Monday','Tuesday','Wednesday'],
  times: ['9:00','10:00','11:00'],
  grid: [
    ['English','Maths','History'],
    ['Science','PE','Drama'],
    ['Art', null, null],
  ],
};

/*
  MTT grid (for S6/S7 reference):
  Mon 9:00=Maths   Tue 9:00=English   Wed 9:00=Science
  Mon 10:00=History  Tue 10:00=Art    Wed 10:00=Maths
  Mon 11:00=PE     Tue 11:00=Science  Wed 11:00=Music
*/

const S6_POOL = [
  {words:["Have","we","got","English","on","Monday?"],          correct:"Have we got English on Monday?"},
  {words:["I've","got","Maths","at","nine","o'clock."],         correct:"I've got Maths at nine o'clock."},
  {words:["We","haven't","got","PE","on","Tuesday."],           correct:"We haven't got PE on Tuesday."},
  {words:["Have","we","got","Art","on","Wednesday?"],           correct:"Have we got Art on Wednesday?"},
  {words:["She's","got","Science","on","Wednesday."],           correct:"She's got Science on Wednesday."},
  {words:["We","haven't","got","Drama","on","Monday."],         correct:"We haven't got Drama on Monday."},
  {words:["I've","got","History","at","ten","o'clock."],        correct:"I've got History at ten o'clock."},
  {words:["Have","we","got","Music","on","Wednesday?"],         correct:"Have we got Music on Wednesday?"},
  {words:["He","hasn't","got","Art","on","Thursday."],          correct:"He hasn't got Art on Thursday."},
  {words:["She","hasn't","got","ICT","on","Friday."],           correct:"She hasn't got ICT on Friday."},
  {words:["Have","you","got","PE","at","eleven","o'clock?"],    correct:"Have you got PE at eleven o'clock?"},
  {words:["I've","got","Geography","on","Thursday."],           correct:"I've got Geography on Thursday."},
  {words:["We","haven't","got","Drama","on","Wednesday."],      correct:"We haven't got Drama on Wednesday."},
  {words:["I","haven't","got","Maths","on","Friday."],          correct:"I haven't got Maths on Friday."},
  {words:["Have","we","got","History","on","Wednesday?"],       correct:"Have we got History on Wednesday?"},
  {words:["I've","got","Science","at","ten","o'clock."],        correct:"I've got Science at ten o'clock."},
  {words:["She","hasn't","got","PE","on","Monday."],            correct:"She hasn't got PE on Monday."},
  {words:["Have","we","got","Maths","at","nine","o'clock?"],    correct:"Have we got Maths at nine o'clock?"},
  {words:["He's","got","English","on","Tuesday."],              correct:"He's got English on Tuesday."},
  {words:["We","haven't","got","Science","on","Monday."],       correct:"We haven't got Science on Monday."},
  {words:["Have","you","got","Music","on","Wednesday?"],        correct:"Have you got Music on Wednesday?"},
  {words:["I've","got","Art","at","eleven","o'clock."],         correct:"I've got Art at eleven o'clock."},
  {words:["She","hasn't","got","Maths","on","Wednesday."],      correct:"She hasn't got Maths on Wednesday."},
  {words:["Have","we","got","Drama","on","Tuesday?"],           correct:"Have we got Drama on Tuesday?"},
  {words:["I","haven't","got","Science","on","Wednesday."],     correct:"I haven't got Science on Wednesday."},
  {words:["He's","got","PE","on","Monday","at","eleven."],      correct:"He's got PE on Monday at eleven."},
  {words:["Have","you","got","History","at","ten","o'clock?"],  correct:"Have you got History at ten o'clock?"},
  {words:["We've","got","Music","on","Wednesday","at","eleven","o'clock."], correct:"We've got Music on Wednesday at eleven o'clock."},
  {words:["She","hasn't","got","English","on","Wednesday."],    correct:"She hasn't got English on Wednesday."},
  {words:["Have","we","got","Art","on","Tuesday?"],             correct:"Have we got Art on Tuesday?"},
  {words:["I've","got","Geography","on","Friday."],             correct:"I've got Geography on Friday."},
  {words:["He","hasn't","got","Drama","on","Monday."],          correct:"He hasn't got Drama on Monday."},
  {words:["We've","got","Maths","on","Monday","at","nine","o'clock."], correct:"We've got Maths on Monday at nine o'clock."},
  {words:["Have","we","got","PE","on","Monday","at","eleven?"], correct:"Have we got PE on Monday at eleven?"},
  {words:["I","haven't","got","Art","on","Thursday."],          correct:"I haven't got Art on Thursday."},
  {words:["She's","got","History","on","Monday","at","ten."],   correct:"She's got History on Monday at ten."},
  {words:["Have","you","got","ICT","on","Friday?"],             correct:"Have you got ICT on Friday?"},
  {words:["We","haven't","got","English","on","Friday."],       correct:"We haven't got English on Friday."},
  {words:["I've","got","Science","on","Tuesday","at","eleven","o'clock."], correct:"I've got Science on Tuesday at eleven o'clock."},
  {words:["Have","we","got","Music","on","Wednesday","at","eleven?"], correct:"Have we got Music on Wednesday at eleven?"},
  {words:["He","hasn't","got","Geography","this","week."],      correct:"He hasn't got Geography this week."},
  {words:["She's","got","English","on","Tuesday","at","nine."], correct:"She's got English on Tuesday at nine."},
  {words:["Have","you","got","Drama","on","Tuesday?"],          correct:"Have you got Drama on Tuesday?"},
  {words:["We","haven't","got","PE","on","Thursday."],          correct:"We haven't got PE on Thursday."},
  {words:["I've","got","Maths","on","Wednesday","at","ten","o'clock."], correct:"I've got Maths on Wednesday at ten o'clock."},
  {words:["She","hasn't","got","ICT","this","week."],           correct:"She hasn't got ICT this week."},
  {words:["Have","we","got","English","on","Tuesday","at","nine?"], correct:"Have we got English on Tuesday at nine?"},
  {words:["I","haven't","got","PE","on","Wednesday."],          correct:"I haven't got PE on Wednesday."},
  {words:["We've","got","Art","on","Tuesday","at","ten","o'clock."], correct:"We've got Art on Tuesday at ten o'clock."},
  {words:["He","hasn't","got","Science","on","Monday."],        correct:"He hasn't got Science on Monday."},
];

const S7_POOL = [
  {stmt:"We've got Maths on Monday at 9:00.",         ans:true},
  {stmt:"We've got History on Tuesday at 10:00.",     ans:false},
  {stmt:"We've got PE on Monday at 11:00.",           ans:true},
  {stmt:"We've got English on Wednesday at 9:00.",    ans:false},
  {stmt:"We haven't got Drama this week.",            ans:true},
  {stmt:"We've got Science on Tuesday at 11:00.",     ans:true},
  {stmt:"We've got Music on Wednesday at 11:00.",     ans:true},
  {stmt:"We've got Art on Wednesday at 10:00.",       ans:false},
  {stmt:"We've got English on Tuesday at 9:00.",      ans:true},
  {stmt:"We've got History on Wednesday at 10:00.",   ans:false},
  {stmt:"We've got Science on Wednesday at 9:00.",    ans:true},
  {stmt:"We've got History on Monday at 10:00.",      ans:true},
  {stmt:"We've got Art on Tuesday at 10:00.",         ans:true},
  {stmt:"We've got Maths on Tuesday at 11:00.",       ans:false},
  {stmt:"We haven't got Geography this week.",        ans:true},
  {stmt:"We've got Maths on Wednesday at 10:00.",     ans:true},
  {stmt:"We've got PE on Monday at 9:00.",            ans:false},
  {stmt:"We've got Science on Wednesday at 11:00.",   ans:false},
  {stmt:"We've got History on Monday at 9:00.",       ans:false},
  {stmt:"We've got Art on Monday at 10:00.",          ans:false},
  {stmt:"We've got English on Monday at 9:00.",       ans:false},
  {stmt:"We've got Music on Tuesday at 11:00.",       ans:false},
  {stmt:"We've got PE on Wednesday at 11:00.",        ans:false},
  {stmt:"We've got History on Tuesday at 9:00.",      ans:false},
  {stmt:"We've got Science on Monday at 9:00.",       ans:false},
  {stmt:"We haven't got Art on Monday.",              ans:true},
  {stmt:"We haven't got PE on Wednesday.",            ans:true},
  {stmt:"We haven't got English on Monday.",          ans:true},
  {stmt:"We haven't got Music on Monday.",            ans:true},
  {stmt:"We haven't got History on Wednesday.",       ans:true},
  {stmt:"We haven't got Maths on Monday.",            ans:false},
  {stmt:"We haven't got English on Tuesday.",         ans:false},
  {stmt:"We haven't got Science on Wednesday.",       ans:false},
  {stmt:"We haven't got PE on Monday.",               ans:false},
  {stmt:"We haven't got Art on Tuesday.",             ans:false},
  {stmt:"We haven't got Music on Wednesday.",         ans:false},
  {stmt:"We haven't got History on Monday.",          ans:false},
  {stmt:"We've got ICT on Monday at 9:00.",           ans:false},
  {stmt:"We've got Drama on Tuesday at 10:00.",       ans:false},
  {stmt:"We haven't got ICT this week.",              ans:true},
  {stmt:"We haven't got Art on Wednesday.",           ans:true},
  {stmt:"We've got Maths on Monday and Wednesday.",   ans:true},
  {stmt:"We've got Science twice this week.",         ans:true},
  {stmt:"We've got English twice this week.",         ans:false},
  {stmt:"We've got Maths twice this week.",           ans:true},
  {stmt:"We've got Art on Wednesday at 11:00.",       ans:false},
  {stmt:"We've got Science on Monday at 10:00.",      ans:false},
  {stmt:"We've got English on Wednesday at 9:00.",    ans:false},
  {stmt:"We've got Music on Wednesday at 10:00.",     ans:false},
  {stmt:"We've got PE on Tuesday at 11:00.",          ans:false},
];
