const PLACES = [
  {name:'park',          icon:'🌳', cls:'cb-park'},
  {name:'school',        icon:'🏫', cls:'cb-school'},
  {name:'hospital',      icon:'🏥', cls:'cb-hospital'},
  {name:'museum',        icon:'🏛️', cls:'cb-museum'},
  {name:'bank',          icon:'🏦', cls:'cb-bank'},
  {name:'café',          icon:'☕', cls:'cb-cafe'},
  {name:'cinema',        icon:'🎬', cls:'cb-cinema'},
  {name:'zoo',           icon:'🦁', cls:'cb-zoo'},
  {name:'library',       icon:'📚', cls:'cb-library'},
  {name:'train station', icon:'🚂', cls:'cb-school'},
  {name:'supermarket',   icon:'🛒', cls:'cb-bank'},
  {name:'toy shop',      icon:'🧸', cls:'cb-cafe'},
  {name:'sports centre', icon:'🏊', cls:'cb-school'},
  {name:'post office',   icon:'📮', cls:'cb-museum'},
  {name:'fire station',  icon:'🚒', cls:'cb-hospital'},
  {name:'restaurant',    icon:'🍽️', cls:'cb-cafe'},
  {name:'pharmacy',      icon:'💊', cls:'cb-hospital'},
  {name:'bakery',        icon:'🥖', cls:'cb-cafe'},
];

/* Fixed 3×3 map grid: [row0col0, row0col1, row0col2, row1col0, ...] */
const MAP_PLACES = [
  {name:'park',     icon:'🌳', cls:'cb-park'},
  {name:'bank',     icon:'🏦', cls:'cb-bank'},
  {name:'hospital', icon:'🏥', cls:'cb-hospital'},
  {name:'café',     icon:'☕', cls:'cb-cafe'},
  {name:'museum',   icon:'🏛️', cls:'cb-museum'},
  {name:'library',  icon:'📚', cls:'cb-library'},
  {name:'cinema',   icon:'🎬', cls:'cb-cinema'},
  {name:'school',   icon:'🏫', cls:'cb-school'},
  {name:'zoo',      icon:'🦁', cls:'cb-zoo'},
];

/* Adjacency facts derived from the fixed map */
const PREP_FACTS = [
  {a:'park',     prep:'next to',    b:'bank',     ans:true},
  {a:'bank',     prep:'next to',    b:'hospital', ans:true},
  {a:'café',     prep:'next to',    b:'museum',   ans:true},
  {a:'museum',   prep:'next to',    b:'library',  ans:true},
  {a:'cinema',   prep:'next to',    b:'school',   ans:true},
  {a:'school',   prep:'next to',    b:'zoo',      ans:true},
  {a:'park',     prep:'next to',    b:'café',     ans:true},
  {a:'bank',     prep:'next to',    b:'museum',   ans:true},
  {a:'hospital', prep:'next to',    b:'library',  ans:true},
  {a:'park',     prep:'next to',    b:'hospital', ans:false},
  {a:'cinema',   prep:'next to',    b:'bank',     ans:false},
  {a:'zoo',      prep:'next to',    b:'café',     ans:false},
  {a:'park',     prep:'opposite',   b:'cinema',   ans:true},
  {a:'bank',     prep:'opposite',   b:'school',   ans:true},
  {a:'hospital', prep:'opposite',   b:'zoo',      ans:true},
  {a:'park',     prep:'opposite',   b:'hospital', ans:false},
  {a:'café',     prep:'opposite',   b:'zoo',      ans:false},
  {a:'bank',     prep:'between',    b:'the park and the hospital', ans:true},
  {a:'museum',   prep:'between',    b:'the café and the library',  ans:true},
  {a:'school',   prep:'between',    b:'the cinema and the zoo',    ans:true},
  {a:'café',     prep:'between',    b:'the park and the cinema',   ans:true},
  {a:'bank',     prep:'between',    b:'the café and the library',  ans:false},
];

const S3_POOL = [
  {q:"Is there a park in the town?",              yes:"Yes, there is.",   no:"No, there isn't.",  ans:true},
  {q:"Is there a hospital in the town?",          yes:"Yes, there is.",   no:"No, there isn't.",  ans:true},
  {q:"Is there a museum in the town?",            yes:"Yes, there is.",   no:"No, there isn't.",  ans:true},
  {q:"Is there a zoo in the town?",               yes:"Yes, there is.",   no:"No, there isn't.",  ans:true},
  {q:"Is there a cinema in the town?",            yes:"Yes, there is.",   no:"No, there isn't.",  ans:true},
  {q:"Is there a supermarket in the town?",       yes:"Yes, there is.",   no:"No, there isn't.",  ans:false},
  {q:"Is there a toy shop in the town?",          yes:"Yes, there is.",   no:"No, there isn't.",  ans:false},
  {q:"Is there a train station in the town?",     yes:"Yes, there is.",   no:"No, there isn't.",  ans:false},
  {q:"Are there any shops in the town?",          yes:"Yes, there are.",  no:"No, there aren't.", ans:false},
  {q:"Are there any schools in the town?",        yes:"Yes, there are.",  no:"No, there aren't.", ans:true},
  {q:"Are there any cafés in the town?",          yes:"Yes, there are.",  no:"No, there aren't.", ans:true},
  {q:"Are there any libraries in the town?",      yes:"Yes, there are.",  no:"No, there aren't.", ans:true},
  {q:"Is there a bank in the town?",              yes:"Yes, there is.",   no:"No, there isn't.",  ans:true},
  {q:"Is there a sports centre in the town?",     yes:"Yes, there is.",   no:"No, there isn't.",  ans:false},
  {q:"Is there a post office in the town?",       yes:"Yes, there is.",   no:"No, there isn't.",  ans:false},
  {q:"Is there a fire station in the town?",      yes:"Yes, there is.",   no:"No, there isn't.",  ans:false},
  {q:"Is there a restaurant in the town?",        yes:"Yes, there is.",   no:"No, there isn't.",  ans:false},
  {q:"Is there a library in the town?",           yes:"Yes, there is.",   no:"No, there isn't.",  ans:true},
  {q:"Are there any banks in the town?",          yes:"Yes, there are.",  no:"No, there aren't.", ans:true},
  {q:"Are there any museums in the town?",        yes:"Yes, there are.",  no:"No, there aren't.", ans:true},
  {q:"Are there any zoos in the town?",           yes:"Yes, there are.",  no:"No, there aren't.", ans:true},
  {q:"Is there a café in the town?",              yes:"Yes, there is.",   no:"No, there isn't.",  ans:true},
  {q:"Is there a school in the town?",            yes:"Yes, there is.",   no:"No, there isn't.",  ans:true},
  {q:"Are there any parks in the town?",          yes:"Yes, there are.",  no:"No, there aren't.", ans:true},
  {q:"Are there any hospitals in the town?",      yes:"Yes, there are.",  no:"No, there aren't.", ans:true},
  {q:"Are there any cinemas in the town?",        yes:"Yes, there are.",  no:"No, there aren't.", ans:true},
  {q:"Is there a pharmacy in the town?",          yes:"Yes, there is.",   no:"No, there isn't.",  ans:false},
  {q:"Is there a bakery in the town?",            yes:"Yes, there is.",   no:"No, there isn't.",  ans:false},
  {q:"Are there any restaurants in the town?",    yes:"Yes, there are.",  no:"No, there aren't.", ans:false},
  {q:"Are there any fire stations in the town?",  yes:"Yes, there are.",  no:"No, there aren't.", ans:false},
  {q:"Are there any supermarkets in the town?",   yes:"Yes, there are.",  no:"No, there aren't.", ans:false},
  {q:"Are there any toy shops in the town?",      yes:"Yes, there are.",  no:"No, there aren't.", ans:false},
  {q:"Are there any train stations in the town?", yes:"Yes, there are.",  no:"No, there aren't.", ans:false},
  {q:"Are there any post offices in the town?",   yes:"Yes, there are.",  no:"No, there aren't.", ans:false},
  {q:"Are there any sports centres in the town?", yes:"Yes, there are.",  no:"No, there aren't.", ans:false},
  {q:"Are there any pharmacies in the town?",     yes:"Yes, there are.",  no:"No, there aren't.", ans:false},
  {q:"Are there any bakeries in the town?",       yes:"Yes, there are.",  no:"No, there aren't.", ans:false},
  {q:"Is there a swimming pool in the town?",     yes:"Yes, there is.",   no:"No, there isn't.",  ans:false},
  {q:"Is there a hotel in the town?",             yes:"Yes, there is.",   no:"No, there isn't.",  ans:false},
  {q:"Is there a castle in the town?",            yes:"Yes, there is.",   no:"No, there isn't.",  ans:false},
  {q:"Is there a beach in the town?",             yes:"Yes, there is.",   no:"No, there isn't.",  ans:false},
  {q:"Is there a market in the town?",            yes:"Yes, there is.",   no:"No, there isn't.",  ans:false},
  {q:"Is there a stadium in the town?",           yes:"Yes, there is.",   no:"No, there isn't.",  ans:false},
  {q:"Is there an airport in the town?",          yes:"Yes, there is.",   no:"No, there isn't.",  ans:false},
  {q:"Is there a bookshop in the town?",          yes:"Yes, there is.",   no:"No, there isn't.",  ans:false},
  {q:"Is there a church in the town?",            yes:"Yes, there is.",   no:"No, there isn't.",  ans:false},
  {q:"Are there any hotels in the town?",         yes:"Yes, there are.",  no:"No, there aren't.", ans:false},
  {q:"Are there any castles in the town?",        yes:"Yes, there are.",  no:"No, there aren't.", ans:false},
  {q:"Are there any stadiums in the town?",       yes:"Yes, there are.",  no:"No, there aren't.", ans:false},
  {q:"Are there any airports in the town?",       yes:"Yes, there are.",  no:"No, there aren't.", ans:false},
];

const S5_POOL = [
  {words:["Is","there","a","park","in","the","town?"],                         correct:"Is there a park in the town?"},
  {words:["There","is","a","museum","next","to","the","bank."],                correct:"There is a museum next to the bank."},
  {words:["Is","there","a","supermarket","near","here?"],                      correct:"Is there a supermarket near here?"},
  {words:["There","isn't","a","train","station","in","the","town."],           correct:"There isn't a train station in the town."},
  {words:["Are","there","any","shops","in","the","town?"],                     correct:"Are there any shops in the town?"},
  {words:["The","café","is","opposite","the","zoo."],                          correct:"The café is opposite the zoo."},
  {words:["The","bank","is","between","the","park","and","the","hospital."],   correct:"The bank is between the park and the hospital."},
  {words:["There","are","a","lot","of","places","in","the","town."],           correct:"There are a lot of places in the town."},
  {words:["The","cinema","is","next","to","the","school."],                    correct:"The cinema is next to the school."},
  {words:["There","isn't","a","zoo","opposite","the","park."],                 correct:"There isn't a zoo opposite the park."},
  {words:["Is","there","a","library","in","the","town?"],                      correct:"Is there a library in the town?"},
  {words:["The","zoo","is","opposite","the","cinema."],                        correct:"The zoo is opposite the cinema."},
  {words:["There","isn't","a","sports","centre","in","the","town."],           correct:"There isn't a sports centre in the town."},
  {words:["The","museum","is","between","the","café","and","the","library."],  correct:"The museum is between the café and the library."},
  {words:["Is","there","a","post","office","near","here?"],                    correct:"Is there a post office near here?"},
  {words:["There","are","two","parks","in","the","town."],                     correct:"There are two parks in the town."},
  {words:["The","park","is","next","to","the","café."],                        correct:"The park is next to the café."},
  {words:["Is","there","a","café","in","the","town?"],                         correct:"Is there a café in the town?"},
  {words:["The","hospital","is","opposite","the","zoo."],                      correct:"The hospital is opposite the zoo."},
  {words:["There","isn't","a","pharmacy","in","the","town."],                  correct:"There isn't a pharmacy in the town."},
  {words:["The","café","is","next","to","the","museum."],                      correct:"The café is next to the museum."},
  {words:["Is","there","a","hospital","near","here?"],                         correct:"Is there a hospital near here?"},
  {words:["There","isn't","a","bakery","in","the","town."],                    correct:"There isn't a bakery in the town."},
  {words:["The","bank","is","opposite","the","school."],                       correct:"The bank is opposite the school."},
  {words:["The","library","is","next","to","the","museum."],                   correct:"The library is next to the museum."},
  {words:["Is","there","a","school","in","the","town?"],                       correct:"Is there a school in the town?"},
  {words:["There","is","a","library","next","to","the","hospital."],           correct:"There is a library next to the hospital."},
  {words:["The","café","is","between","the","park","and","the","cinema."],     correct:"The café is between the park and the cinema."},
  {words:["There","isn't","a","hotel","in","the","town."],                     correct:"There isn't a hotel in the town."},
  {words:["The","bank","is","next","to","the","park."],                        correct:"The bank is next to the park."},
  {words:["Are","there","any","parks","in","the","town?"],                     correct:"Are there any parks in the town?"},
  {words:["The","school","is","between","the","cinema","and","the","zoo."],    correct:"The school is between the cinema and the zoo."},
  {words:["Is","there","a","museum","next","to","the","library?"],             correct:"Is there a museum next to the library?"},
  {words:["There","is","a","zoo","next","to","the","school."],                 correct:"There is a zoo next to the school."},
  {words:["The","cinema","is","opposite","the","park."],                       correct:"The cinema is opposite the park."},
  {words:["Are","there","any","schools","in","the","town?"],                   correct:"Are there any schools in the town?"},
  {words:["The","hospital","is","next","to","the","bank."],                    correct:"The hospital is next to the bank."},
  {words:["There","isn't","a","restaurant","in","the","town."],                correct:"There isn't a restaurant in the town."},
  {words:["Is","there","a","bank","next","to","the","park?"],                  correct:"Is there a bank next to the park?"},
  {words:["The","library","is","between","the","hospital","and","the","zoo."], correct:"The library is between the hospital and the zoo."},
  {words:["Is","there","a","cinema","in","the","town?"],                       correct:"Is there a cinema in the town?"},
  {words:["There","isn't","a","fire","station","near","here."],                correct:"There isn't a fire station near here."},
  {words:["The","museum","is","next","to","the","bank."],                      correct:"The museum is next to the bank."},
  {words:["Are","there","any","libraries","in","the","town?"],                 correct:"Are there any libraries in the town?"},
  {words:["Is","there","a","zoo","in","the","town?"],                          correct:"Is there a zoo in the town?"},
  {words:["The","park","is","opposite","the","cinema."],                       correct:"The park is opposite the cinema."},
  {words:["There","isn't","a","supermarket","in","the","town."],               correct:"There isn't a supermarket in the town."},
  {words:["Is","there","a","café","opposite","the","cinema?"],                 correct:"Is there a café opposite the cinema?"},
  {words:["Are","there","any","museums","in","the","town?"],                   correct:"Are there any museums in the town?"},
  {words:["There","is","a","café","next","to","the","park."],                  correct:"There is a café next to the park."},
];
