const JOBS = [
  {name:'police officer',   pronoun:'she', icon:'👮', desc:'She keeps people safe in the streets and catches criminals.'},
  {name:'vet',              pronoun:'she', icon:'🐾', desc:'She helps sick and injured animals get better.'},
  {name:'firefighter',      pronoun:'he',  icon:'🚒', desc:'He puts out fires and rescues people from danger.'},
  {name:'doctor',           pronoun:'he',  icon:'🩺', desc:'He helps sick people and works in a hospital or clinic.'},
  {name:'farmer',           pronoun:'he',  icon:'🌾', desc:'He grows vegetables and fruit and looks after animals on his farm.'},
  {name:'nurse',            pronoun:'she', icon:'💊', desc:'She looks after patients and helps doctors in a hospital.'},
  {name:'pop star',         pronoun:'she', icon:'🎤', desc:'She sings songs and performs on stage in front of big audiences.'},
  {name:'shop assistant',   pronoun:'she', icon:'🛍️', desc:'She helps customers find and buy things in a shop.'},
  {name:'fashion designer', pronoun:'she', icon:'👗', desc:'She designs and creates beautiful clothes for people to wear.'},
  {name:'taxi driver',      pronoun:'he',  icon:'🚕', desc:'He drives people around the city in his car.'},
  {name:'teacher',          pronoun:'she', icon:'📚', desc:'She teaches children and helps them learn new things at school.'},
  {name:'chef',             pronoun:'he',  icon:'👨‍🍳', desc:'He prepares and cooks delicious food in a restaurant kitchen.'},
  {name:'pilot',            pronoun:'he',  icon:'✈️',  desc:'He flies aeroplanes and takes passengers to different countries.'},
  {name:'engineer',         pronoun:'he',  icon:'🔧',  desc:'He designs and builds machines and bridges.'},
  {name:'dentist',          pronoun:'she', icon:'🦷',  desc:'She takes care of teeth and helps people have a healthy smile.'},
  {name:'journalist',       pronoun:'she', icon:'📰',  desc:'She writes articles and reports the news for newspapers and TV.'},
  {name:'librarian',        pronoun:'she', icon:'📖',  desc:'She helps people find and borrow books in a library.'},
];

const TF_POOL = [
  {stmt:"A teacher works in a school.",          ans:true},
  {stmt:"A vet helps sick people.",              ans:false},
  {stmt:"A firefighter drives a taxi.",           ans:false},
  {stmt:"A nurse works in a hospital.",           ans:true},
  {stmt:"A farmer grows food.",                   ans:true},
  {stmt:"A fashion designer makes clothes.",      ans:true},
  {stmt:"A pop star works in a bank.",            ans:false},
  {stmt:"A police officer keeps people safe.",    ans:true},
  {stmt:"A doctor helps sick animals.",           ans:false},
  {stmt:"A shop assistant works in a shop.",      ans:true},
  {stmt:"A taxi driver works in an office.",      ans:false},
  {stmt:"A police officer wears a uniform.",      ans:true},
  {stmt:"A vet wears a uniform.",                 ans:false},
  {stmt:"A firefighter puts out fires.",          ans:true},
  {stmt:"A pop star wears a uniform.",            ans:false},
  {stmt:"A doctor works in a hospital.",          ans:true},
  {stmt:"A farmer works outdoors.",               ans:true},
  {stmt:"A fashion designer wears a uniform.",     ans:false},
  {stmt:"A nurse looks after patients.",           ans:true},
  {stmt:"A taxi driver works in a hospital.",      ans:false},
  {stmt:"A teacher helps children learn.",         ans:true},
  {stmt:"A vet works with plants.",                ans:false},
  {stmt:"A pop star sings songs.",                 ans:true},
  {stmt:"A police officer drives a fire engine.",  ans:false},
  {stmt:"A firefighter is brave.",                 ans:true},
  {stmt:"A shop assistant sells things in a shop.",ans:true},
  {stmt:"A chef cooks food in a restaurant.",         ans:true},
  {stmt:"A chef flies aeroplanes.",                    ans:false},
  {stmt:"A chef wears a uniform.",                     ans:true},
  {stmt:"A pilot flies aeroplanes.",                   ans:true},
  {stmt:"A pilot works in a school.",                  ans:false},
  {stmt:"A pilot wears a uniform.",                    ans:true},
  {stmt:"An engineer builds bridges and machines.",    ans:true},
  {stmt:"An engineer wears a uniform.",                ans:false},
  {stmt:"A dentist looks after people's teeth.",       ans:true},
  {stmt:"A dentist works in a hospital.",              ans:false},
  {stmt:"A dentist wears a uniform.",                  ans:true},
  {stmt:"A journalist writes articles and news.",      ans:true},
  {stmt:"A journalist wears a uniform.",               ans:false},
  {stmt:"A librarian works in a library.",             ans:true},
  {stmt:"A librarian wears a uniform.",                ans:false},
  {stmt:"A librarian helps people borrow books.",      ans:true},
];

const WEAR_POOL = [
  {job:'police officer',   wears:true},
  {job:'vet',              wears:false},
  {job:'firefighter',      wears:true},
  {job:'doctor',           wears:true},
  {job:'nurse',            wears:true},
  {job:'pop star',         wears:false},
  {job:'farmer',           wears:false},
  {job:'taxi driver',      wears:false},
  {job:'fashion designer', wears:false},
  {job:'teacher',          wears:false},
  {job:'shop assistant',   wears:false},
  {job:'chef',             wears:true},
  {job:'pilot',            wears:true},
  {job:'engineer',         wears:false},
  {job:'dentist',          wears:true},
  {job:'journalist',       wears:false},
  {job:'librarian',        wears:false},
];

const DOES_POOL = [
  {q:"Does a nurse wear a uniform?",             pronoun:'she', ans:true},
  {q:"Does a farmer work in an office?",          pronoun:'he',  ans:false},
  {q:"Does a pop star work in a school?",         pronoun:'she', ans:false},
  {q:"Does a doctor work in a hospital?",         pronoun:'he',  ans:true},
  {q:"Does a vet help sick animals?",             pronoun:'she', ans:true},
  {q:"Does a taxi driver wear a uniform?",        pronoun:'he',  ans:false},
  {q:"Does a teacher work in a school?",          pronoun:'she', ans:true},
  {q:"Does a fashion designer make clothes?",     pronoun:'she', ans:true},
  {q:"Does a firefighter put out fires?",         pronoun:'he',  ans:true},
  {q:"Does a police officer keep people safe?",   pronoun:'she', ans:true},
  {q:"Does a shop assistant work in a shop?",     pronoun:'she', ans:true},
  {q:"Does a pop star wear a uniform?",           pronoun:'she', ans:false},
  {q:"Does a vet work in a hospital?",            pronoun:'she', ans:false},
  {q:"Does a firefighter wear a uniform?",        pronoun:'he',  ans:true},
  {q:"Does a farmer grow food?",                  pronoun:'he',  ans:true},
  {q:"Does a shop assistant help customers?",     pronoun:'she', ans:true},
  {q:"Does a doctor drive a taxi?",               pronoun:'he',  ans:false},
  {q:"Does a nurse look after patients?",         pronoun:'she', ans:true},
  {q:"Does a pop star sing songs?",               pronoun:'she', ans:true},
  {q:"Does a taxi driver work in an office?",     pronoun:'he',  ans:false},
  {q:"Does a fashion designer work in a school?", pronoun:'she', ans:false},
  {q:"Does a teacher help students?",             pronoun:'she', ans:true},
  {q:"Does a police officer work in the streets?",pronoun:'she', ans:true},
  {q:"Does a chef cook food in a restaurant?",    pronoun:'he',  ans:true},
  {q:"Does a chef fly aeroplanes?",               pronoun:'he',  ans:false},
  {q:"Does a pilot wear a uniform?",              pronoun:'he',  ans:true},
  {q:"Does a pilot work in a school?",            pronoun:'he',  ans:false},
  {q:"Does an engineer build bridges?",           pronoun:'he',  ans:true},
  {q:"Does an engineer wear a uniform?",          pronoun:'he',  ans:false},
  {q:"Does a dentist look after teeth?",          pronoun:'she', ans:true},
  {q:"Does a dentist work in a hospital?",        pronoun:'she', ans:false},
  {q:"Does a journalist write articles?",         pronoun:'she', ans:true},
  {q:"Does a journalist wear a uniform?",         pronoun:'she', ans:false},
  {q:"Does a librarian work in a library?",       pronoun:'she', ans:true},
  {q:"Does a librarian help people find books?",  pronoun:'she', ans:true},
];

const S5_POOL = [
  {words:["Does","a","nurse","wear","a","uniform?"],           correct:"Does a nurse wear a uniform?"},
  {words:["A","vet","doesn't","wear","a","uniform."],          correct:"A vet doesn't wear a uniform."},
  {words:["She","works","in","a","hospital."],                 correct:"She works in a hospital."},
  {words:["Does","a","teacher","work","in","a","school?"],     correct:"Does a teacher work in a school?"},
  {words:["He","doesn't","work","in","an","office."],          correct:"He doesn't work in an office."},
  {words:["Does","a","pop","star","wear","a","uniform?"],      correct:"Does a pop star wear a uniform?"},
  {words:["She","doesn't","wear","a","uniform."],              correct:"She doesn't wear a uniform."},
  {words:["A","farmer","works","on","a","farm."],              correct:"A farmer works on a farm."},
  {words:["Does","a","doctor","work","in","a","hospital?"],    correct:"Does a doctor work in a hospital?"},
  {words:["He","doesn't","drive","a","taxi."],                 correct:"He doesn't drive a taxi."},
  {words:["A","police","officer","wears","a","uniform."],      correct:"A police officer wears a uniform."},
  {words:["Does","a","firefighter","put","out","fires?"],      correct:"Does a firefighter put out fires?"},
  {words:["She","teaches","children","at","school."],          correct:"She teaches children at school."},
  {words:["She","helps","sick","animals."],                    correct:"She helps sick animals."},
  {words:["A","pop","star","doesn't","wear","a","uniform."],   correct:"A pop star doesn't wear a uniform."},
  {words:["Does","a","shop","assistant","work","in","a","shop?"],correct:"Does a shop assistant work in a shop?"},
  {words:["She","doesn't","work","in","a","hospital."],        correct:"She doesn't work in a hospital."},
  {words:["A","taxi","driver","doesn't","wear","a","uniform."],correct:"A taxi driver doesn't wear a uniform."},
  {words:["A","chef","wears","a","uniform."],                  correct:"A chef wears a uniform."},
  {words:["Does","a","pilot","fly","aeroplanes?"],              correct:"Does a pilot fly aeroplanes?"},
  {words:["A","dentist","takes","care","of","people's","teeth."], correct:"A dentist takes care of people's teeth."},
  {words:["She","works","in","a","library."],                   correct:"She works in a library."},
  {words:["A","journalist","doesn't","wear","a","uniform."],    correct:"A journalist doesn't wear a uniform."},
];

const GUESS_POOL = [
  {icon:'🐾', ans:'vet',
   clues:["She helps sick and injured animals.","She doesn't wear a uniform.","She works in a clinic, not a hospital."],
   opts:['vet','doctor','nurse','farmer']},
  {icon:'🚒', ans:'firefighter',
   clues:["He puts out fires.","He wears a uniform.","He is very brave and helps people in danger."],
   opts:['firefighter','police officer','taxi driver','doctor']},
  {icon:'👗', ans:'fashion designer',
   clues:["She creates beautiful clothes.","She doesn't wear a uniform.","She works in a studio and is very creative."],
   opts:['fashion designer','pop star','shop assistant','teacher']},
  {icon:'👮', ans:'police officer',
   clues:["She keeps people safe.","She wears a uniform.","She works in the streets and can arrest criminals."],
   opts:['police officer','firefighter','nurse','teacher']},
  {icon:'🎤', ans:'pop star',
   clues:["She performs on stage for thousands of fans.","She doesn't wear a uniform.","She is famous and sings songs."],
   opts:['pop star','fashion designer','teacher','shop assistant']},
  {icon:'🌾', ans:'farmer',
   clues:["He grows vegetables and fruit.","He doesn't work in an office.","He wakes up very early and works outdoors."],
   opts:['farmer','taxi driver','vet','shop assistant']},
  {icon:'🚕', ans:'taxi driver',
   clues:["He drives people around the city.","He works at night and during the day.","He knows all the streets very well."],
   opts:['taxi driver','farmer','firefighter','police officer']},
  {icon:'📚', ans:'teacher',
   clues:["She works with children every day.","She doesn't wear a uniform.","She helps students learn new things."],
   opts:['teacher','nurse','shop assistant','pop star']},
  {icon:'💊', ans:'nurse',
   clues:["She wears a uniform.","She works in a hospital.","She looks after sick patients and helps doctors."],
   opts:['nurse','doctor','vet','police officer']},
  {icon:'📚', ans:'teacher',
   clues:["She works with children every day.","She doesn't wear a uniform.","She helps students learn new things at school."],
   opts:['teacher','nurse','shop assistant','fashion designer']},
  {icon:'🛍️', ans:'shop assistant',
   clues:["She works in a shop.","She doesn't wear a uniform.","She helps customers find and buy things."],
   opts:['shop assistant','fashion designer','pop star','teacher']},
  {icon:'👨‍🍳', ans:'chef',
   clues:["He works in a restaurant kitchen.","He wears a uniform.","He prepares and cooks delicious food."],
   opts:['chef','farmer','doctor','shop assistant']},
  {icon:'✈️', ans:'pilot',
   clues:["He flies aeroplanes.","He wears a uniform.","He takes passengers to different countries."],
   opts:['pilot','taxi driver','firefighter','engineer']},
  {icon:'🦷', ans:'dentist',
   clues:["She takes care of your teeth.","She wears a uniform.","She works in a clinic and gives you a healthy smile."],
   opts:['dentist','nurse','doctor','vet']},
  {icon:'📰', ans:'journalist',
   clues:["She writes articles and reports news.","She doesn't wear a uniform.","She interviews people and works for newspapers or TV."],
   opts:['journalist','teacher','fashion designer','librarian']},
];
