const STORIES = [

{id:0, title:'Caperucita Roja',
text:`<p>Érase una vez una niña muy alegre que vivía cerca de un bosque. Su abuela le había regalado una capa roja con capucha, y la niña la llevaba tan a menudo que todo el mundo la llamaba Caperucita Roja. Un día, su madre le preparó una cesta con pan, mantequilla y mermelada para que se la llevara a su abuela, que estaba enferma y vivía al otro lado del bosque.</p>
<p>Caperucita prometió ir por el camino sin desviarse, pero al entrar en el bosque vio flores tan bonitas que se apartó del sendero para recogerlas. Allí se encontró con un lobo enorme. El lobo le preguntó adónde iba y Caperucita, sin pensar en el peligro, le contó todo: que llevaba comida a su abuela y dónde vivía ella.</p>
<p>El lobo se fue corriendo por el camino más corto y llegó antes que Caperucita a casa de la abuela. Llamó a la puerta imitando la voz de la niña. La anciana abrió y el lobo la encerró en el armario. Luego se disfrazó con el gorro y la ropa de la abuela y se metió en la cama a esperar.</p>
<p>Cuando Caperucita llegó, notó que «su abuela» tenía los ojos enormes, las orejas muy grandes y una boca enorme. Al comprender que era el lobo, Caperucita gritó. Un cazador que pasaba cerca oyó los gritos, entró corriendo y asustó al lobo, que huyó sin volver nunca más. La abuela salió del armario sana y salva y las tres festejaron juntas con toda la comida de la cesta.</p>`,
questions:[
{type:'c', q:'¿Quién le regaló la capa roja a Caperucita?', opts:['Su madre','Su abuela','Una vecina','Una hada'], ans:1, exp:'El texto dice que su abuela le había regalado una capa roja con capucha.'},
{type:'c', q:'¿Por qué fue Caperucita al bosque?', opts:['Para recoger flores','Para buscar al lobo','Para llevar comida a su abuela enferma','Para visitar a un cazador'], ans:2, exp:'Su madre le preparó una cesta con comida para llevarle a su abuela, que estaba enferma.'},
{type:'c', q:'¿Qué hizo el lobo al enterarse de dónde vivía la abuela?', opts:['Se quedó esperando a Caperucita','La siguió despacio por el bosque','Fue corriendo a casa de la abuela por el camino más corto','Se fue a buscar a la madre'], ans:2, exp:'El lobo se fue corriendo por el camino más corto y llegó antes que Caperucita.'},
{type:'c', q:'¿Dónde escondió el lobo a la abuela?', opts:['Debajo de la cama','En el sótano','En el jardín','En el armario'], ans:3, exp:'El lobo encerró a la abuela en el armario y se disfrazó con su ropa.'},
{type:'c', q:'¿Quién salvó a Caperucita y a su abuela?', opts:['La madre de Caperucita','Un vecino del pueblo','Un cazador que pasaba cerca','La propia abuela'], ans:2, exp:'Un cazador que oyó los gritos de Caperucita entró corriendo y asustó al lobo.'},
{type:'c', q:'¿Por qué se desvió Caperucita del camino?', opts:['Porque vio al lobo','Porque estaba cansada','Porque vio flores bonitas','Porque se perdió'], ans:2, exp:'Al entrar en el bosque, Caperucita vio flores tan bonitas que se apartó del sendero para recogerlas.'},
{type:'f', t:'Caperucita llevaba una {0} con pan, mantequilla y mermelada para su abuela.', blanks:['cesta'], pool:['cesta','bolsa','caja','mochila','maleta','carro'], exp:'El texto dice que su madre le preparó una cesta con esa comida para la abuela.'},
{type:'f', t:'El lobo se disfrazó con el gorro y la {0} de la abuela y se metió en la cama.', blanks:['ropa'], pool:['ropa','bufanda','capa','sombrero','manta','falda'], exp:'El lobo se puso la ropa de la abuela para engañar a Caperucita cuando llegara.'},
{type:'f', t:'La niña se llamaba Caperucita Roja porque siempre llevaba una {0} roja.', blanks:['capa'], pool:['capa','falda','bufanda','chaqueta','manta','bolsa'], exp:'Su abuela le había regalado una capa roja con capucha y por eso todos la llamaban así.'},
{type:'v', q:'La abuela de Caperucita estaba enferma.', ans:true, exp:'El texto dice que la abuela estaba enferma y vivía al otro lado del bosque.'},
{type:'v', q:'Caperucita fue directamente a casa de la abuela sin parar.', ans:false, exp:'Caperucita se apartó del sendero para recoger flores y allí encontró al lobo.'},
{type:'v', q:'Al final, la abuela salió sana y salva del armario.', ans:true, exp:'El cazador asustó al lobo y la abuela pudo salir del armario sana y salva.'}
]},

{id:1, title:'Los tres cerditos',
text:`<p>Había una vez tres cerditos hermanos que se llamaban Tito, Pipo y Rico. Un día, su madre les dijo que ya eran mayores y que debían construir sus propias casas para protegerse del lobo feroz que vivía en el bosque. Los tres prometieron que lo harían, pero cada uno tenía una idea muy diferente.</p>
<p>Tito, el más pequeño y perezoso, construyó su casa de paja en un solo día. «¡Ya está! —dijo—. Así tendré tiempo para jugar.» Pipo, el mediano, tardó un poco más y construyó su casa de madera. Solo Rico, el mayor, se tomó el trabajo en serio y construyó una casa de ladrillo, aunque tardó mucho tiempo y sus hermanos se rieron de él.</p>
<p>Un día llegó el lobo hambriento. Primero fue a casa de Tito y sopló tan fuerte que la casa de paja cayó en un momento. Tito corrió a casa de Pipo. El lobo fue a por ellos y sopló con más fuerza: la casa de madera también se derrumbó. Los dos cerditos corrieron entonces a casa de Rico.</p>
<p>El lobo sopló y sopló, pero la casa de ladrillo no se movió. Furioso, intentó entrar por la chimenea. Los tres cerditos pusieron rápidamente una olla con agua hirviendo debajo. El lobo cayó dentro, se quemó y huyó despavorido. Desde ese día, los tres hermanos vivieron juntos en la casa de Rico y aprendieron que el trabajo bien hecho siempre vale la pena.</p>`,
questions:[
{type:'c', q:'¿Por qué la madre pidió a los cerditos que construyeran sus casas?', opts:['Porque quería estar sola','Para protegerse del lobo feroz','Para ganar un concurso','Porque la casa antigua era muy vieja'], ans:1, exp:'La madre les dijo que ya eran mayores y debían construir casas para protegerse del lobo.'},
{type:'c', q:'¿De qué material construyó su casa Pipo, el cerdito mediano?', opts:['De paja','De ladrillo','De piedra','De madera'], ans:3, exp:'Pipo, el mediano, construyó su casa de madera, tardando más que Tito pero menos que Rico.'},
{type:'c', q:'¿Por qué se rieron Tito y Pipo de Rico?', opts:['Porque Rico no sabía construir','Porque la casa de Rico era muy pequeña','Porque Rico tardó mucho tiempo en construir su casa de ladrillo','Porque Rico usaba materiales muy caros'], ans:2, exp:'Rico tardó mucho tiempo en construir su casa de ladrillo y sus hermanos se rieron de él por eso.'},
{type:'c', q:'¿En qué orden atacó el lobo las casas?', opts:['Primero la de ladrillo, luego la de madera, luego la de paja','Primero la de paja, luego la de madera, luego la de ladrillo','Primero la de madera, luego la de paja, luego la de ladrillo','Las tres al mismo tiempo'], ans:1, exp:'El lobo fue primero a casa de Tito (paja), luego a casa de Pipo (madera), y finalmente intentó la de Rico (ladrillo).'},
{type:'c', q:'¿Cómo intentó el lobo entrar en la casa de ladrillo al no poder derribarla?', opts:['Rompiendo una ventana','Cavando un túnel','Entrando por la chimenea','Esperando que los cerditos salieran'], ans:2, exp:'Al no poder derribar la casa de ladrillo soplando, el lobo intentó entrar por la chimenea.'},
{type:'f', t:'Tito construyó su casa de {0} en un solo día porque era el más {1}.', blanks:['paja','perezoso'], pool:['paja','perezoso','madera','valiente','ladrillo','trabajador'], exp:'Tito, el más perezoso, construyó la casa de paja rápidamente para tener tiempo de jugar.'},
{type:'f', t:'Los cerditos pusieron una olla con agua {0} debajo de la chimenea para atrapar al lobo.', blanks:['hirviendo'], pool:['hirviendo','fría','tibia','caliente','sucia','salada'], exp:'Pusieron agua hirviendo para que el lobo cayera dentro al bajar por la chimenea.'},
{type:'v', q:'Rico, el cerdito mayor, construyó su casa de paja.', ans:false, exp:'Rico construyó su casa de ladrillo. La de paja la construyó Tito, el más pequeño y perezoso.'},
{type:'v', q:'El lobo consiguió derribar la casa de ladrillo soplando.', ans:false, exp:'La casa de ladrillo era muy sólida: el lobo sopló y sopló pero no se movió.'},
{type:'v', q:'Al final, los tres cerditos vivieron juntos en la casa de Rico.', ans:true, exp:'El texto dice que desde ese día los tres hermanos vivieron juntos en la casa de Rico.'},
{type:'v', q:'La lección del cuento es que el trabajo bien hecho siempre vale la pena.', ans:true, exp:'El propio texto lo dice al final del cuento.'}
]},

{id:2, title:'La liebre y la tortuga',
text:`<p>En un prado verde y soleado vivían muchos animales. Entre ellos había una liebre muy presuntuosa que se pasaba el día alardeando de lo rápida que era. «¡Nadie puede correr más que yo!», decía siempre. Un día, la tortuga, que era tranquila y constante, la retó a una carrera. La liebre se rio a carcajadas: «¿Tú, retarme a mí? ¡Será un paseo!»</p>
<p>El zorro marcó la salida y la meta. Cuando sonó la señal, la liebre salió disparada como un rayo mientras la tortuga avanzaba despacio, paso a paso, sin detenerse nunca. Al cabo de un rato, la liebre llevaba tanta ventaja que decidió descansar bajo un árbol. «La tortuga tardará horas en llegar aquí», pensó. Se tumbó a la sombra y se quedó dormida.</p>
<p>La tortuga, mientras tanto, continuó andando sin parar, sin distraerse, con paso firme y constante. Cuando la liebre se despertó sobresaltada, ya era demasiado tarde: la tortuga estaba a punto de cruzar la meta. La liebre corrió con todas sus fuerzas, pero llegó unos segundos después. La tortuga había ganado la carrera.</p>
<p>Todos los animales aplaudieron a la tortuga. El búho, el más sabio del prado, dijo: «El verdadero ganador no es siempre el más rápido, sino el más constante.» La liebre, avergonzada, entendió la lección y desde ese día dejó de presumir tanto.</p>`,
questions:[
{type:'c', q:'¿Por qué todos los animales se cansaron de la liebre?', opts:['Porque era muy antipática con todos','Porque se pasaba el día alardeando de su velocidad','Porque hacía mucho ruido por las noches','Porque nunca ayudaba a nadie'], ans:1, exp:'La liebre se pasaba el día diciendo que nadie corría más que ella, y eso cansó a todos.'},
{type:'c', q:'¿Quién desafió a la liebre a una carrera?', opts:['El zorro','El búho','La tortuga','El ciervo'], ans:2, exp:'La tortuga, que era tranquila y constante, fue quien retó a la liebre a una carrera.'},
{type:'c', q:'¿Quién marcó la salida y la meta de la carrera?', opts:['El búho','La tortuga','El oso','El zorro'], ans:3, exp:'El texto dice que el zorro marcó la salida y la meta de la carrera.'},
{type:'c', q:'¿Qué hizo la liebre cuando llevaba mucha ventaja?', opts:['Volvió atrás para ayudar a la tortuga','Siguió corriendo sin parar hasta la meta','Se tumbó a la sombra de un árbol y se quedó dormida','Se distrajo hablando con otros animales'], ans:2, exp:'La liebre pensó que tenía tanta ventaja que podía descansar. Se tumbó bajo un árbol y se quedó dormida.'},
{type:'c', q:'¿Qué dijo el búho al final de la carrera?', opts:['Que la tortuga había hecho trampa','Que el verdadero ganador es el más constante, no el más rápido','Que había que repetir la carrera','Que la liebre debía entrenar más'], ans:1, exp:'El búho explicó que el verdadero ganador no es siempre el más rápido, sino el más constante.'},
{type:'c', q:'¿Cómo cambió la liebre tras la derrota?', opts:['Se fue a vivir a otro bosque','Prometió volver a retar a la tortuga','Dejó de presumir tanto','No cambió en absoluto'], ans:2, exp:'La liebre, avergonzada, entendió la lección y desde ese día dejó de presumir tanto.'},
{type:'f', t:'La tortuga avanzaba {0}, paso a paso, sin detenerse nunca.', blanks:['despacio'], pool:['despacio','rápido','saltando','corriendo','triste','cantando'], exp:'La tortuga avanzaba despacio pero de forma constante, sin parar nunca.'},
{type:'f', t:'La liebre se tumbó a la {0} de un árbol y se quedó {1}.', blanks:['sombra','dormida'], pool:['sombra','dormida','raíz','cansada','copa','tranquila'], exp:'La liebre se tumbó a la sombra de un árbol pensando que tenía tiempo de sobra.'},
{type:'v', q:'La liebre ganó la carrera porque era más rápida.', ans:false, exp:'Aunque la liebre era más rápida, se quedó dormida y la tortuga llegó primero a la meta.'},
{type:'v', q:'La tortuga se paró varias veces durante la carrera para descansar.', ans:false, exp:'La tortuga avanzó sin parar, sin distraerse, con paso firme y constante durante toda la carrera.'},
{type:'v', q:'La moraleja del cuento es que ser constante es más importante que ser rápido.', ans:true, exp:'El búho lo dice claramente: «el verdadero ganador no es siempre el más rápido, sino el más constante».'}
]},

{id:3, title:'El pastorcito mentiroso',
text:`<p>Había una vez un pastorcito llamado Pedro que cuidaba las ovejas del pueblo en una colina. El trabajo era tranquilo pero muy aburrido: los días pasaban lentos y sin novedad. Pedro decidió que podía gastar una broma para divertirse un poco. Se puso a gritar con todas sus fuerzas: «¡El lobo! ¡El lobo viene a comerse las ovejas!»</p>
<p>Los campesinos que trabajaban en los campos cercanos escucharon el grito y corrieron rápidamente hacia la colina con palos y herramientas para ahuyentar al lobo. Pero cuando llegaron, Pedro se reía a carcajadas. «¡Os he engañado! ¡No hay ningún lobo!» Los campesinos se fueron muy enfadados, pero perdonaron al chico.</p>
<p>Unos días después, Pedro volvió a hacer lo mismo: «¡El lobo! ¡El lobo!». Los campesinos corrieron otra vez, y otra vez Pedro se burló de ellos. Esta vez, los adultos se fueron mucho más enfadados y le advirtieron que no volviera a mentir. Pedro prometió que no lo haría.</p>
<p>Una tarde, un lobo de verdad apareció en la colina. Pedro, aterrorizado, gritó con todas sus fuerzas: «¡El lobo! ¡El lobo! ¡Es de verdad esta vez!». Pero los campesinos, pensando que era otra broma, no se movieron de sus casas. El lobo se llevó varias ovejas. Pedro aprendió la lección de la peor manera: el que miente pierde la confianza de los demás, y cuando más la necesita, nadie le cree.</p>`,
questions:[
{type:'c', q:'¿Por qué Pedro gritó «¡El lobo!» la primera vez?', opts:['Porque había visto un lobo de verdad','Para pedir ayuda a los campesinos','Para gastar una broma y divertirse','Para avisar de un peligro real'], ans:2, exp:'Pedro estaba aburrido y decidió gastar una broma gritando que venía el lobo.'},
{type:'c', q:'¿Qué hicieron los campesinos al escuchar el primer grito?', opts:['Ignoraron el aviso','Lo regañaron desde lejos','Corrieron hacia la colina con palos y herramientas','Se asomaron a la ventana a mirar'], ans:2, exp:'Los campesinos, creyendo que era real, corrieron rápidamente con palos y herramientas.'},
{type:'c', q:'¿Cuántas veces gastó Pedro la broma del lobo antes de que llegara el lobo de verdad?', opts:['Una vez','Dos veces','Tres veces','Cuatro veces'], ans:1, exp:'Pedro gastó la broma del lobo dos veces antes de que apareciera el lobo real.'},
{type:'c', q:'¿Qué pasó cuando Pedro gritó al ver el lobo de verdad?', opts:['Los campesinos corrieron inmediatamente a ayudarlo','El lobo se asustó y huyó solo','Los campesinos no le creyeron y no fueron a ayudarlo','El perro del pueblo espantó al lobo'], ans:2, exp:'Como Pedro había mentido antes, los campesinos pensaron que era otra broma y no fueron.'},
{type:'c', q:'¿Cuál es la moraleja del cuento?', opts:['Los lobos son animales muy peligrosos','El que miente pierde la confianza de los demás','Los pastores no deben gastar bromas','Los campesinos deben trabajar más'], ans:1, exp:'El texto lo dice al final: «el que miente pierde la confianza de los demás».'},
{type:'f', t:'Pedro cuidaba las {0} del pueblo en una colina.', blanks:['ovejas'], pool:['ovejas','vacas','cabras','gallinas','cerdos','caballos'], exp:'Pedro era un pastorcito que cuidaba las ovejas del pueblo.'},
{type:'f', t:'Los campesinos corrieron con palos y {0} para ahuyentar al lobo.', blanks:['herramientas'], pool:['herramientas','piedras','antorchas','redes','sacos','cestas'], exp:'Los campesinos cogieron palos y herramientas para defenderse del lobo que creían real.'},
{type:'v', q:'Pedro gritó «¡El lobo!» la primera vez porque realmente había visto uno.', ans:false, exp:'La primera vez Pedro mintió. Solo gritó para gastar una broma y divertirse.'},
{type:'v', q:'Los campesinos perdonaron a Pedro la primera vez que mintió.', ans:true, exp:'El texto dice que los campesinos se fueron enfadados pero perdonaron al chico.'},
{type:'v', q:'Cuando el lobo de verdad llegó, los campesinos corrieron a ayudar a Pedro.', ans:false, exp:'Los campesinos, cansados de las bromas, pensaron que era otra mentira y no fueron a ayudarlo.'}
]},

{id:4, title:'El patito feo',
text:`<p>En el estanque de una granja, una pata esperaba con impaciencia a que eclosionaran sus huevos. Uno a uno fueron saliendo los patitos: todos amarillos y esponjosos. Pero el último huevo, el más grande, tardó más en abrirse. Cuando por fin nació el último patito, todos quedaron asombrados: era gris, grande y torpe, muy distinto a sus hermanos.</p>
<p>Desde el primer día, el patito diferente lo pasó muy mal. Sus hermanos se reían de él y le llamaban «el patito feo». Los patos del estanque también lo rechazaban y le daban picotazos. El pobre patito estaba tan triste que decidió marcharse. Solo y asustado, se alejó del estanque y caminó durante mucho tiempo por el mundo.</p>
<p>Durante el otoño y el invierno, el patito vivió muchas dificultades. Casi se muere de frío junto a un lago helado. Un hombre bueno lo recogió y lo cuidó en su cabaña, pero el patito, al verse entre gatos y gallinas, volvió a escaparse. Pasó el invierno solo, temblando de frío, sobreviviendo como podía hasta que llegó la primavera.</p>
<p>Un día de primavera, el patito vio un grupo de cisnes blancos que volaban sobre el lago. Eran tan elegantes que se acercó a ellos, esperando que también lo rechazaran. Pero cuando se miró en el agua, no vio al patito gris y torpe de antes: vio un hermoso cisne blanco. Los otros cisnes lo rodearon con alegría. Por fin había encontrado a su verdadera familia.</p>`,
questions:[
{type:'c', q:'¿Por qué el patito era diferente a sus hermanos?', opts:['Porque llegó de otro nido','Porque nació del huevo más grande y era gris, grande y torpe','Porque no sabía nadar','Porque era mucho más pequeño que los demás'], ans:1, exp:'Todos los patitos eran amarillos y esponjosos, pero el último, nacido del huevo más grande, era gris, grande y torpe.'},
{type:'c', q:'¿Cómo trataban los otros patos al patito diferente?', opts:['Lo protegían de los peligros','Lo elegían como líder del grupo','Lo rechazaban y le daban picotazos','Lo ignoraban completamente'], ans:2, exp:'Sus hermanos se reían, los patos del estanque lo rechazaban y le daban picotazos.'},
{type:'c', q:'¿Por qué decidió marcharse el patito del estanque?', opts:['Porque quería ver mundo','Porque buscaba a sus padres','Porque estaba tan triste por el rechazo que decidió alejarse','Porque tenía hambre y no había comida'], ans:2, exp:'El patito estaba tan triste por el rechazo de todos que decidió marcharse solo.'},
{type:'c', q:'¿Cómo descubrió el patito que era un cisne?', opts:['Se lo dijo el hombre que lo cuidó','Se miró en el agua del lago','Un pájaro le dijo la verdad','Otro cisne le habló'], ans:1, exp:'Al acercarse a los cisnes y mirarse en el agua, vio que se había convertido en un hermoso cisne blanco.'},
{type:'c', q:'¿Cómo reaccionaron los cisnes cuando el patito se acercó a ellos?', opts:['Lo rechazaron como habían hecho los patos','Le dieron picotazos para alejarlo','Lo rodearon con alegría','Le preguntaron de dónde venía'], ans:2, exp:'Los cisnes lo rodearon con alegría porque era su verdadera familia.'},
{type:'f', t:'Sus hermanos le llamaban «el patito {0}» porque era muy diferente a ellos.', blanks:['feo'], pool:['feo','lento','tonto','gris','pequeño','torpe'], exp:'Sus hermanos le pusieron el apodo de «el patito feo» por su aspecto diferente.'},
{type:'f', t:'El patito pasó el {0} solo, temblando de {1}.', blanks:['invierno','frío'], pool:['invierno','frío','otoño','hambre','verano','miedo'], exp:'El texto dice que pasó el invierno solo, temblando de frío, hasta que llegó la primavera.'},
{type:'f', t:'Al mirarse en el agua, el patito vio que se había convertido en un hermoso {0} blanco.', blanks:['cisne'], pool:['cisne','pato','ganso','flamenco','garza','pelícano'], exp:'El patito descubrió su verdadera identidad al mirarse en el lago: era un cisne.'},
{type:'v', q:'El patito nació del huevo más pequeño del nido.', ans:false, exp:'El último huevo era el más grande, y de él salió el patito diferente.'},
{type:'v', q:'El patito pasó el invierno completamente solo.', ans:true, exp:'Aunque un hombre lo recogió, el patito escapó y pasó el invierno solo temblando de frío.'},
{type:'v', q:'Al final, el patito descubrió que en realidad era un cisne.', ans:true, exp:'Al mirarse en el agua del lago, vio que se había convertido en un hermoso cisne blanco.'}
]},

{id:5, title:'Pinocho',
text:`<p>Geppetto era un viejo carpintero que vivía solo y soñaba con tener un hijo. Un día talló un muñeco de madera al que llamó Pinocho. A medianoche apareció el Hada Azul y le dio vida, prometiéndole que si aprendía a ser honesto y bueno se convertiría en un niño de verdad. Le asignó a Pepito el Grillo como conciencia, pero el travieso Pinocho rara vez le hizo caso.</p>
<p>El mayor problema de Pinocho era la mentira: cada vez que decía algo falso, su nariz de madera crecía varios centímetros. Aun así, se dejó engañar por dos bribones que le prometieron riquezas. En lugar de ir a la escuela, acabó en la Isla de los Juguetes, un lugar donde los niños que solo pensaban en divertirse poco a poco se convertían en burros.</p>
<p>Aterrorizado al ver que le crecían orejas de burro, Pinocho huyó y cayó al mar. Dentro del vientre de una ballena enorme encontró a Geppetto, que llevaba semanas buscándolo y también había sido tragado. En ese momento Pinocho comprendió cuánto quería a su padre y decidió que haría lo que fuera para salvarlo.</p>
<p>Encendieron un fuego dentro de la ballena para hacerla estornudar y así escapar. Pinocho cargó a Geppetto hasta la orilla, agotado pero feliz. Esa noche el Hada Azul vio que el muñeco había demostrado verdadero valor y amor, y cumplió su promesa: Pinocho despertó convertido en un niño de verdad.</p>`,
questions:[
{type:'c', q:'¿Qué era Geppetto?', opts:['Un rey','Un sastre','Un carpintero','Un pescador'], ans:2, exp:'El texto dice que Geppetto era un viejo carpintero que soñaba con tener un hijo.'},
{type:'c', q:'¿Qué le ocurría a la nariz de Pinocho cuando mentía?', opts:['Se ponía roja','Crecía varios centímetros','Desaparecía','Cambiaba de color'], ans:1, exp:'Cada vez que Pinocho decía algo falso, su nariz de madera crecía varios centímetros.'},
{type:'c', q:'¿Qué les pasaba a los niños en la Isla de los Juguetes?', opts:['Se volvían invisibles','Se quedaban dormidos','Se convertían en burros','Ganaban superpoderes'], ans:2, exp:'En la Isla de los Juguetes, los niños que solo pensaban en divertirse se convertían en burros.'},
{type:'c', q:'¿Dónde encontró Pinocho a Geppetto?', opts:['En la escuela','En el bosque','En la Isla de los Juguetes','En el vientre de una ballena'], ans:3, exp:'Dentro del vientre de una ballena enorme, Pinocho encontró a Geppetto, que llevaba semanas buscándolo.'},
{type:'c', q:'¿Cómo escaparon Pinocho y Geppetto de la ballena?', opts:['Nadando muy rápido','Saltando por el espiráculo','Encendiendo un fuego para que la ballena estornudara','Esperando a que la ballena abriera la boca'], ans:2, exp:'Encendieron un fuego dentro de la ballena para hacerla estornudar y así escapar.'},
{type:'c', q:'¿Quién hacía de conciencia de Pinocho?', opts:['El Hada Azul','Pepito el Grillo','Geppetto','Un pez dorado'], ans:1, exp:'El Hada Azul le asignó a Pepito el Grillo como conciencia, aunque Pinocho rara vez le hizo caso.'},
{type:'f', t:'Geppetto talló un muñeco de {0} al que llamó Pinocho, y el {1} Azul le dio vida.', blanks:['madera','Hada'], pool:['madera','Hada','piedra','Mago','metal','Genio'], exp:'Geppetto talló un muñeco de madera y el Hada Azul fue quien le dio vida.'},
{type:'f', t:'Pinocho encontró a Geppetto en el vientre de una enorme {0}.', blanks:['ballena'], pool:['ballena','tortuga','medusa','tiburón','foca','orca'], exp:'Dentro del vientre de una ballena enorme encontraron a Geppetto.'},
{type:'v', q:'Al final del cuento, Pinocho se convirtió en un niño de verdad.', ans:true, exp:'El Hada Azul cumplió su promesa cuando Pinocho demostró valor y amor: lo convirtió en un niño de verdad.'},
{type:'v', q:'Pinocho siempre siguió los consejos de Pepito el Grillo.', ans:false, exp:'El texto dice que Pepito era su conciencia, pero Pinocho rara vez le hizo caso.'},
{type:'v', q:'Geppetto fue a buscar a Pinocho al mar y fue tragado por la ballena.', ans:true, exp:'Geppetto llevaba semanas buscando a su hijo y también había sido tragado por la ballena.'}
]},

{id:6, title:'La cigarra y la hormiga',
text:`<p>En un prado lleno de flores y sol, la cigarra pasaba todo el verano cantando alegremente. Su voz llenaba el aire cálido y ella no pensaba en otra cosa que en disfrutar del buen tiempo. Cerca de allí, una pequeña hormiga trabajaba sin descanso desde que amanecía hasta que oscurecía, recogiendo granos y semillas que guardaba con cuidado en su hormiguero.</p>
<p>Un día la cigarra se acercó a la hormiga con curiosidad. «¿Por qué te esfuerzas tanto bajo el sol?», le preguntó. «El campo está lleno de comida. ¡Deja el trabajo y ven a cantar conmigo!» La hormiga sacudió la cabeza sin detenerse. «Estoy preparando provisiones para el invierno. Cuando llegue el frío no habrá nada que comer.» La cigarra se rio: «¡El invierno está muy lejos! Hay tiempo para todo.»</p>
<p>Pero el verano se acabó antes de lo que la cigarra esperaba. Las hojas de los árboles cayeron, el viento se volvió gélido y la nieve cubrió los campos. La cigarra buscó comida por todas partes, pero no encontró nada. Tiritando y hambrienta, se acercó a la puerta del hormiguero y llamó con timidez.</p>
<p>La hormiga abrió y vio a la cigarra pálida y débil. Con compasión la invitó a entrar. «Puedo compartir mis provisiones contigo», dijo, «pero prométeme que el próximo verano trabajarás junto a mí.» La cigarra asintió, avergonzada. Había aprendido de la peor manera que la previsión y el esfuerzo son el mejor remedio contra las dificultades.</p>`,
questions:[
{type:'c', q:'¿Qué hacía la hormiga mientras la cigarra cantaba?', opts:['Descansaba a la sombra','Recogía granos y semillas para el invierno','Escuchaba a la cigarra con alegría','Buscaba flores para decorar su casa'], ans:1, exp:'La hormiga trabajaba sin descanso recogiendo granos y semillas que guardaba en su hormiguero.'},
{type:'c', q:'¿Por qué la hormiga no quiso unirse a la cigarra?', opts:['Porque no sabía cantar','Porque no le caía bien','Porque estaba preparando provisiones para el invierno','Porque tenía miedo al sol'], ans:2, exp:'La hormiga explicó que estaba preparando provisiones para el invierno, cuando no habría comida.'},
{type:'c', q:'¿Qué ocurrió cuando llegó el invierno?', opts:['La cigarra se fue a vivir al sur','Se quedó sin comida y fue a pedir ayuda a la hormiga','Encontró suficiente comida bajo la nieve','La hormiga le envió comida a su casa'], ans:1, exp:'La cigarra buscó comida por todas partes pero no encontró nada. Tiritando y hambrienta, fue a pedir ayuda.'},
{type:'c', q:'¿Qué condición puso la hormiga para ayudar a la cigarra?', opts:['Que le pagara con sus canciones','Que se fuera del prado en primavera','Que prometiera trabajar con ella el próximo verano','Que le contara todos sus secretos'], ans:2, exp:'La hormiga pidió que la cigarra prometiera trabajar junto a ella el próximo verano.'},
{type:'c', q:'¿Cuál es la moraleja del cuento?', opts:['Es mejor descansar que trabajar','La previsión y el esfuerzo son el mejor remedio contra las dificultades','El canto es más valioso que cualquier trabajo','Los amigos siempre se ayudan'], ans:1, exp:'El propio cuento lo dice al final: la previsión y el esfuerzo son el mejor remedio contra las dificultades.'},
{type:'f', t:'La cigarra pasaba el verano {0}, mientras la hormiga guardaba {1} para el invierno.', blanks:['cantando','provisiones'], pool:['cantando','provisiones','bailando','semillas','durmiendo','riquezas'], exp:'La cigarra cantaba y la hormiga guardaba provisiones para sobrevivir el invierno.'},
{type:'f', t:'Cuando llegó el invierno, la cigarra fue al {0} de la hormiga hambrienta y {1}.', blanks:['hormiguero','tiritando'], pool:['hormiguero','tiritando','bosque','llorando','río','corriendo'], exp:'La cigarra fue al hormiguero de la hormiga, tiritando de frío y hambrienta.'},
{type:'v', q:'La cigarra siguió el consejo de la hormiga y guardó provisiones en verano.', ans:false, exp:'La cigarra se rio del consejo de la hormiga y siguió cantando, sin guardar ninguna provisión.'},
{type:'v', q:'La hormiga dejó pasar a la cigarra y compartió su comida con ella.', ans:true, exp:'La hormiga, con compasión, invitó a la cigarra a entrar y prometió compartir sus provisiones.'},
{type:'v', q:'La moraleja es que hay que trabajar cuando es el momento oportuno.', ans:true, exp:'El cuento enseña que la previsión durante el buen tiempo prepara para las dificultades futuras.'}
]},

{id:7, title:'Aladino y la lámpara maravillosa',
text:`<p>Aladino era un joven pobre que vivía con su madre en una ciudad de Arabia. Un día un mago astuto que se hacía pasar por su tío lejano le propuso entrar en una cueva secreta para recoger una vieja lámpara. Cuando el mago intentó quitársela sin darle nada, Aladino se negó. Furioso, el mago cerró la cueva y lo dejó atrapado dentro.</p>
<p>Sin saber muy bien por qué, Aladino frotó la lámpara y de ella salió un genio enorme. «Soy el genio de la lámpara. El que me libere tiene derecho a tres deseos.» Aladino pidió salir de la cueva, comida para su madre y riquezas para vivir. Con sus nuevas posibilidades se enamoró de la princesa del sultán y, gracias al genio, logró casarse con ella y construir un palacio magnífico.</p>
<p>Pero el mago no se había olvidado de la lámpara. Disfrazado de comerciante, recorría las calles cambiando «lámparas viejas por lámparas nuevas». La princesa, sin saber el secreto, entregó la lámpara y el mago la usó para trasladar el palacio entero a África. Cuando Aladino descubrió lo ocurrido, ideó un plan para recuperarla.</p>
<p>Aladino viajó hasta África y, con ayuda de la princesa, recuperó la lámpara mientras el mago dormía. Al frotar de nuevo la lámpara, el genio apareció y devolvió el palacio a su lugar. El mago fue derrotado para siempre y Aladino aprendió que la astucia y el amor pueden vencer cualquier obstáculo.</p>`,
questions:[
{type:'c', q:'¿Qué quería el mago que hiciera Aladino?', opts:['Que le construyera un palacio','Que entrara en una cueva a recoger una lámpara','Que robara el tesoro del sultán','Que se casara con la princesa'], ans:1, exp:'El mago le pidió a Aladino que entrara en una cueva secreta para recoger una vieja lámpara.'},
{type:'c', q:'¿Por qué el mago dejó a Aladino atrapado en la cueva?', opts:['Porque Aladino rompió la lámpara','Porque no la encontró','Porque se negó a entregarle la lámpara','Porque el mago quería toda la riqueza de la cueva'], ans:2, exp:'Cuando el mago intentó quitarle la lámpara sin darle nada a cambio, Aladino se negó y el mago lo dejó atrapado.'},
{type:'c', q:'¿Cuántos deseos concedía el genio de la lámpara?', opts:['Uno','Dos','Tres','Todos los que se pidieran'], ans:2, exp:'El genio dijo claramente: «el que me libere tiene derecho a tres deseos».'},
{type:'c', q:'¿Cómo consiguió el mago hacerse con la lámpara?', opts:['Robándola por la noche','Engañando a la princesa cambiando lámparas viejas por nuevas','Comprándosela a Aladino','Usando su magia para quitársela'], ans:1, exp:'El mago se disfrazó de comerciante que ofrecía lámparas nuevas a cambio de viejas. La princesa entregó la lámpara sin saber el secreto.'},
{type:'c', q:'¿Cómo recuperó Aladino el palacio?', opts:['Construyó uno nuevo','Usó otro genio','Recuperó la lámpara mientras el mago dormía y pidió al genio que lo devolviera','El sultán ordenó al mago que lo devolviera'], ans:2, exp:'Aladino viajó a África, recuperó la lámpara mientras el mago dormía y el genio devolvió el palacio a su lugar.'},
{type:'f', t:'Aladino frotó la {0} y apareció un {1} que le concedió tres deseos.', blanks:['lámpara','genio'], pool:['lámpara','genio','caja','mago','bolsa','sultán'], exp:'Al frotar la lámpara mágica salió un genio enorme que le concedió tres deseos a Aladino.'},
{type:'f', t:'El mago se disfrazó de {0} para engañar a la princesa y quedarse con la {1}.', blanks:['comerciante','lámpara'], pool:['comerciante','lámpara','médico','alfombra','soldado','corona'], exp:'El mago se disfrazó de comerciante que cambiaba lámparas viejas por nuevas para hacerse con la lámpara mágica.'},
{type:'v', q:'Aladino era un joven rico cuando conoció al mago.', ans:false, exp:'El texto dice que Aladino era un joven pobre que vivía con su madre en una ciudad de Arabia.'},
{type:'v', q:'La princesa entregó la lámpara al mago sin saber que era mágica.', ans:true, exp:'La princesa no conocía el secreto de la lámpara y la cambió pensando que era una lámpara vieja normal.'},
{type:'v', q:'Al final, Aladino recuperó la lámpara y el palacio gracias a su astucia.', ans:true, exp:'Aladino ideó un plan ingenioso, recuperó la lámpara mientras el mago dormía y el genio devolvió el palacio.'}
]},

{id:8, title:'El flautista de Hamelín',
text:`<p>La ciudad de Hamelín tenía un grave problema: estaba invadida por ratas. Millones de ratas se colaban en las casas, comían los alimentos y asustaban a los habitantes. Los vecinos estaban desesperados y el alcalde prometió una gran recompensa a quien solucionara el problema. Un día llegó un hombre extraño vestido con un traje de colores que tocaba una flauta.</p>
<p>«Puedo librar a vuestra ciudad de todas las ratas», dijo el flautista al alcalde. «Mi música las hipnotiza.» El alcalde prometió pagarle cien monedas de oro si lo conseguía. El flautista salió a las calles y comenzó a tocar. Al instante, las ratas salieron de todos los rincones y empezaron a seguirle hipnotizadas. El flautista las condujo hasta el río y todas se ahogaron.</p>
<p>Hamelín estaba libre de ratas. Pero cuando el flautista fue a cobrar su recompensa, el alcalde se negó. «Fue demasiado fácil», dijo con descaro. «Solo tocar una flauta. No mereces cien monedas.» El flautista le advirtió que se arrepentiría, pero el alcalde lo expulsó de su despacho.</p>
<p>Esa noche el flautista volvió a las calles y tocó una melodía diferente. Esta vez, todos los niños de la ciudad salieron y lo siguieron hipnotizados hasta una colina donde desaparecieron. Los padres suplicaron al alcalde que pagara. Demasiado tarde comprendieron que las promesas deben cumplirse y que quien engaña termina pagando las consecuencias.</p>`,
questions:[
{type:'c', q:'¿Cuál era el problema de la ciudad de Hamelín?', opts:['Una terrible sequía','Una plaga de lobos','Una invasión de ratas','Un incendio'], ans:2, exp:'La ciudad estaba invadida por millones de ratas que comían los alimentos y asustaban a los habitantes.'},
{type:'c', q:'¿Qué prometió el alcalde al flautista?', opts:['El cargo de alcalde','Cien monedas de oro','Una casa en la ciudad','La mano de su hija'], ans:1, exp:'El alcalde prometió pagarle cien monedas de oro si conseguía librar a la ciudad de todas las ratas.'},
{type:'c', q:'¿Cómo hizo el flautista para que las ratas lo siguieran?', opts:['Les puso comida en el camino','Tocó su flauta, cuya melodía las hipnotizaba','Las atrapó con una red gigante','Les habló en el idioma de las ratas'], ans:1, exp:'El flautista tocó su flauta y las ratas salieron hipnotizadas por la melodía, siguiéndole hasta el río.'},
{type:'c', q:'¿Por qué el alcalde no pagó al flautista?', opts:['Porque la ciudad no tenía dinero','Porque las ratas volvieron','Porque le pareció que el trabajo había sido demasiado fácil','Porque el flautista no había cumplido el trato'], ans:2, exp:'El alcalde dijo que tocar una flauta era demasiado fácil y se negó a pagar las cien monedas prometidas.'},
{type:'c', q:'¿Qué hizo el flautista al no cobrar su recompensa?', opts:['Se fue de la ciudad sin decir nada','Llamó más ratas','Tocó otra melodía que hizo seguirle a todos los niños','Fue a hablar con el rey'], ans:2, exp:'El flautista tocó una melodía diferente y todos los niños de Hamelín lo siguieron hipnotizados hasta una colina.'},
{type:'f', t:'El flautista tocó su {0} y las ratas lo siguieron hipnotizadas hasta el {1}.', blanks:['flauta','río'], pool:['flauta','río','tambor','lago','violín','bosque'], exp:'La música de la flauta hipnotizaba a las ratas y el flautista las condujo hasta el río.'},
{type:'f', t:'El alcalde se negó a pagar la {0} prometida porque le pareció un trabajo demasiado {1}.', blanks:['recompensa','fácil'], pool:['recompensa','fácil','deuda','difícil','promesa','caro'], exp:'El alcalde dijo que tocar una flauta era demasiado fácil y se negó a dar la recompensa.'},
{type:'v', q:'El alcalde pagó al flautista las cien monedas de oro prometidas.', ans:false, exp:'El alcalde se negó a pagar, diciendo que el trabajo había sido demasiado fácil.'},
{type:'v', q:'El flautista consiguió eliminar todas las ratas de Hamelín tocando su flauta.', ans:true, exp:'La melodía hipnotizó a las ratas y el flautista las condujo hasta el río, donde se ahogaron.'},
{type:'v', q:'La moraleja del cuento es que las promesas deben cumplirse siempre.', ans:true, exp:'Al final, los vecinos comprendieron demasiado tarde que las promesas deben cumplirse y que engañar tiene consecuencias.'}
]},

{id:9, title:'Juan y los frijoles mágicos',
text:`<p>Juan vivía con su madre en una cabaña humilde. Un día su madre le pidió que vendiera su vaca para comprar comida. En el camino al mercado, Juan se encontró con un anciano que le ofreció cinco frijoles a cambio de la vaca, asegurando que eran mágicos. Juan aceptó. Cuando llegó a casa sin dinero y solo con cinco frijoles, su madre se enfadó tanto que los lanzó por la ventana.</p>
<p>A la mañana siguiente, de los frijoles había crecido una planta gigantesca que llegaba hasta las nubes. Juan empezó a trepar por el tallo. Al llegar arriba encontró un inmenso castillo. Hambriento, llamó a la puerta. Una giganta amable le ofreció comida, pero le advirtió: «¡Cuidado! Mi marido, el gigante, huele a los humanos y es muy peligroso.»</p>
<p>Antes de que Juan pudiera escapar, el gigante llegó a casa gritando: «¡Huelo sangre de ser humano!» Juan se escondió rápidamente. Mientras el gigante contaba sus monedas y dormitaba, Juan le robó una gallina que ponía huevos de oro y un arpa que tocaba sola. El gigante se despertó con el ruido y empezó a perseguirle.</p>
<p>Juan bajó por el tallo lo más rápido que pudo, gritando a su madre que le trajera un hacha. Cuando llegó al suelo, cortó el tallo con golpes certeros. El gigante cayó desde las alturas y nunca más volvió a amenazarlos. Con la gallina que ponía huevos de oro, Juan y su madre vivieron cómodamente para siempre.</p>`,
questions:[
{type:'c', q:'¿Por qué la madre de Juan le pidió que vendiera la vaca?', opts:['Para comprar semillas','Para pagar deudas','Para comprar comida','Para comprar una casa más grande'], ans:2, exp:'La madre le pidió que vendiera la vaca para comprar comida, pues vivían en una cabaña humilde.'},
{type:'c', q:'¿Qué le dio el anciano a Juan a cambio de la vaca?', opts:['Diez monedas de oro','Cinco frijoles mágicos','Un mapa con un tesoro','Tres deseos'], ans:1, exp:'El anciano le ofreció cinco frijoles mágicos a cambio de la vaca y Juan aceptó el trato.'},
{type:'c', q:'¿Qué encontró Juan al llegar a lo alto de la planta de frijoles?', opts:['Un jardín lleno de tesoros','Un inmenso castillo en las nubes','El país de las hadas','La casa de un mago'], ans:1, exp:'Al trepar por el tallo hasta las nubes, Juan encontró un inmenso castillo donde vivía un gigante.'},
{type:'c', q:'¿Qué robó Juan del castillo del gigante?', opts:['Monedas de oro y una espada','Una gallina de huevos de oro y un arpa que tocaba sola','Un cofre de joyas y una alfombra voladora','La corona del gigante'], ans:1, exp:'Juan aprovechó que el gigante dormitaba para robarle una gallina que ponía huevos de oro y un arpa que tocaba sola.'},
{type:'c', q:'¿Cómo se deshizo Juan del gigante?', opts:['Lo encerró en el castillo','Lo convenció de que se fuera','Cortó el tallo de la planta cuando el gigante bajaba por él','Lo atrapó con una red mágica'], ans:2, exp:'Juan bajó rápido y, con un hacha, cortó el tallo de la planta. El gigante cayó desde las alturas.'},
{type:'f', t:'De los cinco {0} mágicos creció una planta enorme que llegaba hasta las {1}.', blanks:['frijoles','nubes'], pool:['frijoles','nubes','semillas','estrellas','flores','montañas'], exp:'Los frijoles mágicos crecieron durante la noche hasta llegar a las nubes.'},
{type:'f', t:'Juan robó una {0} que ponía huevos de oro y un {1} que tocaba sola.', blanks:['gallina','arpa'], pool:['gallina','arpa','pata','violín','oca','tambor'], exp:'Juan aprovechó que el gigante dormitaba para robarle esos dos objetos mágicos.'},
{type:'v', q:'La madre de Juan se alegró cuando él volvió con los cinco frijoles.', ans:false, exp:'La madre se enfadó tanto que lanzó los frijoles por la ventana.'},
{type:'v', q:'La esposa del gigante avisó a Juan del peligro que corría.', ans:true, exp:'La giganta le abrió la puerta y le advirtió que su marido olía a los humanos y era muy peligroso.'},
{type:'v', q:'Con la gallina de los huevos de oro, Juan y su madre vivieron cómodamente.', ans:true, exp:'Con la gallina que ponía huevos de oro tuvieron suficiente riqueza para siempre.'}
]},

{id:10, title:'La bella durmiente',
text:`<p>Cuando nació la princesa Aurora, el rey y la reina invitaron a todas las hadas del reino a un gran banquete para que le concedieran dones. Las hadas le regalaron belleza, bondad y gracia. Pero había una hada malvada que no había sido invitada y llegó furiosa. «¡Mi regalo es una maldición!», exclamó. «Al cumplir dieciséis años, se pinchará con el huso de una rueca y caerá en un sueño eterno.»</p>
<p>El rey ordenó destruir todas las ruecas del reino. Aurora creció alegre y querida. Pero el día de su decimosexto cumpleaños, encontró en una torre olvidada a una anciana que hilaba. Sin saber lo que era, Aurora tocó la rueca y se pinchó el dedo. Al instante cayó dormida. Las hadas, para que no estuviera sola al despertar, hicieron dormir a todo el reino.</p>
<p>Alrededor del castillo creció un espeso bosque de espinos que nadie podía atravesar. Durante cien años el castillo durmió en silencio. Los pájaros no cantaban, el viento no soplaba y el tiempo parecía detenido. Muchos príncipes intentaron llegar atraídos por la leyenda, pero ninguno logró cruzar el bosque.</p>
<p>Pasados exactamente cien años llegó un joven príncipe. Al acercarse, el bosque se abrió ante él como si lo esperara. Entró al castillo, encontró a la bella Aurora y la besó con ternura. La princesa abrió los ojos, y con ella despertó todo el reino. La maldición se había roto. El príncipe y Aurora se enamoraron y celebraron una gran boda.</p>`,
questions:[
{type:'c', q:'¿Qué maldición lanzó el hada malvada sobre Aurora?', opts:['Que nunca fuera feliz','Que al cumplir dieciséis años se pincharía con una rueca y caería en sueño eterno','Que se volvería invisible','Que perdería su belleza'], ans:1, exp:'El hada malvada maldijo que al cumplir dieciséis años Aurora se pincharía con el huso de una rueca y caería en un sueño eterno.'},
{type:'c', q:'¿Qué ordenó el rey para proteger a Aurora?', opts:['Encerrar a Aurora en una torre','Destruir todas las ruecas del reino','Contratar guardias día y noche','Buscar y encerrar al hada malvada'], ans:1, exp:'El rey ordenó destruir todas las ruecas del reino para que Aurora no pudiera pincharse con ningún huso.'},
{type:'c', q:'¿Dónde encontró Aurora la rueca que la hizo dormir?', opts:['En el jardín real','En la habitación de la reina','En una torre olvidada del castillo','En el bosque cercano'], ans:2, exp:'El día de su decimosexto cumpleaños, Aurora encontró en una torre olvidada a una anciana que hilaba.'},
{type:'c', q:'¿Por qué las hadas hicieron dormir a todo el reino?', opts:['Porque les pareció divertido','Para castigar al rey','Para que Aurora no estuviera sola cuando despertara','Porque el hada malvada las obligó'], ans:2, exp:'Las hadas hicieron dormir a todo el reino para que Aurora no estuviera sola al despertar.'},
{type:'c', q:'¿Cómo se rompió la maldición?', opts:['Una hada lanzó un contra-hechizo','Un médico preparó una poción','El príncipe encontró a Aurora y la besó con ternura','Aurora se despertó sola al pasar cien años'], ans:2, exp:'El príncipe encontró a la bella Aurora y la besó con ternura. Ella abrió los ojos y todo el castillo despertó.'},
{type:'f', t:'La maldición decía que Aurora se pincharía con el {0} de una {1} al cumplir dieciséis años.', blanks:['huso','rueca'], pool:['huso','rueca','peine','aguja','cuchillo','tijera'], exp:'El hada malvada maldijo que Aurora se pincharía con el huso de una rueca.'},
{type:'f', t:'Alrededor del castillo creció un espeso bosque de {0} que nadie podía {1}.', blanks:['espinos','atravesar'], pool:['espinos','atravesar','rosas','escalar','árboles','cruzar'], exp:'El bosque de espinos protegió el castillo durante cien años y nadie logró atravesarlo.'},
{type:'v', q:'Todas las hadas del reino fueron invitadas al banquete de nacimiento de Aurora.', ans:false, exp:'El hada malvada no fue invitada y llegó furiosa al banquete para lanzar su maldición.'},
{type:'v', q:'Aurora pasó cien años dormida en el castillo junto con todos sus habitantes.', ans:true, exp:'Las hadas hicieron dormir a todo el reino para que Aurora no estuviera sola, y así durmieron cien años.'},
{type:'v', q:'El príncipe tuvo que luchar contra el bosque de espinos para llegar al castillo.', ans:false, exp:'El bosque se abrió ante el príncipe como si lo esperara, sin que tuviera que luchar.'}
]},

{id:11, title:'El gato con botas',
text:`<p>Cuando un viejo molinero murió, dejó a sus tres hijos como herencia: al mayor el molino, al mediano el burro y al pequeño solo un gato. El joven estaba muy triste pensando que no tenía nada de valor. Pero el gato le dijo: «No te preocupes, amo. Dame unas botas y una bolsa y te haré más rico de lo que imaginas.» El joven aceptó.</p>
<p>El gato se calzó las botas, salió al campo y empezó a cazar conejos y perdices. Cada vez que atrapaba algo, lo llevaba al rey en nombre de su amo, al que llamó «el Marqués de Carabás». El rey quedó encantado con los regalos y pronto quiso conocer a ese misterioso marqués. El gato preparó un plan: hizo que su amo se bañara en el río justo cuando el carruaje del rey pasara.</p>
<p>El gato gritó que el Marqués de Carabás se había ahogado y que ladrones le habían robado la ropa. El rey ordenó darle ropa elegante y lo invitó a subir al carruaje. El gato corrió adelante y convenció a los campesinos de decir al rey que todas aquellas tierras eran del Marqués de Carabás.</p>
<p>El gato llegó a un castillo habitado por un ogro que podía transformarse en cualquier animal. El gato lo retó: «Dicen que puedes convertirte en un ratón, ¡no me lo creo!» El ogro, picado en su orgullo, se transformó en ratón. El gato lo atrapó y se lo comió. Así el castillo quedó libre, el joven se casó con la princesa y el gato fue tratado como un noble el resto de su vida.</p>`,
questions:[
{type:'c', q:'¿Qué heredó el hijo menor del molinero?', opts:['El molino','El burro','Solo un gato','Nada en absoluto'], ans:2, exp:'El mayor heredó el molino, el mediano el burro y el pequeño únicamente un gato.'},
{type:'c', q:'¿Con qué nombre presentaba el gato a su amo ante el rey?', opts:['El Conde de las Botas','El Príncipe del Molino','El Marqués de Carabás','El Barón del Bosque'], ans:2, exp:'El gato llamaba a su amo «el Marqués de Carabás» al llevar los regalos al rey.'},
{type:'c', q:'¿Qué truco usó el gato para que el rey invitara a su amo al carruaje?', opts:['Dijo que el marqués había salvado la vida al rey','Fingió que el marqués se había ahogado y que le robaron la ropa','Organizó un banquete en honor del rey','Regaló al rey una bolsa de monedas'], ans:1, exp:'El gato gritó que su amo se había ahogado y que ladrones le robaron la ropa, así el rey le dio ropa y lo invitó al carruaje.'},
{type:'c', q:'¿Cómo derrotó el gato al ogro del castillo?', opts:['Lo retó a una pelea','Lo encerró en el sótano','Lo engañó para que se transformara en ratón y se lo comió','Le robó el objeto que le daba su poder'], ans:2, exp:'El gato retó al ogro a transformarse en un ratón. Cuando lo hizo, el gato lo atrapó y se lo comió.'},
{type:'c', q:'¿Cuál fue la recompensa del gato al final del cuento?', opts:['Recibió la mitad del castillo','Fue tratado como un noble el resto de su vida','Se convirtió en el nuevo rey','Se convirtió en persona'], ans:1, exp:'Al final del cuento el joven se casó con la princesa y el gato fue tratado como un noble el resto de su vida.'},
{type:'f', t:'El gato pidió unas {0} y una {1} para hacer rico a su amo.', blanks:['botas','bolsa'], pool:['botas','bolsa','capas','cesta','espadas','red'], exp:'El gato pidió botas para caminar y una bolsa para cazar animales y llevarlos al rey como regalo.'},
{type:'f', t:'El gato retó al ogro a convertirse en un {0} y, cuando lo hizo, se lo {1}.', blanks:['ratón','comió'], pool:['ratón','comió','conejo','atrapó','pájaro','persiguió'], exp:'El gato engañó al ogro con su orgullo: cuando se transformó en ratón, el gato lo atrapó y se lo comió.'},
{type:'v', q:'El hijo menor estaba contento con la herencia de su padre.', ans:false, exp:'El joven estaba muy triste pensando que no tenía nada de valor, ya que solo había heredado un gato.'},
{type:'v', q:'El gato convenció a los campesinos de decir que las tierras eran del Marqués de Carabás.', ans:true, exp:'El gato corrió adelante del carruaje real y convenció a los campesinos para que dijeran que esas tierras eran de su amo.'},
{type:'v', q:'El ogro del castillo podía transformarse en cualquier animal.', ans:true, exp:'El texto dice que el castillo estaba habitado por un ogro que podía transformarse en cualquier animal.'}
]},

{id:12, title:'El traje nuevo del rey',
text:`<p>Había una vez un rey tan aficionado a los trajes elegantes que gastaba todo su dinero en ropa. Un día llegaron a la ciudad dos pícaros que se hacían pasar por tejedores y prometieron al rey una tela prodigiosa. Según ellos, esa tela era invisible para las personas estúpidas o incapaces de hacer bien su trabajo. Al rey le pareció una idea perfecta para descubrir quién era tonto en su reino.</p>
<p>Los dos estafadores se instalaron en el palacio con telares y pidieron hilo de oro y seda de los más finos. Pero no tejían nada: se lo quedaban todo para sí mismos. Cuando el rey mandó a sus ministros a inspeccionar el trabajo, ninguno vio absolutamente nada. Sin embargo, para no parecer estúpidos, todos dijeron que la tela era preciosa y de colores maravillosos.</p>
<p>Al final los pícaros dijeron que el traje estaba listo y «vistieron» al rey sin ropa. El rey tampoco vio la tela, pero no quiso admitirlo. Así que salió en solemne desfile por las calles con la convicción de lucir el traje más espléndido del mundo. La gente, que tampoco se atrevía a decir la verdad, aplaudía y alababa el traje invisible.</p>
<p>De repente, un niño pequeño que no entendía de adultos ni de apariencias, gritó sin ningún reparo: «¡El rey va desnudo!» Sus palabras corrieron de boca en boca y toda la multitud empezó a reír. El rey sintió que era verdad, pero siguió caminando muy erguido, aprendiendo de la manera más ridícula posible que la vanidad tiene un precio.</p>`,
questions:[
{type:'c', q:'¿Por qué el rey quería la tela mágica?', opts:['Para venderla y ganar dinero','Para descubrir quién era tonto en su reino','Para regalarla a la reina','Para hacer cortinas en el palacio'], ans:1, exp:'Al rey le pareció perfecto: si la tela solo la veían los inteligentes, podría descubrir quién era estúpido o incapaz.'},
{type:'c', q:'¿Qué hacían realmente los dos tejedores con el hilo de oro y la seda?', opts:['Tejían la tela muy despacio','Se lo quedaban todo para sí mismos','Lo vendían en el mercado','Lo guardaban para el rey'], ans:1, exp:'Los estafadores no tejían nada: se quedaban con todos los materiales preciosos para sí mismos.'},
{type:'c', q:'¿Por qué los ministros dijeron que la tela era preciosa si no veían nada?', opts:['Porque realmente la veían','Para no parecer estúpidos ante el rey','Porque les sobornaron los tejedores','Porque el rey les ordenó decirlo'], ans:1, exp:'Ningún ministro quería admitir que no veía la tela, para no parecer estúpido o incapaz.'},
{type:'c', q:'¿Quién reveló la verdad sobre el traje del rey?', opts:['Un ministro honesto','La reina','Un niño pequeño','Un soldado de la guardia'], ans:2, exp:'Un niño pequeño, sin miedo ni pretensiones, gritó que el rey iba desnudo.'},
{type:'c', q:'¿Qué lección enseña este cuento?', opts:['Los trajes elegantes son los mejores','La vanidad puede hacernos ridículos','Siempre hay que obedecer al rey','Los niños no deben hablar con adultos'], ans:1, exp:'El cuento muestra que la vanidad del rey lo llevó a una situación ridícula ante todo su pueblo.'},
{type:'f', t:'Los dos pícaros prometieron al rey una tela invisible para los {0} o los {1}.', blanks:['estúpidos','incapaces'], pool:['estúpidos','incapaces','ricos','pobres','jóvenes','valientes'], exp:'Según los estafadores, la tela solo era invisible para las personas estúpidas o incapaces de hacer bien su trabajo.'},
{type:'f', t:'Un {0} pequeño gritó que el rey iba {1}, y sus palabras corrieron de boca en boca.', blanks:['niño','desnudo'], pool:['niño','desnudo','anciano','solo','soldado','descalzo'], exp:'Un niño sin miedo a las convenciones fue el único que dijo la verdad en voz alta.'},
{type:'v', q:'Los tejedores fabricaron realmente una tela muy fina y transparente.', ans:false, exp:'Los tejedores eran estafadores y no tejían nada; solo fingían trabajar.'},
{type:'v', q:'Todo el pueblo aplaudió el traje antes de que el niño dijera la verdad.', ans:true, exp:'La gente tampoco se atrevía a decir que no veían nada y aplaudían alabando el traje invisible.'},
{type:'v', q:'Al final el rey reconoció abiertamente que lo habían engañado y se enfadó.', ans:false, exp:'El rey sintió que era verdad pero siguió caminando muy erguido, sin admitirlo públicamente.'}
]},

{id:13, title:'La gallina de los huevos de oro',
text:`<p>Había una vez un granjero y su mujer que tenían una gallina muy especial. Cada mañana, cuando se acercaban al gallinero, encontraban un huevo de oro puro. Los vendían en el mercado y poco a poco se fueron haciendo ricos. La gallina era su mayor tesoro y la cuidaban con mucho mimo.</p>
<p>Al principio el matrimonio estaba feliz con un huevo de oro cada día. Pero con el tiempo empezaron a pensar que si la gallina tenía huevos de oro por dentro, podrían hacerse riquísimos de golpe. «¿Para qué esperar un huevo al día?», dijo el granjero, «¡dentro de ella debe haber muchos!» Su mujer asintió, convencida.</p>
<p>Un día, sin poder resistir la codicia, el granjero tomó un cuchillo y mató a la gallina. Pero al abrirla descubrieron que por dentro era una gallina completamente normal. No había ningún huevo de oro en su interior. Habían sacrificado la fuente de toda su riqueza por la avaricia.</p>
<p>Desde ese día, el granjero y su mujer tuvieron que volver a trabajar duramente como antes. Ya no había gallina, ni huevos de oro, ni riquezas fáciles. Aprendieron de la peor manera posible que la codicia es la peor consejera y que quien tiene algo bueno debe cuidarlo y valorarlo antes de perderlo para siempre.</p>`,
questions:[
{type:'c', q:'¿Qué encontraban el granjero y su mujer cada mañana en el gallinero?', opts:['Un pollo asado','Un cofre de monedas','Un huevo de oro','Varios huevos normales'], ans:2, exp:'Cada mañana la gallina ponía un huevo de oro que luego vendían en el mercado para hacerse ricos.'},
{type:'c', q:'¿Qué pensaron el granjero y su mujer que había dentro de la gallina?', opts:['Muchos huevos de oro','Un tesoro escondido','Una piedra preciosa','Nada especial'], ans:0, exp:'Pensaron que si la gallina ponía huevos de oro, dentro de ella debía haber muchos más huevos de oro.'},
{type:'c', q:'¿Qué encontraron dentro de la gallina cuando la abrieron?', opts:['Muchos huevos de oro','Una piedra mágica','Que era una gallina completamente normal','Monedas de plata'], ans:2, exp:'Al abrirla descubrieron que era una gallina normal por dentro, sin ningún huevo de oro.'},
{type:'c', q:'¿Qué lección principal enseña esta fábula?', opts:['Hay que comer bien para estar sano','La codicia puede hacernos perder lo que tenemos','Los granjeros son muy codiciosos','El oro siempre trae problemas'], ans:1, exp:'El cuento enseña que la codicia lleva a perder lo que ya se tiene, como le pasó al granjero con su gallina.'},
{type:'c', q:'¿Cómo se habían hecho ricos el granjero y su mujer?', opts:['Trabajando mucho en el campo','Vendiendo los huevos de oro en el mercado','Ganando un premio','Heredando de un familiar'], ans:1, exp:'Vendían cada huevo de oro en el mercado y poco a poco se fueron haciendo ricos gracias a la gallina.'},
{type:'f', t:'El granjero no quiso esperar un {0} al día y mató a la gallina por {1}.', blanks:['huevo','codicia'], pool:['huevo','codicia','mes','hambre','año','miedo'], exp:'La codicia de querer toda la riqueza de golpe llevó al granjero a cometer el error de matar a la gallina.'},
{type:'f', t:'Desde ese día tuvieron que volver a {0} duramente como {1}.', blanks:['trabajar','antes'], pool:['trabajar','antes','robar','siempre','viajar','después'], exp:'Sin la gallina, perdieron su fuente de ingresos y tuvieron que trabajar duro como hacían antes de tenerla.'},
{type:'v', q:'La gallina ponía un huevo de oro cada semana.', ans:false, exp:'La gallina ponía un huevo de oro cada mañana, es decir, uno al día.'},
{type:'v', q:'Dentro de la gallina había un montón de huevos de oro.', ans:false, exp:'Al abrirla descubrieron que era normal por dentro: no había ningún huevo de oro.'},
{type:'v', q:'El cuento nos enseña que hay que valorar lo que uno tiene.', ans:true, exp:'La moraleja es que quien tiene algo bueno debe cuidarlo y valorarlo antes de perderlo para siempre.'}
]},

{id:14, title:'Rapunzel',
text:`<p>Había una vez una pareja que vivía cerca de un jardín rodeado de un alto muro que pertenecía a una bruja. La mujer estaba embarazada y tenía un antojo tan fuerte de una planta que crecía en ese jardín, llamada rapunzel, que enfermó. Su marido, desesperado, se coló en el jardín a robar un poco. La bruja lo atrapó y él, asustado, prometió darle el bebé cuando naciera.</p>
<p>Cuando nació la niña, la bruja se la llevó y la llamó Rapunzel. Era muy hermosa y tenía una cabellera larga y dorada. Cuando Rapunzel cumplió doce años, la bruja la encerró en una torre altísima sin puertas ni escaleras, con solo una pequeña ventana en lo alto. Cada vez que la bruja quería subir, gritaba: «¡Rapunzel, Rapunzel, suelta tu cabello!» y Rapunzel dejaba caer su larga trenza dorada para que la bruja trepara.</p>
<p>Un día un príncipe que cabalgaba por el bosque oyó la hermosa voz de Rapunzel cantando. Observó cómo subía la bruja y repitió las mismas palabras. Rapunzel, sorprendida, dejó caer su trenza. El príncipe subió, se enamoraron y planearon escapar. Pero la bruja los descubrió. Enfurecida, cortó la trenza de Rapunzel y la desterró a un desierto lejano.</p>
<p>El príncipe, al llegar y ver solo a la bruja, cayó de la torre y quedó ciego entre los espinos. Vagó durante años llamando a Rapunzel hasta que la encontró en el desierto. Las lágrimas de ella cayeron sobre los ojos del príncipe y este recuperó la vista. Se abrazaron y regresaron juntos al reino, donde vivieron felices para siempre.</p>`,
questions:[
{type:'c', q:'¿Por qué el padre de Rapunzel entró en el jardín de la bruja?', opts:['Para robar flores para su mujer','Porque su mujer tenía antojo de la planta rapunzel que allí crecía','Para explorar el jardín abandonado','Para vender verduras a la bruja'], ans:1, exp:'Su mujer embarazada tenía un antojo tan fuerte de la planta rapunzel que enfermó, y él entró a robarla desesperado.'},
{type:'c', q:'¿Cómo subía la bruja a la torre donde vivía Rapunzel?', opts:['Con una escalera de cuerda','Por una puerta secreta','Trepando por la larga trenza de Rapunzel','Usando magia para volar'], ans:2, exp:'La bruja gritaba a Rapunzel que soltara su cabello y trepaba por la larga trenza dorada.'},
{type:'c', q:'¿Qué hizo la bruja cuando descubrió al príncipe?', opts:['Lo encerró en la torre','Cortó la trenza de Rapunzel y la desterró lejos','Lo convirtió en animal','Los perdonó a ambos'], ans:1, exp:'La bruja, furiosa, cortó la trenza de Rapunzel y la desterró a un desierto lejano.'},
{type:'c', q:'¿Cómo recuperó el príncipe la vista?', opts:['Un hada lo curó','Las lágrimas de Rapunzel cayeron sobre sus ojos','Encontró una poción mágica','La bruja se arrepintió y lo curó'], ans:1, exp:'Las lágrimas de Rapunzel, al caer sobre los ojos del príncipe, le devolvieron la vista milagrosamente.'},
{type:'c', q:'¿Dónde encontró el príncipe a Rapunzel después de quedar ciego?', opts:['En la torre','En el palacio real','En el bosque donde se conocieron','En el desierto donde la bruja la había desterrado'], ans:3, exp:'El príncipe vagó años llamando a Rapunzel hasta que la encontró en el desierto lejano donde la bruja la desterró.'},
{type:'f', t:'La bruja gritaba «¡Rapunzel, Rapunzel, suelta tu {0}!» para que ella dejara caer su larga {1}.', blanks:['cabello','trenza'], pool:['cabello','trenza','capa','soga','pelo','manta'], exp:'La bruja trepaba a la torre usando la larga trenza dorada de Rapunzel como si fuera una cuerda.'},
{type:'f', t:'El príncipe quedó {0} al caer de la torre entre los {1}.', blanks:['ciego','espinos'], pool:['ciego','espinos','dormido','árboles','herido','arbustos'], exp:'Al ver solo a la bruja y darse cuenta de que Rapunzel había desaparecido, el príncipe cayó y quedó ciego entre los espinos.'},
{type:'v', q:'Rapunzel fue encerrada en la torre porque hizo algo malo.', ans:false, exp:'La bruja la encerró cuando cumplió doce años para tenerla para ella sola, no como castigo.'},
{type:'v', q:'El príncipe escuchó la voz de Rapunzel cantando y así descubrió la torre.', ans:true, exp:'Cabalgando por el bosque, el príncipe oyó la hermosa voz de Rapunzel cantando desde la torre.'},
{type:'v', q:'Al final Rapunzel y el príncipe regresaron juntos al reino.', ans:true, exp:'Tras la curación del príncipe con las lágrimas de Rapunzel, ambos regresaron juntos al reino.'}
]},

{id:15, title:'La zorra y las uvas',
text:`<p>Era una tarde de verano calurosa y seca. Una zorra caminaba por el campo buscando algo para comer, pues llevaba muchas horas sin probar bocado. De repente vio entre los árboles una vid cargada de hermosos racimos de uvas maduras que colgaban tentadores. Eran uvas de color morado oscuro, gordas y brillantes, que parecían dulcísimas.</p>
<p>La zorra se relamió de gusto solo de mirarlas. Se acercó y probó a saltar para alcanzarlas. Pero las uvas colgaban demasiado altas y no las alcanzó. Lo intentó una segunda vez, tomando más carrerilla, pero tampoco. Una tercera vez saltó con toda su energía… y nada. Las uvas seguían allí, relucientes e inalcanzables.</p>
<p>La zorra, exhausta y frustrada, se sentó un momento a recuperar el aliento. Miraba los racimos con rabia. No quería admitir que simplemente no podía llegar a ellos. Así que después de mucho pensar, se dio la vuelta y se alejó con la cabeza bien alta.</p>
<p>Mientras se marchaba, murmuró para sí misma: «Total, esas uvas estaban verdes. Seguro que estaban agrias y me habrían puesto mala.» Pero en el fondo sabía que no era verdad. Los demás animales del campo que la oyeron entendieron bien la lección: cuando no podemos conseguir algo, no debemos engañarnos a nosotros mismos diciéndonos que tampoco lo queríamos.</p>`,
questions:[
{type:'c', q:'¿Qué buscaba la zorra cuando vio las uvas?', opts:['Un lugar para descansar','Agua para beber','Algo para comer','Compañía de otros animales'], ans:2, exp:'La zorra llevaba muchas horas sin probar bocado y caminaba por el campo buscando algo para comer.'},
{type:'c', q:'¿Por qué la zorra no pudo coger las uvas?', opts:['Porque había otro animal protegiéndolas','Porque tenía miedo a la vid','Porque colgaban demasiado altas','Porque estaban rodeadas de espinos'], ans:2, exp:'Las uvas colgaban demasiado altas y la zorra no podía alcanzarlas aunque saltó varias veces.'},
{type:'c', q:'¿Cuántas veces intentó la zorra saltar para alcanzar las uvas?', opts:['Una vez','Dos veces','Tres veces','Cuatro veces'], ans:2, exp:'La zorra intentó saltar tres veces: la primera, una segunda con más carrerilla, y una tercera con toda su energía.'},
{type:'c', q:'¿Qué dijo la zorra al marcharse sin las uvas?', opts:['Que volvería otro día con una escalera','Que las uvas estaban verdes y agrias','Que prefería comer otra cosa','Que pediría ayuda a alguien más alto'], ans:1, exp:'La zorra dijo que las uvas seguramente estaban verdes y agrias, para justificar que no las quería.'},
{type:'c', q:'¿Cuál es la moraleja de esta fábula?', opts:['Las uvas son difíciles de coger','No debemos engañarnos diciendo que no queremos lo que no podemos conseguir','Los zorros no saben saltar','El verano es la mejor época para buscar fruta'], ans:1, exp:'La moraleja es que no debemos autoengañarnos diciendo que no queríamos algo que simplemente no pudimos conseguir.'},
{type:'f', t:'La zorra vio unos racimos de uvas {0} y brillantes que parecían muy {1}.', blanks:['gordas','dulces'], pool:['gordas','dulces','pequeñas','agrias','verdes','amargas'], exp:'Las uvas eran de color morado oscuro, gordas y brillantes, y parecían dulcísimas y tentadoras.'},
{type:'f', t:'Al marcharse, la zorra dijo que las uvas estarían {0} y le habrían puesto {1}.', blanks:['agrias','mala'], pool:['agrias','mala','verdes','enferma','duras','triste'], exp:'Para no admitir su fracaso, la zorra inventó que las uvas estaban agrias y que le habrían sentado mal.'},
{type:'v', q:'La zorra consiguió alcanzar las uvas a la tercera vez que saltó.', ans:false, exp:'Saltó tres veces pero no alcanzó las uvas en ningún intento porque colgaban demasiado alto.'},
{type:'v', q:'En el fondo, la zorra sabía que lo que dijo de las uvas no era verdad.', ans:true, exp:'El texto dice que en el fondo la zorra sabía que no era verdad lo que decía de las uvas.'},
{type:'v', q:'Los demás animales entendieron la lección de la fábula.', ans:true, exp:'Los animales del campo que la oyeron entendieron bien la moraleja sobre el autoengaño.'}
]},

{id:16, title:'El ratón de ciudad y el ratón de campo',
text:`<p>Un ratón que vivía en el campo recibió un día la visita de su primo, que vivía en la gran ciudad. El ratón de campo lo recibió con mucha alegría y le ofreció todo lo que tenía: semillas, bellotas, trigo y agua fresca del arroyo. La cena era sencilla pero abundante. Sin embargo, el ratón de ciudad la probó con cara de asco.</p>
<p>«Primo», dijo el ratón de ciudad, «¿cómo puedes vivir así? En la ciudad tenemos quesos, pasteles, jamón, chocolate y manjares de todo tipo. Debes venir a visitarme y ver cómo se vive de verdad.» El ratón de campo, curioso, aceptó la invitación y se marchó con su primo a la ciudad.</p>
<p>Llegaron de noche a una casa enorme. Cuando los dueños se fueron a dormir, los dos ratones entraron a la despensa. Allí había quesos, embutidos, pastas y dulces de todo tipo. El ratón de campo nunca había visto tanta comida junta. Empezó a comer entusiasmado, admirado por tanta abundancia.</p>
<p>Pero de repente apareció un enorme gato. Los dos ratones huyeron despavoridos y se escondieron en un pequeño agujero temblando de miedo. Cuando por fin el gato se marchó, el ratón de campo dijo: «Primo, gracias por la invitación, pero prefiero volver a mi campo. Allí tengo poca comida, pero como tranquilo y sin miedo. Una vida sencilla y segura vale más que una lujosa llena de peligros.»</p>`,
questions:[
{type:'c', q:'¿Qué le ofreció el ratón de campo a su primo de visita?', opts:['Quesos y pasteles','Semillas, bellotas, trigo y agua fresca','Chocolate y jamón','Nada, porque no tenía comida'], ans:1, exp:'El ratón de campo ofreció lo que tenía: semillas, bellotas, trigo y agua fresca del arroyo.'},
{type:'c', q:'¿Por qué el ratón de ciudad invitó a su primo al campo a la ciudad?', opts:['Para enseñarle la ciudad','Para que conociera la abundante comida que había allí','Porque se sentía solo','Porque el campo era peligroso'], ans:1, exp:'El ratón de ciudad le habló de todos los manjares que había en la ciudad y lo invitó a ver cómo se vivía allí.'},
{type:'c', q:'¿Dónde entraron los dos ratones cuando llegaron a la ciudad?', opts:['Al comedor principal de la casa','A la despensa llena de comida','A la cocina','Al jardín de la casa'], ans:1, exp:'Cuando los dueños se fueron a dormir, los ratones entraron a la despensa, donde había todo tipo de manjares.'},
{type:'c', q:'¿Qué interrumpió la cena de los ratones en la ciudad?', opts:['Los dueños de la casa que se despertaron','Un perro guardián','Un gato enorme que apareció de repente','Una trampa para ratones'], ans:2, exp:'De repente apareció un enorme gato que hizo huir despavoridos a los dos ratones.'},
{type:'c', q:'¿Qué decidió hacer el ratón de campo al final?', opts:['Quedarse en la ciudad con su primo','Buscar una casa sin gato','Volver a su campo tranquilo','Aprender a enfrentarse al gato'], ans:2, exp:'El ratón de campo prefirió volver a su campo, donde la comida era escasa pero podía comer tranquilo y sin peligros.'},
{type:'f', t:'El ratón de ciudad dijo que en la ciudad había quesos, pasteles, jamón, chocolate y {0} de todo tipo.', blanks:['manjares'], pool:['manjares','regalos','juguetes','libros','plantas','semillas'], exp:'El ratón de ciudad describió todos los manjares y delicias que había en la gran ciudad.'},
{type:'f', t:'El ratón de campo prefería una vida {0} y {1} a una lujosa llena de peligros.', blanks:['sencilla','segura'], pool:['sencilla','segura','aburrida','tranquila','pobre','fácil'], exp:'La moraleja es que una vida sencilla y segura vale más que una lujosa llena de peligros.'},
{type:'v', q:'El ratón de ciudad disfrutó mucho de la comida sencilla del campo.', ans:false, exp:'El ratón de ciudad probó la comida del campo con cara de asco y dijo que no era forma de vivir.'},
{type:'v', q:'En la despensa de la casa de la ciudad había mucha variedad de comida.', ans:true, exp:'Había quesos, embutidos, pastas y dulces de todo tipo, más comida de la que el ratón de campo había visto junta.'},
{type:'v', q:'Al final el ratón de campo comprendió que la vida sencilla del campo era mejor para él.', ans:true, exp:'Prefirió volver: en el campo tenía poca comida pero comía tranquilo y sin miedo al gato.'}
]},

{id:17, title:'Pulgarcita',
text:`<p>Una mujer que deseaba mucho tener un hijo fue a ver a una bruja, que le dio una semilla mágica. La plantó en una maceta y pronto creció una flor enorme. Cuando la flor se abrió, dentro había una niña diminuta, no más grande que un pulgar. La mujer la llamó Pulgarcita y la quiso mucho. La niña vivía en una cáscara de nuez y dormía en un pétalo de rosa.</p>
<p>Una noche, un sapo enorme se coló por la ventana y se llevó a Pulgarcita para casarla con su hijo. La dejó en una hoja de nenúfar en medio del río para que no escapara. Unos peces compadecidos royeron el tallo y la hoja flotó libremente. Así Pulgarcita escapó del sapo, pero quedó sola en el mundo.</p>
<p>Llegó el invierno y Pulgarcita, tiritando de frío, llamó a la puerta de un topo que vivía bajo tierra. El topo la acogió pero quería que se casara con él. En el túnel del topo, Pulgarcita encontró a una golondrina herida y la cuidó durante todo el invierno. Cuando llegó la primavera, la golondrina se ofreció a llevarla lejos.</p>
<p>La golondrina la llevó a un país cálido lleno de flores. Allí Pulgarcita encontró a un pequeño rey de las flores, tan diminuto como ella. Se enamoraron y el rey le puso unas alas de libélula. Pulgarcita recibió un nuevo nombre: Maia. Finalmente tenía un hogar y personas de su mismo tamaño con quienes vivir feliz para siempre.</p>`,
questions:[
{type:'c', q:'¿De dónde salió Pulgarcita?', opts:['De un huevo mágico','Del interior de una flor que creció de una semilla mágica','De un lago encantado','De las manos de un hada madrina'], ans:1, exp:'Una bruja le dio a la mujer una semilla mágica. Al plantarla, creció una flor y dentro de ella estaba Pulgarcita.'},
{type:'c', q:'¿Quién se llevó a Pulgarcita en la noche?', opts:['Un ratón del campo','Una mariposa gigante','Un sapo enorme','El viento'], ans:2, exp:'Un sapo enorme se coló por la ventana mientras Pulgarcita dormía y se la llevó para casarla con su hijo.'},
{type:'c', q:'¿Cómo escapó Pulgarcita del sapo?', opts:['Saltó al agua y nadó','Unos peces royeron el tallo del nenúfar y la hoja flotó libre','Una rana la ayudó a escapar','Usó sus alas para volar'], ans:1, exp:'Unos peces compadecidos royeron el tallo del nenúfar y la hoja donde estaba Pulgarcita flotó libremente por el río.'},
{type:'c', q:'¿A quién encontró y cuidó Pulgarcita en el túnel del topo?', opts:['A un ratón enfermo','A una mariposa herida','A una abeja perdida','A una golondrina herida'], ans:3, exp:'En el túnel del topo, Pulgarcita encontró a una golondrina herida y la cuidó durante todo el invierno.'},
{type:'c', q:'¿Qué nombre le pusieron a Pulgarcita al final del cuento?', opts:['Flora','Pétala','Maia','Lila'], ans:2, exp:'El rey de las flores le puso alas de libélula y la llamó Maia, su nuevo nombre en el país de las flores.'},
{type:'f', t:'Pulgarcita vivía en una cáscara de {0} y dormía en un pétalo de {1}.', blanks:['nuez','rosa'], pool:['nuez','rosa','bellota','flor','caracol','hoja'], exp:'La mujer le hizo una camita en una cáscara de nuez y cubría a Pulgarcita con un pétalo de rosa.'},
{type:'f', t:'La golondrina, agradecida por sus cuidados, llevó a Pulgarcita a un país {0} lleno de {1}.', blanks:['cálido','flores'], pool:['cálido','flores','lejano','árboles','oscuro','pájaros'], exp:'La golondrina la llevó a un país cálido lleno de flores donde Pulgarcita encontró su verdadero hogar.'},
{type:'v', q:'El topo quería casarse con Pulgarcita porque la amaba profundamente.', ans:false, exp:'El topo la acogió en invierno pero simplemente quería que se casara con él, sin que hubiera amor verdadero.'},
{type:'v', q:'La golondrina ayudó a Pulgarcita porque ella la había cuidado cuando estaba herida.', ans:true, exp:'Pulgarcita cuidó a la golondrina herida durante el invierno y, agradecida, la golondrina la llevó al país de las flores.'},
{type:'v', q:'Al final Pulgarcita encontró personas de su mismo tamaño con quien vivir.', ans:true, exp:'En el país de las flores encontró al rey de las flores, tan pequeño como ella, y vivió feliz entre personas de su tamaño.'}
]},

{id:18, title:'El enano saltarín',
text:`<p>Una hilandera pobre fue llevada ante el rey, quien creyó que podía convertir la paja en oro. El rey la encerró en una habitación llena de paja y le dijo que si al amanecer no la había convertido en oro, moriría. La muchacha lloraba desesperada cuando apareció un hombrecito muy extraño. Le preguntó qué le daría a cambio de hilar la paja y convertirla en oro.</p>
<p>La primera noche, la muchacha le dio su collar. La segunda noche, su anillo. Pero a la tercera noche, cuando el rey prometió casarse con ella si volvía a lograrlo, la muchacha ya no tenía nada que dar. El hombrecito le pidió entonces que le prometiera su primer hijo. Desesperada, la muchacha aceptó.</p>
<p>La muchacha se casó con el rey y tuvo un hijo. Cuando el hombrecito volvió a reclamar su promesa, ella lloró tanto que él le propuso un trato: si en tres días adivinaba su nombre, podría quedarse con el niño. La reina envió mensajeros por todo el reino a buscar nombres raros.</p>
<p>El último día, un mensajero volvió contando que había visto a un hombrecito bailando alrededor de un fuego y cantando: «¡Que nadie sabe que me llamo Rumpelstiltskin!» Cuando la reina pronunció su nombre, el enano se enfureció tanto que se partió en dos. El niño quedó a salvo y la familia vivió feliz para siempre.</p>`,
questions:[
{type:'c', q:'¿Por qué el rey encerró a la hilandera con la paja?', opts:['Para castigarla por un robo','Porque creyó que podía convertir la paja en oro','Para hacerla trabajar de criada','Porque era una espía del enemigo'], ans:1, exp:'El rey creyó que la muchacha tenía el poder de convertir la paja en oro y la encerró para que lo demostrara.'},
{type:'c', q:'¿Qué le dio la muchacha al hombrecito la primera noche?', opts:['Su anillo','Un mechón de su cabello','Su collar','Una moneda de oro'], ans:2, exp:'La primera noche la muchacha le dio su collar a cambio de que hilara la paja y la convirtiera en oro.'},
{type:'c', q:'¿Qué le pidió el hombrecito la tercera noche a cambio de su ayuda?', opts:['Todo el oro que ganara','La promesa de su primer hijo','El trono del rey','Su nombre verdadero'], ans:1, exp:'Como ya no tenía nada que dar, el hombrecito le pidió que prometiera darle su primer hijo.'},
{type:'c', q:'¿Cómo descubrió la reina el nombre del hombrecito?', opts:['Lo leyó en un libro mágico','Un mensajero lo oyó mientras el enano cantaba su nombre bailando alrededor de un fuego','Se lo susurró un hada','Lo adivinó por casualidad'], ans:1, exp:'Un mensajero vio al hombrecito bailando y cantando su propio nombre: «¡Que nadie sabe que me llamo Rumpelstiltskin!»'},
{type:'c', q:'¿Qué le ocurrió al enano cuando la reina dijo su nombre?', opts:['Huyó corriendo y nunca volvió','Cumplió el trato y se llevó al niño','Se enfureció tanto que se partió en dos','Se convirtió en una nube de humo'], ans:2, exp:'Al escuchar su nombre, el enano se enfureció tanto que se partió en dos.'},
{type:'f', t:'El hombrecito convertía la {0} en {1} a cambio de regalos de la muchacha.', blanks:['paja','oro'], pool:['paja','oro','lana','plata','tela','cobre'], exp:'El enano era capaz de hilar la paja y convertirla en oro, que era lo que el rey exigía a la muchacha.'},
{type:'f', t:'La reina envió {0} por todo el reino para buscar el {1} del hombrecito.', blanks:['mensajeros','nombre'], pool:['mensajeros','nombre','soldados','secreto','magos','paradero'], exp:'Para ganar el trato, la reina necesitaba averiguar el nombre del enano y mandó mensajeros a buscarlo.'},
{type:'v', q:'El hombrecito apareció porque la muchacha lo llamó con un hechizo.', ans:false, exp:'El hombrecito apareció solo cuando la muchacha lloraba desesperada, sin que ella lo llamara con ningún hechizo.'},
{type:'v', q:'La muchacha se casó con el rey después de que el hombrecito hilara la paja en oro tres noches.', ans:true, exp:'Tras las tres noches de hilar paja en oro, el rey cumplió su promesa y se casó con la muchacha.'},
{type:'v', q:'El enano aceptó de buen grado que la reina supiera su nombre.', ans:false, exp:'Al contrario, se enfureció tanto al oír su nombre que se partió en dos.'}
]},

{id:19, title:'El sastrecillo valiente',
text:`<p>Un sastre estaba un día comiendo mermelada cuando llegaron varias moscas a posarse en el pan. Las espantó de un manotazo y mató siete de golpe. Tan orgulloso quedó que se bordó en el cinturón: «¡Siete de un golpe!» Luego salió al mundo a buscar aventuras, convencido de que era el hombre más valiente del reino.</p>
<p>En el camino se encontró con dos gigantes enormes que dormían bajo un árbol. El sastre subió al árbol y les lanzó piedras. Los gigantes se despertaron creyendo que se golpeaban el uno al otro y empezaron a pelearse. Cuando se cansaron de la pelea, el sastre bajó del árbol tranquilamente. El rey, que lo había visto todo desde lejos, pensó que el sastre había derrotado a los dos gigantes él solo.</p>
<p>El rey le propuso un trato: si realizaba tres hazañas imposibles, le daría a su hija en matrimonio y la mitad del reino. El sastre debía capturar a un unicornio, atrapar a un jabalí salvaje y derrotar a otros dos gigantes. El sastrecillo usó el ingenio en cada caso: engañó al unicornio para que clavara su cuerno en un árbol, metió al jabalí en una capilla y volvió a engañar a los nuevos gigantes igual que a los primeros.</p>
<p>El rey, que nunca creyó que el sastre lo conseguiría, tuvo que cumplir su promesa. El sastrecillo se casó con la princesa y gobernó con sabiduría e ingenio. Aprendió, y enseñó a todos, que la astucia y el valor pueden superar la fuerza bruta, y que quien cree en sí mismo puede lograr lo que parece imposible.</p>`,
questions:[
{type:'c', q:'¿Por qué el sastre se bordó «¡Siete de un golpe!» en el cinturón?', opts:['Porque había derrotado a siete gigantes','Porque había matado siete moscas de un manotazo','Porque era el campeón de una competición','Porque el rey se lo ordenó'], ans:1, exp:'El sastre mató siete moscas de un manotazo y, muy orgulloso de ello, se bordó esa frase en el cinturón.'},
{type:'c', q:'¿Cómo venció el sastre a los dos primeros gigantes?', opts:['Luchando con su espada','Usando magia','Lanzándoles piedras desde un árbol para que creyeran que se golpeaban entre sí','Llamando a la guardia del rey'], ans:2, exp:'El sastre subió a un árbol y les lanzó piedras; los gigantes creyeron que se golpeaban el uno al otro y se pelearon hasta cansarse.'},
{type:'c', q:'¿Cómo capturó el sastre al unicornio?', opts:['Con una red muy grande','Engañándolo para que clavara su cuerno en un árbol','Con una trampa de metal','Atándolo mientras dormía'], ans:1, exp:'El sastre engañó al unicornio para que cargara contra un árbol; el cuerno quedó clavado y el animal quedó atrapado.'},
{type:'c', q:'¿Qué recibió el sastre como recompensa por cumplir las tres hazañas?', opts:['Solo oro y plata','La mano de la princesa y la mitad del reino','El ejército del rey','Un palacio propio'], ans:1, exp:'El rey le prometió su hija en matrimonio y la mitad del reino si realizaba las tres hazañas, y tuvo que cumplir su promesa.'},
{type:'c', q:'¿Cuál es la lección principal del cuento?', opts:['La fuerza física es lo más importante','La astucia y el valor pueden superar la fuerza bruta','Los sastres son los mejores guerreros','Nunca hay que enfrentarse a los gigantes'], ans:1, exp:'El cuento enseña que la astucia y el valor pueden superar la fuerza bruta, y que creer en uno mismo permite lograr lo imposible.'},
{type:'f', t:'El sastre usó el {0} en cada prueba, en lugar de la fuerza {1}.', blanks:['ingenio','bruta'], pool:['ingenio','bruta','valor','física','miedo','suave'], exp:'En todas sus hazañas el sastre triunfó gracias al ingenio y la astucia, no a la fuerza.'},
{type:'f', t:'El sastre metió al {0} salvaje dentro de una {1} para atraparlo.', blanks:['jabalí','capilla'], pool:['jabalí','capilla','lobo','cueva','oso','trampa'], exp:'Para atrapar al jabalí salvaje, el sastre lo persiguió y logró encerrarlo dentro de una capilla.'},
{type:'v', q:'El rey siempre creyó que el sastre era un guerrero muy fuerte y poderoso.', ans:false, exp:'El rey nunca creyó que el sastre lo conseguiría, pero tuvo que cumplir su promesa cuando lo logró todo.'},
{type:'v', q:'El sastre usó el mismo truco de las piedras con los dos grupos de gigantes.', ans:true, exp:'En ambos casos subió a un árbol y les lanzó piedras para que se pelearan entre sí hasta cansarse.'},
{type:'v', q:'Al final el sastre gobernó con sabiduría e ingenio.', ans:true, exp:'El texto dice que el sastrecillo se casó con la princesa y gobernó con sabiduría e ingenio.'}
]}

];
