const STORIES = [

{id:0, title:'Caperucita Roja',
text:`<p>Érase una vez una niña muy alegre que vivía cerca de un bosque. Su abuela le había regalado una capa roja con capucha, y la niña la llevaba tan a menudo que todo el mundo la llamaba Caperucita Roja. Un día, su madre le preparó una cesta con pan, mantequilla y mermelada para que se la llevara a su abuela, que estaba enferma y vivía al otro lado del bosque.</p>
<p>Caperucita prometió ir por el camino sin desviarse, pero al entrar en el bosque vio flores tan bonitas que se apartó del sendero para recogerlas. Allí se encontró con un lobo enorme. El lobo le preguntó adónde iba y Caperucita, sin pensar en el peligro, le contó todo: que llevaba comida a su abuela y dónde vivía ella.</p>
<p>El lobo se fue corriendo por el camino más corto y llegó antes que Caperucita a casa de la abuela. Llamó a la puerta imitando la voz de la niña. La anciana abrió y el lobo la encerró en el armario. Luego se disfrazó con el gorro y la ropa de la abuela y se metió en la cama a esperar.</p>
<p>Cuando Caperucita llegó, notó que «su abuela» tenía los ojos enormes, las orejas muy grandes y una boca enorme. Al comprender que era el lobo, Caperucita gritó. Un cazador que pasaba cerca oyó los gritos, entró corriendo y asustó al lobo, que huyó sin volver nunca más. La abuela salió del armario sana y salva y las tres festejaron juntas con toda la comida de la cesta.</p>`,
questions:[
{type:'c', q:'¿Quién le regaló la capa roja a Caperucita?', opts:['Su madre','Su abuela','Una vecina','Una hada'], ans:1, exp:'El texto dice que su abuela le había regalado una capa roja con capucha.'},
{type:'c', q:'¿Por qué fue Caperucita al bosque?', opts:['Para recoger flores','Para buscar al lobo','Para llevar comida a su abuela enferma','Para visitar a un cazador'], ans:2, exp:'Su madre le preparó una cesta con comida para llevarle a su abuela, que estaba enferma.'},
{type:'c', q:'¿Qué hizo el lobo al enterarse de dónde vivía la abuela?', opts:['Se quedó esperando a Caperucita','La siguió despacio por el bosque','Fue corriendo a casa de la abuela por el camino más corto','Se fue a buscar a la madre'], ans:2, exp:'El lobo se fue corriendo por el camino más corto y llegó antes que Caperucita.'},
{type:'c', q:'¿Dónde escondió el lobo a la abuela?', opts:['Debajo de la cama','En el sótano','En el jardín','En el armario'], ans:3, exp:'El lobo encerró a la abuela en el armario y se disfrazó con su ropa.'},
{type:'c', q:'¿Quién salvó a Caperucita y a su abuela?', opts:['La madre de Caperucita','Un vecino del pueblo','Un cazador que pasaba cerca','La propia abuela'], ans:2, exp:'Un cazador que oyó los gritos de Caperucita entró corriendo y asustó al lobo.'},
{type:'c', q:'¿Por qué se desvió Caperucita del camino?', opts:['Porque vio al lobo','Porque estaba cansada','Porque vio flores bonitas','Porque se perdió'], ans:2, exp:'Al entrar en el bosque, Caperucita vio flores tan bonitas que se apartó del sendero para recogerlas.'},
{type:'f', t:'Caperucita llevaba una {0} con pan, mantequilla y mermelada para su abuela.', blanks:['cesta'], pool:['cesta','bolsa','caja','mochila','maleta','carro'], exp:'El texto dice que su madre le preparó una cesta con esa comida para la abuela.'},
{type:'f', t:'El lobo se disfrazó con el gorro y la {0} de la abuela y se metió en la cama.', blanks:['ropa'], pool:['ropa','bufanda','capa','sombrero','manta','falda'], exp:'El lobo se puso la ropa de la abuela para engañar a Caperucita cuando llegara.'},
{type:'f', t:'La niña se llamaba Caperucita Roja porque siempre llevaba una {0} roja.', blanks:['capa'], pool:['capa','falda','bufanda','chaqueta','manta','bolsa'], exp:'Su abuela le había regalado una capa roja con capucha y por eso todos la llamaban así.'},
{type:'v', q:'La abuela de Caperucita estaba enferma.', ans:true, exp:'El texto dice que la abuela estaba enferma y vivía al otro lado del bosque.'},
{type:'v', q:'Caperucita fue directamente a casa de la abuela sin parar.', ans:false, exp:'Caperucita se apartó del sendero para recoger flores y allí encontró al lobo.'},
{type:'v', q:'Al final, la abuela salió sana y salva del armario.', ans:true, exp:'El cazador asustó al lobo y la abuela pudo salir del armario sana y salva.'}
]},

{id:1, title:'Los tres cerditos',
text:`<p>Había una vez tres cerditos hermanos que se llamaban Tito, Pipo y Rico. Un día, su madre les dijo que ya eran mayores y que debían construir sus propias casas para protegerse del lobo feroz que vivía en el bosque. Los tres prometieron que lo harían, pero cada uno tenía una idea muy diferente.</p>
<p>Tito, el más pequeño y perezoso, construyó su casa de paja en un solo día. «¡Ya está! —dijo—. Así tendré tiempo para jugar.» Pipo, el mediano, tardó un poco más y construyó su casa de madera. Solo Rico, el mayor, se tomó el trabajo en serio y construyó una casa de ladrillo, aunque tardó mucho tiempo y sus hermanos se rieron de él.</p>
<p>Un día llegó el lobo hambriento. Primero fue a casa de Tito y sopló tan fuerte que la casa de paja cayó en un momento. Tito corrió a casa de Pipo. El lobo fue a por ellos y sopló con más fuerza: la casa de madera también se derrumbó. Los dos cerditos corrieron entonces a casa de Rico.</p>
<p>El lobo sopló y sopló, pero la casa de ladrillo no se movió. Furioso, intentó entrar por la chimenea. Los tres cerditos pusieron rápidamente una olla con agua hirviendo debajo. El lobo cayó dentro, se quemó y huyó despavorido. Desde ese día, los tres hermanos vivieron juntos en la casa de Rico y aprendieron que el trabajo bien hecho siempre vale la pena.</p>`,
questions:[
{type:'c', q:'¿Por qué la madre pidió a los cerditos que construyeran sus casas?', opts:['Porque quería estar sola','Para protegerse del lobo feroz','Para ganar un concurso','Porque la casa antigua era muy vieja'], ans:1, exp:'La madre les dijo que ya eran mayores y debían construir casas para protegerse del lobo.'},
{type:'c', q:'¿De qué material construyó su casa Pipo, el cerdito mediano?', opts:['De paja','De ladrillo','De piedra','De madera'], ans:3, exp:'Pipo, el mediano, construyó su casa de madera, tardando más que Tito pero menos que Rico.'},
{type:'c', q:'¿Por qué se rieron Tito y Pipo de Rico?', opts:['Porque Rico no sabía construir','Porque la casa de Rico era muy pequeña','Porque Rico tardó mucho tiempo en construir su casa de ladrillo','Porque Rico usaba materiales muy caros'], ans:2, exp:'Rico tardó mucho tiempo en construir su casa de ladrillo y sus hermanos se rieron de él por eso.'},
{type:'c', q:'¿En qué orden atacó el lobo las casas?', opts:['Primero la de ladrillo, luego la de madera, luego la de paja','Primero la de paja, luego la de madera, luego la de ladrillo','Primero la de madera, luego la de paja, luego la de ladrillo','Las tres al mismo tiempo'], ans:1, exp:'El lobo fue primero a casa de Tito (paja), luego a casa de Pipo (madera), y finalmente intentó la de Rico (ladrillo).'},
{type:'c', q:'¿Cómo intentó el lobo entrar en la casa de ladrillo al no poder derribarla?', opts:['Rompiendo una ventana','Cavando un túnel','Entrando por la chimenea','Esperando que los cerditos salieran'], ans:2, exp:'Al no poder derribar la casa de ladrillo soplando, el lobo intentó entrar por la chimenea.'},
{type:'f', t:'Tito construyó su casa de {0} en un solo día porque era el más {1}.', blanks:['paja','perezoso'], pool:['paja','perezoso','madera','valiente','ladrillo','trabajador'], exp:'Tito, el más perezoso, construyó la casa de paja rápidamente para tener tiempo de jugar.'},
{type:'f', t:'Los cerditos pusieron una olla con agua {0} debajo de la chimenea para atrapar al lobo.', blanks:['hirviendo'], pool:['hirviendo','fría','tibia','caliente','sucia','salada'], exp:'Pusieron agua hirviendo para que el lobo cayera dentro al bajar por la chimenea.'},
{type:'v', q:'Rico, el cerdito mayor, construyó su casa de paja.', ans:false, exp:'Rico construyó su casa de ladrillo. La de paja la construyó Tito, el más pequeño y perezoso.'},
{type:'v', q:'El lobo consiguió derribar la casa de ladrillo soplando.', ans:false, exp:'La casa de ladrillo era muy sólida: el lobo sopló y sopló pero no se movió.'},
{type:'v', q:'Al final, los tres cerditos vivieron juntos en la casa de Rico.', ans:true, exp:'El texto dice que desde ese día los tres hermanos vivieron juntos en la casa de Rico.'},
{type:'v', q:'La lección del cuento es que el trabajo bien hecho siempre vale la pena.', ans:true, exp:'El propio texto lo dice al final del cuento.'}
]},

{id:2, title:'La liebre y la tortuga',
text:`<p>En un prado verde y soleado vivían muchos animales. Entre ellos había una liebre muy presuntuosa que se pasaba el día alardeando de lo rápida que era. «¡Nadie puede correr más que yo!», decía siempre. Un día, la tortuga, que era tranquila y constante, la retó a una carrera. La liebre se rio a carcajadas: «¿Tú, retarme a mí? ¡Será un paseo!»</p>
<p>El zorro marcó la salida y la meta. Cuando sonó la señal, la liebre salió disparada como un rayo mientras la tortuga avanzaba despacio, paso a paso, sin detenerse nunca. Al cabo de un rato, la liebre llevaba tanta ventaja que decidió descansar bajo un árbol. «La tortuga tardará horas en llegar aquí», pensó. Se tumbó a la sombra y se quedó dormida.</p>
<p>La tortuga, mientras tanto, continuó andando sin parar, sin distraerse, con paso firme y constante. Cuando la liebre se despertó sobresaltada, ya era demasiado tarde: la tortuga estaba a punto de cruzar la meta. La liebre corrió con todas sus fuerzas, pero llegó unos segundos después. La tortuga había ganado la carrera.</p>
<p>Todos los animales aplaudieron a la tortuga. El búho, el más sabio del prado, dijo: «El verdadero ganador no es siempre el más rápido, sino el más constante.» La liebre, avergonzada, entendió la lección y desde ese día dejó de presumir tanto.</p>`,
questions:[
{type:'c', q:'¿Por qué todos los animales se cansaron de la liebre?', opts:['Porque era muy antipática con todos','Porque se pasaba el día alardeando de su velocidad','Porque hacía mucho ruido por las noches','Porque nunca ayudaba a nadie'], ans:1, exp:'La liebre se pasaba el día diciendo que nadie corría más que ella, y eso cansó a todos.'},
{type:'c', q:'¿Quién desafió a la liebre a una carrera?', opts:['El zorro','El búho','La tortuga','El ciervo'], ans:2, exp:'La tortuga, que era tranquila y constante, fue quien retó a la liebre a una carrera.'},
{type:'c', q:'¿Quién marcó la salida y la meta de la carrera?', opts:['El búho','La tortuga','El oso','El zorro'], ans:3, exp:'El texto dice que el zorro marcó la salida y la meta de la carrera.'},
{type:'c', q:'¿Qué hizo la liebre cuando llevaba mucha ventaja?', opts:['Volvió atrás para ayudar a la tortuga','Siguió corriendo sin parar hasta la meta','Se tumbó a la sombra de un árbol y se quedó dormida','Se distrajo hablando con otros animales'], ans:2, exp:'La liebre pensó que tenía tanta ventaja que podía descansar. Se tumbó bajo un árbol y se quedó dormida.'},
{type:'c', q:'¿Qué dijo el búho al final de la carrera?', opts:['Que la tortuga había hecho trampa','Que el verdadero ganador es el más constante, no el más rápido','Que había que repetir la carrera','Que la liebre debía entrenar más'], ans:1, exp:'El búho explicó que el verdadero ganador no es siempre el más rápido, sino el más constante.'},
{type:'c', q:'¿Cómo cambió la liebre tras la derrota?', opts:['Se fue a vivir a otro bosque','Prometió volver a retar a la tortuga','Dejó de presumir tanto','No cambió en absoluto'], ans:2, exp:'La liebre, avergonzada, entendió la lección y desde ese día dejó de presumir tanto.'},
{type:'f', t:'La tortuga avanzaba {0}, paso a paso, sin detenerse nunca.', blanks:['despacio'], pool:['despacio','rápido','saltando','corriendo','triste','cantando'], exp:'La tortuga avanzaba despacio pero de forma constante, sin parar nunca.'},
{type:'f', t:'La liebre se tumbó a la {0} de un árbol y se quedó {1}.', blanks:['sombra','dormida'], pool:['sombra','dormida','raíz','cansada','copa','tranquila'], exp:'La liebre se tumbó a la sombra de un árbol pensando que tenía tiempo de sobra.'},
{type:'v', q:'La liebre ganó la carrera porque era más rápida.', ans:false, exp:'Aunque la liebre era más rápida, se quedó dormida y la tortuga llegó primero a la meta.'},
{type:'v', q:'La tortuga se paró varias veces durante la carrera para descansar.', ans:false, exp:'La tortuga avanzó sin parar, sin distraerse, con paso firme y constante durante toda la carrera.'},
{type:'v', q:'La moraleja del cuento es que ser constante es más importante que ser rápido.', ans:true, exp:'El búho lo dice claramente: «el verdadero ganador no es siempre el más rápido, sino el más constante».'}
]},

{id:3, title:'El pastorcito mentiroso',
text:`<p>Había una vez un pastorcito llamado Pedro que cuidaba las ovejas del pueblo en una colina. El trabajo era tranquilo pero muy aburrido: los días pasaban lentos y sin novedad. Pedro decidió que podía gastar una broma para divertirse un poco. Se puso a gritar con todas sus fuerzas: «¡El lobo! ¡El lobo viene a comerse las ovejas!»</p>
<p>Los campesinos que trabajaban en los campos cercanos escucharon el grito y corrieron rápidamente hacia la colina con palos y herramientas para ahuyentar al lobo. Pero cuando llegaron, Pedro se reía a carcajadas. «¡Os he engañado! ¡No hay ningún lobo!» Los campesinos se fueron muy enfadados, pero perdonaron al chico.</p>
<p>Unos días después, Pedro volvió a hacer lo mismo: «¡El lobo! ¡El lobo!». Los campesinos corrieron otra vez, y otra vez Pedro se burló de ellos. Esta vez, los adultos se fueron mucho más enfadados y le advirtieron que no volviera a mentir. Pedro prometió que no lo haría.</p>
<p>Una tarde, un lobo de verdad apareció en la colina. Pedro, aterrorizado, gritó con todas sus fuerzas: «¡El lobo! ¡El lobo! ¡Es de verdad esta vez!». Pero los campesinos, pensando que era otra broma, no se movieron de sus casas. El lobo se llevó varias ovejas. Pedro aprendió la lección de la peor manera: el que miente pierde la confianza de los demás, y cuando más la necesita, nadie le cree.</p>`,
questions:[
{type:'c', q:'¿Por qué Pedro gritó «¡El lobo!» la primera vez?', opts:['Porque había visto un lobo de verdad','Para pedir ayuda a los campesinos','Para gastar una broma y divertirse','Para avisar de un peligro real'], ans:2, exp:'Pedro estaba aburrido y decidió gastar una broma gritando que venía el lobo.'},
{type:'c', q:'¿Qué hicieron los campesinos al escuchar el primer grito?', opts:['Ignoraron el aviso','Lo regañaron desde lejos','Corrieron hacia la colina con palos y herramientas','Se asomaron a la ventana a mirar'], ans:2, exp:'Los campesinos, creyendo que era real, corrieron rápidamente con palos y herramientas.'},
{type:'c', q:'¿Cuántas veces gastó Pedro la broma del lobo antes de que llegara el lobo de verdad?', opts:['Una vez','Dos veces','Tres veces','Cuatro veces'], ans:1, exp:'Pedro gastó la broma del lobo dos veces antes de que apareciera el lobo real.'},
{type:'c', q:'¿Qué pasó cuando Pedro gritó al ver el lobo de verdad?', opts:['Los campesinos corrieron inmediatamente a ayudarlo','El lobo se asustó y huyó solo','Los campesinos no le creyeron y no fueron a ayudarlo','El perro del pueblo espantó al lobo'], ans:2, exp:'Como Pedro había mentido antes, los campesinos pensaron que era otra broma y no fueron.'},
{type:'c', q:'¿Cuál es la moraleja del cuento?', opts:['Los lobos son animales muy peligrosos','El que miente pierde la confianza de los demás','Los pastores no deben gastar bromas','Los campesinos deben trabajar más'], ans:1, exp:'El texto lo dice al final: «el que miente pierde la confianza de los demás».'},
{type:'f', t:'Pedro cuidaba las {0} del pueblo en una colina.', blanks:['ovejas'], pool:['ovejas','vacas','cabras','gallinas','cerdos','caballos'], exp:'Pedro era un pastorcito que cuidaba las ovejas del pueblo.'},
{type:'f', t:'Los campesinos corrieron con palos y {0} para ahuyentar al lobo.', blanks:['herramientas'], pool:['herramientas','piedras','antorchas','redes','sacos','cestas'], exp:'Los campesinos cogieron palos y herramientas para defenderse del lobo que creían real.'},
{type:'v', q:'Pedro gritó «¡El lobo!» la primera vez porque realmente había visto uno.', ans:false, exp:'La primera vez Pedro mintió. Solo gritó para gastar una broma y divertirse.'},
{type:'v', q:'Los campesinos perdonaron a Pedro la primera vez que mintió.', ans:true, exp:'El texto dice que los campesinos se fueron enfadados pero perdonaron al chico.'},
{type:'v', q:'Cuando el lobo de verdad llegó, los campesinos corrieron a ayudar a Pedro.', ans:false, exp:'Los campesinos, cansados de las bromas, pensaron que era otra mentira y no fueron a ayudarlo.'}
]},

{id:4, title:'El patito feo',
text:`<p>En el estanque de una granja, una pata esperaba con impaciencia a que eclosionaran sus huevos. Uno a uno fueron saliendo los patitos: todos amarillos y esponjosos. Pero el último huevo, el más grande, tardó más en abrirse. Cuando por fin nació el último patito, todos quedaron asombrados: era gris, grande y torpe, muy distinto a sus hermanos.</p>
<p>Desde el primer día, el patito diferente lo pasó muy mal. Sus hermanos se reían de él y le llamaban «el patito feo». Los patos del estanque también lo rechazaban y le daban picotazos. El pobre patito estaba tan triste que decidió marcharse. Solo y asustado, se alejó del estanque y caminó durante mucho tiempo por el mundo.</p>
<p>Durante el otoño y el invierno, el patito vivió muchas dificultades. Casi se muere de frío junto a un lago helado. Un hombre bueno lo recogió y lo cuidó en su cabaña, pero el patito, al verse entre gatos y gallinas, volvió a escaparse. Pasó el invierno solo, temblando de frío, sobreviviendo como podía hasta que llegó la primavera.</p>
<p>Un día de primavera, el patito vio un grupo de cisnes blancos que volaban sobre el lago. Eran tan elegantes que se acercó a ellos, esperando que también lo rechazaran. Pero cuando se miró en el agua, no vio al patito gris y torpe de antes: vio un hermoso cisne blanco. Los otros cisnes lo rodearon con alegría. Por fin había encontrado a su verdadera familia.</p>`,
questions:[
{type:'c', q:'¿Por qué el patito era diferente a sus hermanos?', opts:['Porque llegó de otro nido','Porque nació del huevo más grande y era gris, grande y torpe','Porque no sabía nadar','Porque era mucho más pequeño que los demás'], ans:1, exp:'Todos los patitos eran amarillos y esponjosos, pero el último, nacido del huevo más grande, era gris, grande y torpe.'},
{type:'c', q:'¿Cómo trataban los otros patos al patito diferente?', opts:['Lo protegían de los peligros','Lo elegían como líder del grupo','Lo rechazaban y le daban picotazos','Lo ignoraban completamente'], ans:2, exp:'Sus hermanos se reían, los patos del estanque lo rechazaban y le daban picotazos.'},
{type:'c', q:'¿Por qué decidió marcharse el patito del estanque?', opts:['Porque quería ver mundo','Porque buscaba a sus padres','Porque estaba tan triste por el rechazo que decidió alejarse','Porque tenía hambre y no había comida'], ans:2, exp:'El patito estaba tan triste por el rechazo de todos que decidió marcharse solo.'},
{type:'c', q:'¿Cómo descubrió el patito que era un cisne?', opts:['Se lo dijo el hombre que lo cuidó','Se miró en el agua del lago','Un pájaro le dijo la verdad','Otro cisne le habló'], ans:1, exp:'Al acercarse a los cisnes y mirarse en el agua, vio que se había convertido en un hermoso cisne blanco.'},
{type:'c', q:'¿Cómo reaccionaron los cisnes cuando el patito se acercó a ellos?', opts:['Lo rechazaron como habían hecho los patos','Le dieron picotazos para alejarlo','Lo rodearon con alegría','Le preguntaron de dónde venía'], ans:2, exp:'Los cisnes lo rodearon con alegría porque era su verdadera familia.'},
{type:'f', t:'Sus hermanos le llamaban «el patito {0}» porque era muy diferente a ellos.', blanks:['feo'], pool:['feo','lento','tonto','gris','pequeño','torpe'], exp:'Sus hermanos le pusieron el apodo de «el patito feo» por su aspecto diferente.'},
{type:'f', t:'El patito pasó el {0} solo, temblando de {1}.', blanks:['invierno','frío'], pool:['invierno','frío','otoño','hambre','verano','miedo'], exp:'El texto dice que pasó el invierno solo, temblando de frío, hasta que llegó la primavera.'},
{type:'f', t:'Al mirarse en el agua, el patito vio que se había convertido en un hermoso {0} blanco.', blanks:['cisne'], pool:['cisne','pato','ganso','flamenco','garza','pelícano'], exp:'El patito descubrió su verdadera identidad al mirarse en el lago: era un cisne.'},
{type:'v', q:'El patito nació del huevo más pequeño del nido.', ans:false, exp:'El último huevo era el más grande, y de él salió el patito diferente.'},
{type:'v', q:'El patito pasó el invierno completamente solo.', ans:true, exp:'Aunque un hombre lo recogió, el patito escapó y pasó el invierno solo temblando de frío.'},
{type:'v', q:'Al final, el patito descubrió que en realidad era un cisne.', ans:true, exp:'Al mirarse en el agua del lago, vio que se había convertido en un hermoso cisne blanco.'}
]}

];
