const CWORD_POOL = [
  // 3 letras
  {w:'sol', c:'El astro que da luz y calor durante el día'},
  {w:'mar', c:'Gran masa de agua salada'},
  {w:'rio', c:'Corriente de agua dulce que va al mar'},
  {w:'pie', c:'Parte del cuerpo con la que caminamos'},
  {w:'ojo', c:'Órgano de la vista'},
  {w:'pan', c:'Alimento básico hecho con harina y agua'},
  {w:'luz', c:'Claridad que nos permite ver'},
  {w:'paz', c:'Ausencia de guerra o conflicto'},
  {w:'gas', c:'Sustancia sin forma fija que llena el espacio'},
  {w:'ley', c:'Norma que todos debemos cumplir'},
  {w:'mes', c:'Período de unos treinta días; el año tiene doce'},
  {w:'vez', c:'Ocasión o momento en que algo ocurre'},
  {w:'red', c:'Tejido de hilos entrelazados; también usamos una para internet'},
  {w:'sal', c:'Condimento blanco que añadimos a la comida para darle sabor'},
  {w:'pez', c:'Animal acuático con escamas y aletas que respira bajo el agua'},
  {w:'rey', c:'Monarca que gobierna un reino y lleva corona'},
  {w:'gol', c:'Punto que se marca cuando el balón entra en la portería'},

  // 4 letras
  {w:'gato', c:'Animal doméstico que maúlla'},
  {w:'pato', c:'Ave acuática con pico plano que grazna'},
  {w:'luna', c:'Satélite natural que brilla de noche'},
  {w:'casa', c:'Edificio donde vivimos'},
  {w:'mano', c:'Parte del cuerpo con cinco dedos'},
  {w:'boca', c:'Parte de la cara para comer y hablar'},
  {w:'pelo', c:'Filamentos que crecen en la cabeza'},
  {w:'lobo', c:'Animal salvaje del bosque que aúlla'},
  {w:'rojo', c:'Color de la sangre y los tomates'},
  {w:'mesa', c:'Mueble con superficie plana y patas'},
  {w:'sopa', c:'Plato líquido caliente con verduras o fideos'},
  {w:'nube', c:'Masa de vapor de agua que flota en el cielo'},
  {w:'flor', c:'Parte colorida de la planta'},
  {w:'mapa', c:'Dibujo que representa la Tierra o un país'},
  {w:'tren', c:'Vehículo que viaja sobre raíles'},
  {w:'vaca', c:'Animal grande que nos da leche'},
  {w:'piel', c:'Cubierta exterior del cuerpo humano'},
  {w:'guia', c:'Persona que enseña o indica el camino'},
  {w:'lago', c:'Gran masa de agua dulce rodeada de tierra por todos lados'},
  {w:'isla', c:'Trozo de tierra completamente rodeado de agua'},
  {w:'dedo', c:'Cada uno de los cinco apéndices de la mano'},
  {w:'hoja', c:'Parte plana y verde que crece en las ramas de las plantas'},
  {w:'mono', c:'Animal del zoo que trepa a los árboles y come plátanos'},
  {w:'toro', c:'Animal macho grande con cuernos; el matador lo torea'},

  // 5 letras
  {w:'perro', c:'Animal doméstico que ladra y es el mejor amigo del hombre'},
  {w:'tigre', c:'Gran felino rayado de la selva'},
  {w:'oveja', c:'Animal que nos da lana y cuyo sonido es «beee»'},
  {w:'verde', c:'Color de las hojas y los campos en primavera'},
  {w:'arena', c:'Granos finos que hay en la playa'},
  {w:'playa', c:'Orilla del mar cubierta de arena'},
  {w:'noche', c:'Período del día sin luz solar'},
  {w:'tarde', c:'Parte del día entre el mediodía y la noche'},
  {w:'burro', c:'Animal de carga que rebuzna'},
  {w:'libro', c:'Conjunto de hojas encuadernadas con texto'},
  {w:'globo', c:'Esfera de goma llena de aire o esfera que puede volar'},
  {w:'papel', c:'Material en hojas para escribir o dibujar'},
  {w:'piano', c:'Instrumento musical de teclas blancas y negras'},
  {w:'circo', c:'Espectáculo con acróbatas, payasos y animales'},
  {w:'viaje', c:'Desplazamiento de un lugar a otro'},
  {w:'barco', c:'Vehículo de transporte que navega por el mar o el río'},
  {w:'campo', c:'Terreno grande y llano fuera de la ciudad, con prados y cultivos'},
  {w:'pluma', c:'Filamento ligero que cubre el cuerpo de las aves'},
  {w:'norte', c:'Punto cardinal que señala hacia el Polo Ártico'},
  {w:'fresa', c:'Fruta pequeña, roja y dulce que crece cerca del suelo'},
  {w:'mango', c:'Fruta tropical de color amarillo-naranja, dulce y jugosa'},
  {w:'llama', c:'Animal andino similar al camello pero sin joroba'},

  // 6 letras
  {w:'verano', c:'Estación del año más calurosa'},
  {w:'madera', c:'Material duro que viene de los árboles'},
  {w:'ciudad', c:'Gran población donde viven muchas personas'},
  {w:'helado', c:'Postre frío hecho con leche o zumo de frutas'},
  {w:'jardin', c:'Terreno donde se cultivan plantas y flores'},
  {w:'numero', c:'Cifra que representa una cantidad'},
  {w:'blanco', c:'Color de la nieve y de las nubes'},
  {w:'medico', c:'Persona que cuida la salud de los enfermos'},
  {w:'cocina', c:'Habitación de la casa donde se prepara la comida'},
  {w:'bosque', c:'Zona con muchos árboles juntos donde viven muchos animales'},
  {w:'granja', c:'Lugar en el campo donde se crían animales domésticos'},
  {w:'teatro', c:'Edificio donde los actores representan obras ante el público'},
  {w:'pueblo', c:'Población pequeña, más pequeña que una ciudad'},
  {w:'camino', c:'Vía estrecha por donde se puede andar o viajar'},
  {w:'maleta', c:'Bolsa rígida con asa para transportar ropa en los viajes'},

  // 7 letras
  {w:'maestro', c:'Persona que enseña en la escuela'},
  {w:'familia', c:'Grupo formado por padres, hijos y parientes'},
  {w:'planeta', c:'Cuerpo celeste que gira alrededor de una estrella'},
  {w:'escuela', c:'Lugar donde los niños aprenden con su maestro'},
  {w:'pizarra', c:'Superficie negra donde el maestro escribe'},
  {w:'hermano', c:'Persona que comparte los mismos padres que tú'},
  {w:'caballo', c:'Animal que se monta y tira de carruajes'},
  {w:'mochila', c:'Bolsa que se lleva a la espalda para ir al colegio'},
  {w:'tablero', c:'Superficie plana usada en juegos como el ajedrez o el parchís'},
  {w:'camello', c:'Animal del desierto con una o dos jorobas en el lomo'},
  {w:'trabajo', c:'Esfuerzo que hacemos para ganarnos la vida'},
  {w:'espacio', c:'Lugar donde están los planetas y estrellas del universo'},
  {w:'ejemplo', c:'Modelo que sirve para explicar algo a los demás'},

  // 8 letras
  {w:'elefante', c:'Animal terrestre más grande, con trompa y colmillos'},
  {w:'cuaderno', c:'Libreta con hojas para escribir en clase'},
  {w:'mariposa', c:'Insecto con alas de colores que sale de una crisálida'},
  {w:'invierno', c:'Estación del año más fría, con nieve y días cortos'},
  {w:'calabaza', c:'Fruta grande y redonda de color naranja, símbolo de Halloween'},
  {w:'monstruo', c:'Ser imaginario y terrible que aparece en los cuentos de miedo'},
  {w:'mosquito', c:'Insecto pequeño que pica y nos hace rascarnos'},
  {w:'farmacia', c:'Tienda donde se compran medicamentos y remedios'},
  {w:'dentista', c:'Médico especialista en cuidar y curar los dientes'},
];
