// Section 1: donat el root, tria la paraula de la mateixa família
const FAM_POOL = [
  {root:'libro',    w:'librería',    wrong:['libre','lluvia','limón'],       hint:'Comparten la raíz "libr-": libro, librero, librería'},
  {root:'mar',      w:'marinero',    wrong:['mármol','madre','miel'],        hint:'Comparten la raíz "mar-": mar, marino, marinero, marea'},
  {root:'pan',      w:'panadero',    wrong:['patio','pluma','pared'],        hint:'Comparten la raíz "pan-": pan, panadero, panadería'},
  {root:'flor',     w:'florero',     wrong:['flauta','fruta','fábrica'],     hint:'Comparten la raíz "flor-": flor, florero, florista'},
  {root:'leche',    w:'lechería',    wrong:['lechuga','lento','lección'],    hint:'Comparten la raíz "lech-": leche, lechero, lechería'},
  {root:'tierra',   w:'terrestre',   wrong:['techo','tigre','tela'],         hint:'Comparten la raíz "terr-": tierra, terreno, terrestre'},
  {root:'sol',      w:'soleado',     wrong:['sala','sopa','semilla'],        hint:'Comparten la raíz "sol-": sol, solar, soleado, solear'},
  {root:'árbol',    w:'arboleda',    wrong:['ardilla','arco','arena'],       hint:'Comparten la raíz "árbol-": árbol, arboleda, arbolito'},
  {root:'nieve',    w:'nevada',      wrong:['nido','niño','nivel'],          hint:'Comparten la raíz "niev-/nev-": nieve, nevar, nevada'},
  {root:'pez',      w:'pescador',    wrong:['pelo','pena','pecho'],          hint:'Comparten la raíz "pesc-": pez, pescado, pescador'},
  {root:'casa',     w:'caserío',     wrong:['campo','cosa','copa'],          hint:'Comparten la raíz "cas-": casa, casero, caserío'},
  {root:'luz',      w:'luminoso',    wrong:['luna','lobo','loma'],           hint:'Comparten la raíz "lum-": luz, luminoso, alumbrar'},
  {root:'calor',    w:'calentar',    wrong:['calle','cama','campo'],         hint:'Comparten la raíz "calor-/cali-": calor, caliente, calentar'},
  {root:'boca',     w:'bocadillo',   wrong:['bolso','bosque','boda'],        hint:'Comparten la raíz "boc-": boca, bocado, bocadillo'},
  {root:'mano',     w:'manotazo',    wrong:['manta','máscara','mapa'],       hint:'Comparten la raíz "man-": mano, manopla, manotazo'},
  {root:'hierro',   w:'herrería',    wrong:['hilo','hielo','hierba'],        hint:'Comparten la raíz "hierr-/herr-": hierro, herrería, herrero'},
  {root:'fuego',    w:'fogata',      wrong:['fuerza','fuente','funda'],      hint:'Comparten la raíz "fueg-/fog-": fuego, fogata, fogón'},
  {root:'tiempo',   w:'temporal',    wrong:['tímido','título','tinta'],      hint:'Comparten la raíz "tiemp-/temp-": tiempo, temporal, temporada'},
  {root:'piedra',   w:'pedrada',     wrong:['piel','pierna','pieza'],        hint:'Comparten la raíz "piedr-/pedr-": piedra, pedrada, pedrero'},
  {root:'agua',     w:'aguacero',    wrong:['aguja','ajo','alma'],           hint:'Comparten la raíz "agua-": agua, aguacero, aguado'},
  // ── Nuevas entradas ──
  {root:'viento',   w:'ventoso',     wrong:['verde','viejo','vela'],         hint:'Comparten la raíz "vient-/vent-": viento, ventoso, ventolera'},
  {root:'color',    w:'colorido',    wrong:['cola','collar','colegio'],      hint:'Comparten la raíz "color-": color, colorear, colorido'},
  {root:'música',   w:'musical',     wrong:['muela','mosca','multa'],        hint:'Comparten la raíz "music-": música, musical, músico'},
  {root:'cocina',   w:'cocinero',    wrong:['costura','cofre','colmo'],      hint:'Comparten la raíz "cocin-": cocina, cocinar, cocinero'},
  {root:'juego',    w:'jugador',     wrong:['jugo','julio','junta'],         hint:'Comparten la raíz "jueg-/jug-": juego, jugar, jugador'},
  {root:'luna',     w:'lunar',       wrong:['lupa','lumbre','lobo'],         hint:'Comparten la raíz "luna-/lunar-": luna, lunar, lunático'},
  {root:'año',      w:'aniversario', wrong:['ancho','anca','ansia'],         hint:'Comparten la raíz "año-/anu-": año, anual, aniversario'},
  {root:'arte',     w:'artista',     wrong:['arco','arena','ardid'],         hint:'Comparten la raíz "art-": arte, artista, artístico, artesano'},
  {root:'canto',    w:'cantante',    wrong:['campo','caña','caucho'],        hint:'Comparten la raíz "cant-": canto, cantar, cantante'},
  {root:'vuelo',    w:'volador',     wrong:['viejo','valle','vara'],         hint:'Comparten la raíz "vuelo-/vol-": vuelo, volar, volador'},
  {root:'jardín',   w:'jardinero',   wrong:['jarra','jamón','jaula'],        hint:'Comparten la raíz "jardín-/jardin-": jardín, jardinero, jardinería'},
  {root:'hielo',    w:'helado',      wrong:['hilo','hijo','hito'],           hint:'Comparten la raíz "hiel-/hel-": hielo, helar, helado'},
  {root:'fruta',    w:'frutero',     wrong:['frente','freír','flecha'],      hint:'Comparten la raíz "fruta-/frut-": fruta, frutero, frutal'},
  {root:'guerra',   w:'guerrero',    wrong:['guía','gusto','gurú'],          hint:'Comparten la raíz "guerr-": guerra, guerrero, guerrilla'},
  {root:'ciudad',   w:'ciudadano',   wrong:['cielo','cinta','circo'],        hint:'Comparten la raíz "ciudad-/ciudadan-": ciudad, ciudadano, ciudadela'},
  {root:'niño',     w:'niñez',       wrong:['nido','nivel','nimio'],         hint:'Comparten la raíz "niñ-": niño, niñez, niñera'},
  {root:'letra',    w:'letrero',     wrong:['leche','lecho','legua'],        hint:'Comparten la raíz "letra-/letr-": letra, letrero, letrado'},
  {root:'caza',     w:'cazador',     wrong:['casa','caja','capa'],           hint:'Comparten la raíz "caz-": caza, cazar, cazador'},
  {root:'baile',    w:'bailarín',    wrong:['baño','barco','banco'],         hint:'Comparten la raíz "bail-": baile, bailar, bailarín'},
  {root:'camino',   w:'caminante',   wrong:['campo','cama','cañón'],         hint:'Comparten la raíz "camin-": camino, caminar, caminante'},
  {root:'peligro',  w:'peligroso',   wrong:['pelo','perro','pecho'],         hint:'Comparten la raíz "peligr-": peligro, peligroso, peligrar'},
  {root:'diente',   w:'dental',      wrong:['diez','dieta','dicho'],         hint:'Comparten la raíz "dient-/dent-": diente, dental, dentista'},
  {root:'oro',      w:'dorado',      wrong:['olmo','obra','orco'],           hint:'Comparten la raíz "or-/dor-": oro, dorar, dorado'},
  {root:'amor',     w:'amoroso',     wrong:['amigo','añil','ánimo'],         hint:'Comparten la raíz "amor-": amor, amoroso, enamorar'},
  {root:'planta',   w:'plantación',  wrong:['playa','pluma','plaza'],        hint:'Comparten la raíz "plant-": planta, plantar, plantación'},
  {root:'pueblo',   w:'poblado',     wrong:['puente','puerto','puño'],       hint:'Comparten la raíz "puebl-/pobl-": pueblo, poblado, población'},
  {root:'fuerza',   w:'esfuerzo',    wrong:['fuego','fuente','funda'],       hint:'Comparten la raíz "fuerz-/esfu-": fuerza, forzar, esfuerzo'},
  {root:'leña',     w:'leñador',     wrong:['lecho','legua','lema'],         hint:'Comparten la raíz "leñ-": leña, leñador, leñatero'},
  {root:'trabajo',  w:'trabajador',  wrong:['trapo','trampa','trato'],       hint:'Comparten la raíz "trabaj-": trabajo, trabajar, trabajador'},
  {root:'hermano',  w:'hermandad',   wrong:['herida','herrero','hernia'],    hint:'Comparten la raíz "herman-": hermano, hermandad, hermanastro'},
];

// Section 2: quina paraula no pertany a la família?
const FAM_ODD = [
  {words:['librero','librería','libre','libresco'],         intruder:'libre',       hint:'"libre" viene de "liber" (libertad), no de "libro"'},
  {words:['marinero','marino','marisma','mármol'],          intruder:'mármol',      hint:'"mármol" no tiene relación con "mar"'},
  {words:['panadero','panadería','panera','pantalla'],      intruder:'pantalla',    hint:'"pantalla" no comparte raíz con "pan"'},
  {words:['florero','florista','flauta','florecer'],        intruder:'flauta',      hint:'"flauta" es un instrumento, no viene de "flor"'},
  {words:['lechero','lechería','lechuga','lechal'],         intruder:'lechuga',     hint:'"lechuga" es una planta, no viene de "leche"'},
  {words:['terreno','terrestre','territorio','techo'],      intruder:'techo',       hint:'"techo" no comparte raíz con "tierra"'},
  {words:['soleado','solar','solear','sala'],               intruder:'sala',        hint:'"sala" no tiene relación con "sol"'},
  {words:['arboleda','arbolito','árbol','ardilla'],         intruder:'ardilla',     hint:'"ardilla" es un animal, no viene de "árbol"'},
  {words:['nevada','nevar','nevado','nido'],                intruder:'nido',        hint:'"nido" es donde viven los pájaros, no viene de "nieve"'},
  {words:['pescador','pesca','pescar','peinar'],            intruder:'peinar',      hint:'"peinar" no tiene relación con "pez" ni "pescar"'},
  {words:['casero','caserío','casita','campo'],             intruder:'campo',       hint:'"campo" no comparte raíz con "casa"'},
  {words:['bocado','bocadillo','boca','bolso'],             intruder:'bolso',       hint:'"bolso" no viene de "boca"'},
  {words:['calentar','caliente','calefacción','calle'],     intruder:'calle',       hint:'"calle" no tiene relación con "calor"'},
  {words:['manopla','manotazo','mano','manta'],             intruder:'manta',       hint:'"manta" no comparte raíz con "mano"'},
  // ── Nuevas entradas ──
  {words:['ciudadano','ciudadela','ciudad','cielo'],        intruder:'cielo',       hint:'"cielo" no viene de "ciudad"'},
  {words:['ventoso','ventolera','viento','verde'],          intruder:'verde',       hint:'"verde" no tiene relación con "viento"'},
  {words:['colorido','colorear','color','collar'],          intruder:'collar',      hint:'"collar" no comparte raíz con "color"'},
  {words:['musical','músico','música','mosca'],             intruder:'mosca',       hint:'"mosca" es un insecto, no viene de "música"'},
  {words:['cocinero','cocinar','cocina','costura'],         intruder:'costura',     hint:'"costura" no comparte raíz con "cocina"'},
  {words:['jugador','juguete','jugar','julio'],             intruder:'julio',       hint:'"julio" es un mes, no viene de "juego"'},
  {words:['lunar','lunático','luna','lupa'],                intruder:'lupa',        hint:'"lupa" no tiene relación con "luna"'},
  {words:['anual','aniversario','año','ancho'],             intruder:'ancho',       hint:'"ancho" no comparte raíz con "año"'},
  {words:['artista','artístico','artesano','arco'],         intruder:'arco',        hint:'"arco" no viene de "arte"'},
  {words:['cantante','cantar','cantautor','campo'],         intruder:'campo',       hint:'"campo" no tiene relación con "canto"'},
  {words:['volar','volador','volátil','valle'],             intruder:'valle',       hint:'"valle" no comparte raíz con "vuelo"'},
  {words:['jardinero','jardinería','jardín','jarra'],       intruder:'jarra',       hint:'"jarra" no viene de "jardín"'},
  {words:['helar','helado','helador','hilo'],               intruder:'hilo',        hint:'"hilo" no tiene relación con "hielo"'},
  {words:['frutero','frutal','fruta','frente'],             intruder:'frente',      hint:'"frente" no comparte raíz con "fruta"'},
  {words:['guerrero','guerrilla','guerra','gusto'],         intruder:'gusto',       hint:'"gusto" no viene de "guerra"'},
  {words:['niñez','niñera','niño','nivel'],                 intruder:'nivel',       hint:'"nivel" no comparte raíz con "niño"'},
  {words:['letrero','letrado','letra','leche'],             intruder:'leche',       hint:'"leche" no tiene relación con "letra"'},
  {words:['cazar','cazador','caza','casa'],                 intruder:'casa',        hint:'"casa" no comparte raíz con "caza"'},
  {words:['bailar','bailarín','baile','baño'],              intruder:'baño',        hint:'"baño" no viene de "baile"'},
  {words:['caminar','caminante','camino','cama'],           intruder:'cama',        hint:'"cama" no tiene relación con "camino"'},
  {words:['peligroso','peligrar','peligro','pelo'],         intruder:'pelo',        hint:'"pelo" no comparte raíz con "peligro"'},
  {words:['dental','dentista','diente','dieta'],            intruder:'dieta',       hint:'"dieta" no viene de "diente"'},
  {words:['dorar','dorado','oro','olmo'],                   intruder:'olmo',        hint:'"olmo" es un árbol, no viene de "oro"'},
  {words:['amoroso','enamorar','amor','amigo'],             intruder:'amigo',       hint:'"amigo" no comparte raíz con "amor"'},
  {words:['plantar','plantación','planta','playa'],         intruder:'playa',       hint:'"playa" no tiene relación con "planta"'},
  {words:['poblado','población','pueblo','puente'],         intruder:'puente',      hint:'"puente" no comparte raíz con "pueblo"'},
  {words:['forzar','esfuerzo','fuerza','fuente'],          intruder:'fuente',      hint:'"fuente" no tiene relación con "fuerza"'},
  {words:['leñador','leñatero','leña','lecho'],             intruder:'lecho',       hint:'"lecho" es una cama, no viene de "leña"'},
  {words:['trabajar','trabajador','trabajo','trampa'],      intruder:'trampa',      hint:'"trampa" no comparte raíz con "trabajo"'},
  {words:['hermandad','hermanastro','hermano','herrero'],   intruder:'herrero',     hint:'"herrero" trabaja el hierro, no viene de "hermano"'},
  {words:['nocturno','anochecer','noche','nota'],           intruder:'nota',        hint:'"nota" no tiene relación con "noche"'},
  {words:['pedalear','peatón','pedal','pelota'],            intruder:'pelota',      hint:'"pelota" es una bola, no viene de "pie"'},
  {words:['terreno','territorio','terrestre','tren'],       intruder:'tren',        hint:'"tren" no comparte raíz con "tierra"'},
  {words:['invierno','invernal','invernar','invento'],      intruder:'invento',     hint:'"invento" viene de "inventar", no de "invierno"'},
  {words:['marisma','maremoto','marea','mariposa'],         intruder:'mariposa',    hint:'"mariposa" es un insecto, no viene de "mar"'},
  {words:['hogareño','hogar','hoguera','hora'],             intruder:'hora',        hint:'"hora" no comparte raíz con "hogar"'},
  {words:['luminoso','alumbrar','luz','luna'],              intruder:'luna',        hint:'"luna" brilla en el cielo pero no comparte raíz con "luz"'},
];
