const RR_POOL = [
  // ── RR entre vocales (sonido fuerte) ──
  {w:'ca_o',       ans:'rr', full:'carro',      ctx:'El {w} del granjero iba cargado de paja.',         hint:'Entre vocales, sonido fuerte → rr'},
  {w:'pe_o',       ans:'rr', full:'perro',      ctx:'El {w} mueve la cola cuando está contento.',        hint:'Entre vocales, sonido fuerte → rr'},
  {w:'to_e',       ans:'rr', full:'torre',      ctx:'Desde la {w} se veía todo el pueblo.',              hint:'Entre vocales, sonido fuerte → rr'},
  {w:'a_oz',       ans:'rr', full:'arroz',      ctx:'El {w} con leche es un postre delicioso.',          hint:'Entre vocales, sonido fuerte → rr'},
  {w:'ba_io',      ans:'rr', full:'barrio',     ctx:'Mi {w} tiene un parque muy grande.',                hint:'Entre vocales, sonido fuerte → rr'},
  {w:'co_eo',      ans:'rr', full:'correo',     ctx:'Mandó la carta por {w} postal.',                    hint:'Entre vocales, sonido fuerte → rr'},
  {w:'ja_a',       ans:'rr', full:'jarra',      ctx:'Puso la {w} de agua fría en la mesa.',              hint:'Entre vocales, sonido fuerte → rr'},
  {w:'go_a',       ans:'rr', full:'gorra',      ctx:'Se puso la {w} para protegerse del sol.',           hint:'Entre vocales, sonido fuerte → rr'},
  {w:'tie_a',      ans:'rr', full:'tierra',     ctx:'La {w} del jardín estaba húmeda tras la lluvia.',   hint:'Entre vocales, sonido fuerte → rr'},
  {w:'sie_a',      ans:'rr', full:'sierra',     ctx:'Cortaron el tronco con una {w}.',                   hint:'Entre vocales, sonido fuerte → rr'},
  {w:'ba_o',       ans:'rr', full:'barro',      ctx:'Los niños jugaron en el {w} después de llover.',    hint:'Entre vocales, sonido fuerte → rr'},
  {w:'a_uga',      ans:'rr', full:'arruga',     ctx:'La camisa tenía una {w} enorme.',                   hint:'Entre vocales, sonido fuerte → rr'},
  {w:'bu_o',       ans:'rr', full:'burro',      ctx:'El {w} cargaba leña por el camino del bosque.',     hint:'Entre vocales, sonido fuerte → rr'},
  {w:'chu_o',      ans:'rr', full:'churro',     ctx:'Desayunaron {w}s con chocolate caliente.',          hint:'Entre vocales, sonido fuerte → rr'},
  {w:'bo_ar',      ans:'rr', full:'borrar',     ctx:'Tuvo que {w} la respuesta con la goma.',            hint:'Entre vocales, sonido fuerte → rr'},
  {w:'ce_o',       ans:'rr', full:'cerro',      ctx:'Subieron hasta la cima del {w} para ver el paisaje.',hint:'Entre vocales, sonido fuerte → rr'},
  {w:'abu_ir',     ans:'rr', full:'aburrir',    ctx:'Las clases sin explicaciones pueden {w} mucho.',    hint:'Entre vocales, sonido fuerte → rr'},

  // ── R entre vocales (sonido suave) ──
  {w:'pe_a',       ans:'r',  full:'pera',       ctx:'La {w} que compré estaba muy madura.',              hint:'Entre vocales, sonido suave → r'},
  {w:'ca_a',       ans:'r',  full:'cara',       ctx:'Tenía una {w} muy alegre y risueña.',               hint:'Entre vocales, sonido suave → r'},
  {w:'fa_o',       ans:'r',  full:'faro',       ctx:'El {w} guía a los barcos por la noche.',            hint:'Entre vocales, sonido suave → r'},
  {w:'ho_a',       ans:'r',  full:'hora',       ctx:'¿Qué {w} es? — Son las tres en punto.',             hint:'Entre vocales, sonido suave → r'},
  {w:'lo_o',       ans:'r',  full:'loro',       ctx:'El {w} repetía todo lo que escuchaba.',             hint:'Entre vocales, sonido suave → r'},
  {w:'a_o',        ans:'r',  full:'aro',        ctx:'El gimnasta saltó por el {w} de fuego.',            hint:'Entre vocales, sonido suave → r'},
  {w:'pu_o',       ans:'r',  full:'puro',       ctx:'El aire del campo es {w} y fresco.',                hint:'Entre vocales, sonido suave → r'},
  {w:'fo_o',       ans:'r',  full:'foro',       ctx:'Participó en el {w} de ciencias del colegio.',      hint:'Entre vocales, sonido suave → r'},
  {w:'a_ena',      ans:'r',  full:'arena',      ctx:'Jugaron a construir castillos de {w} en la playa.', hint:'Entre vocales, sonido suave → r'},
  {w:'pi_ata',     ans:'r',  full:'pirata',     ctx:'El {w} buscaba tesoros perdidos en el mar.',        hint:'Entre vocales, sonido suave → r'},
  {w:'co_ona',     ans:'r',  full:'corona',     ctx:'La reina llevaba una {w} de oro en la cabeza.',     hint:'Entre vocales, sonido suave → r'},
  {w:'ma_iposa',   ans:'r',  full:'mariposa',   ctx:'La {w} revoloteaba entre las flores del jardín.',   hint:'Entre vocales, sonido suave → r'},
  {w:'ca_amelo',   ans:'r',  full:'caramelo',   ctx:'Le dieron un {w} de fresa en la feria.',            hint:'Entre vocales, sonido suave → r'},

  // ── R al inicio de palabra (sonido fuerte, se escribe r) ──
  {w:'_osa',       ans:'r',  full:'rosa',       ctx:'Me regalaron una {w} roja muy bonita.',             hint:'Al inicio de palabra → siempre r'},
  {w:'_atón',      ans:'r',  full:'ratón',      ctx:'El {w} se escondió detrás del armario.',            hint:'Al inicio de palabra → siempre r'},
  {w:'_ío',        ans:'r',  full:'río',        ctx:'El {w} Ebro pasa por varias ciudades.',             hint:'Al inicio de palabra → siempre r'},
  {w:'_ueda',      ans:'r',  full:'rueda',      ctx:'Se pinchó una {w} de la bicicleta.',                hint:'Al inicio de palabra → siempre r'},
  {w:'_ey',        ans:'r',  full:'rey',        ctx:'El {w} vivía en un gran palacio.',                  hint:'Al inicio de palabra → siempre r'},
  {w:'_áfaga',     ans:'r',  full:'ráfaga',     ctx:'Una {w} de viento apagó todas las velas.',          hint:'Al inicio de palabra → siempre r'},
  {w:'_isa',       ans:'r',  full:'risa',       ctx:'La {w} de los niños llenó el recreo.',              hint:'Al inicio de palabra → siempre r'},
  {w:'_oca',       ans:'r',  full:'roca',       ctx:'El escalador subió por la {w} con mucho cuidado.',  hint:'Al inicio de palabra → siempre r'},
  {w:'_uido',      ans:'r',  full:'ruido',      ctx:'El {w} del tráfico no le dejaba dormir.',           hint:'Al inicio de palabra → siempre r'},
  {w:'_ompecabezas',ans:'r', full:'rompecabezas',ctx:'Tardó dos horas en terminar el {w}.',             hint:'Al inicio de palabra → siempre r'},

  // ── R tras consonante (sonido fuerte, se escribe r) ──
  {w:'son_isa',    ans:'r',  full:'sonrisa',    ctx:'Su {w} iluminaba toda la habitación.',              hint:'Tras consonante, sonido fuerte → r'},
  {w:'en_edo',     ans:'r',  full:'enredo',     ctx:'Ese {w} de cables es difícil de deshacer.',         hint:'Tras consonante, sonido fuerte → r'},
  {w:'hon_ado',    ans:'r',  full:'honrado',    ctx:'Fue siempre un ciudadano {w} y trabajador.',        hint:'Tras consonante, sonido fuerte → r'},
  {w:'al_ededor',  ans:'r',  full:'alrededor',  ctx:'Pusieron flores {w} de la fuente del parque.',      hint:'Tras consonante, sonido fuerte → r'},
  {w:'is_ael',     ans:'r',  full:'Israel',     ctx:'{w} es un país situado en Oriente Medio.',          hint:'Tras consonante, sonido fuerte → r'},
  {w:'en_ojecer',  ans:'r',  full:'enrojecer',  ctx:'Empezó a {w} de vergüenza al equivocarse.',         hint:'Tras consonante, sonido fuerte → r'},
  {w:'sub_ayado',  ans:'r',  full:'subrayado',  ctx:'El texto {w} en el libro era el más importante.',   hint:'Tras consonante, sonido fuerte → r'},
  {w:'en_iquecer', ans:'r',  full:'enriquecer', ctx:'Leer ayuda a {w} el vocabulario.',                  hint:'Tras consonante, sonido fuerte → r'},
  {w:'hon_ar',     ans:'r',  full:'honrar',     ctx:'Debemos {w} a las personas que nos ayudan.',        hint:'Tras consonante, sonido fuerte → r'},
  {w:'en_oscar',   ans:'r',  full:'enroscar',   ctx:'Tuvo que {w} la tapa del frasco con fuerza.',       hint:'Tras consonante, sonido fuerte → r'},
];
