// ortografia_lly_data.js — Pool de palabras LL e Y (castellano 4º)
// e.w   = palabra con _ donde va LL o Y
// e.full = palabra completa
// e.ans  = 'll' | 'y'
// e.ctx  = frase con {w} — la palabra NO empieza la frase
// e.hint = regla

const LLY_POOL = [
  // ── LL al inicio de palabra ──
  {w:'_amar',     ans:'ll', full:'llamar',     ctx:'Quería {w} a su amiga por teléfono.',                 hint:'ll- al inicio de palabra → ll'},
  {w:'_over',     ans:'ll', full:'llover',     ctx:'Va a {w} toda la tarde; lleva el paraguas.',          hint:'ll- al inicio de palabra → ll'},
  {w:'_ave',      ans:'ll', full:'llave',      ctx:'Perdió la {w} de la puerta de su casa.',              hint:'ll- al inicio de palabra → ll'},
  {w:'_eno',      ans:'ll', full:'lleno',      ctx:'El vaso estaba {w} hasta arriba.',                    hint:'ll- al inicio de palabra → ll'},
  {w:'_orar',     ans:'ll', full:'llorar',     ctx:'El niño empezó a {w} de alegría.',                    hint:'ll- al inicio de palabra → ll'},
  {w:'_uvia',     ans:'ll', full:'lluvia',     ctx:'La {w} mojó todos los paraguas del colegio.',         hint:'ll- al inicio de palabra → ll'},
  {w:'_egar',     ans:'ll', full:'llegar',     ctx:'Prometió {w} a tiempo a la reunión.',                 hint:'ll- al inicio de palabra → ll'},
  {w:'_evar',     ans:'ll', full:'llevar',     ctx:'Tuvo que {w} la mochila al colegio.',                 hint:'ll- al inicio de palabra → ll'},
  {w:'_ano',      ans:'ll', full:'llano',      ctx:'El terreno era muy {w}, sin ninguna colina.',         hint:'ll- al inicio de palabra → ll'},
  {w:'_ama',      ans:'ll', full:'llama',      ctx:'Una pequeña {w} brillaba en la oscuridad.',           hint:'ll- al inicio de palabra → ll'},

  // ── LL en el interior de la palabra ──
  {w:'ca_e',      ans:'ll', full:'calle',      ctx:'Cruzaron la {w} con mucho cuidado.',                  hint:'ll en el interior → ll'},
  {w:'po_o',      ans:'ll', full:'pollo',      ctx:'Comieron {w} asado para cenar.',                      hint:'ll en el interior → ll'},
  {w:'si_a',      ans:'ll', full:'silla',      ctx:'Se sentó en la {w} de madera.',                       hint:'ll en el interior → ll'},
  {w:'bote_a',    ans:'ll', full:'botella',    ctx:'Bebió agua de la {w} de cristal.',                    hint:'ll en el interior → ll'},
  {w:'ga_eta',    ans:'ll', full:'galleta',    ctx:'Se comió una {w} de chocolate.',                      hint:'ll en el interior → ll'},
  {w:'e_a',       ans:'ll', full:'ella',       ctx:'Le contó a {w} todo lo que había pasado.',            hint:'ll en el interior → ll'},
  {w:'ro_o',      ans:'ll', full:'rollo',      ctx:'Compró un {w} de papel de cocina.',                   hint:'ll en el interior → ll'},
  {w:'panta_a',   ans:'ll', full:'pantalla',   ctx:'Miró la {w} del móvil antes de dormir.',              hint:'ll en el interior → ll'},
  {w:'toa_a',     ans:'ll', full:'toalla',     ctx:'Se secó con una {w} después del baño.',               hint:'ll en el interior → ll'},
  {w:'pasti_a',   ans:'ll', full:'pastilla',   ctx:'Tomó una {w} para el dolor de cabeza.',               hint:'ll en el interior → ll'},
  {w:'va_e',      ans:'ll', full:'valle',      ctx:'El río bajaba por el {w} entre montañas.',            hint:'ll en el interior → ll'},
  {w:'caba_o',    ans:'ll', full:'caballo',    ctx:'El jinete montaba un {w} muy veloz.',                 hint:'ll en el interior → ll'},
  {w:'ga_ina',    ans:'ll', full:'gallina',    ctx:'La {w} ponía un huevo cada día.',                     hint:'ll en el interior → ll'},
  {w:'cuchi_o',   ans:'ll', full:'cuchillo',   ctx:'Cortó el pan con el {w} de la cocina.',               hint:'ll en el interior → ll'},
  {w:'ani_o',     ans:'ll', full:'anillo',     ctx:'Le regalaron un {w} de plata.',                       hint:'ll en el interior → ll'},
  {w:'cepi_o',    ans:'ll', full:'cepillo',    ctx:'Se limpió los dientes con el {w}.',                   hint:'ll en el interior → ll'},
  {w:'orgu_o',    ans:'ll', full:'orgullo',    ctx:'Su madre sentía mucho {w} al verlo actuar.',          hint:'ll en el interior → ll'},
  {w:'maravi_a',  ans:'ll', full:'maravilla',  ctx:'El paisaje era una {w} de la naturaleza.',            hint:'ll en el interior → ll'},
  {w:'a_á',       ans:'ll', full:'allá',       ctx:'Mirad {w} arriba, hay un arcoíris.',                  hint:'ll en el interior → ll'},
  {w:'aque_a',    ans:'ll', full:'aquella',    ctx:'Llegaron el mismo día en que {w} tormenta.',          hint:'ll en el interior → ll'},
  {w:'capi_a',    ans:'ll', full:'capilla',    ctx:'Se casaron en una pequeña {w} del pueblo.',           hint:'ll en el interior → ll'},
  {w:'bri_ar',    ans:'ll', full:'brillar',    ctx:'Las estrellas empezaron a {w} al caer la noche.',     hint:'ll en el interior → ll'},
  {w:'senci_o',   ans:'ll', full:'sencillo',   ctx:'El ejercicio era {w} y lo terminó enseguida.',        hint:'ll en el interior → ll'},
  {w:'amari_o',   ans:'ll', full:'amarillo',   ctx:'El canario tenía un plumaje {w} brillante.',          hint:'ll en el interior → ll'},
  {w:'bi_ete',    ans:'ll', full:'billete',    ctx:'Sacó el {w} para subir al tren.',                     hint:'ll en el interior → ll'},
  {w:'torni_o',   ans:'ll', full:'tornillo',   ctx:'Apretó el {w} con el destornillador.',                hint:'ll en el interior → ll'},
  {w:'bata_a',    ans:'ll', full:'batalla',    ctx:'Los soldados ganaron la {w} al amanecer.',            hint:'ll en el interior → ll'},
  {w:'estre_a',   ans:'ll', full:'estrella',   ctx:'Esa noche vieron una {w} fugaz cruzar el cielo.',     hint:'ll en el interior → ll'},
  {w:'vi_ano',    ans:'ll', full:'villano',    ctx:'El {w} del cuento siempre acaba derrotado.',          hint:'ll en el interior → ll'},
  {w:'si_ón',     ans:'ll', full:'sillón',     ctx:'El abuelo se sentó en su {w} favorito.',              hint:'ll en el interior → ll'},
  {w:'casti_o',   ans:'ll', full:'castillo',   ctx:'El príncipe vivía en un enorme {w}.',                 hint:'ll en el interior → ll'},
  {w:'pasi_o',    ans:'ll', full:'pasillo',    ctx:'Corrió por el {w} hasta su clase.',                   hint:'ll en el interior → ll'},
  {w:'rodi_a',    ans:'ll', full:'rodilla',    ctx:'Se cayó y se hizo daño en la {w}.',                   hint:'ll en el interior → ll'},
  {w:'semi_a',    ans:'ll', full:'semilla',    ctx:'Plantaron una {w} en la maceta del aula.',            hint:'ll en el interior → ll'},
  {w:'meji_a',    ans:'ll', full:'mejilla',    ctx:'Le dio un beso en la {w} al despedirse.',             hint:'ll en el interior → ll'},
  {w:'mantequi_a',ans:'ll', full:'mantequilla',ctx:'Untó la tostada con {w} y mermelada.',               hint:'ll en el interior → ll'},
  {w:'pae_a',     ans:'ll', full:'paella',     ctx:'Comieron una {w} de mariscos en la playa.',           hint:'ll en el interior → ll'},
  {w:'pandi_a',   ans:'ll', full:'pandilla',   ctx:'Salió a jugar con su {w} de amigos del barrio.',      hint:'ll en el interior → ll'},
  {w:'rodi_o',    ans:'ll', full:'rodillo',    ctx:'Usó el {w} para aplanar la masa de la pizza.',        hint:'ll en el interior → ll'},

  // ── Y al inicio de la palabra ──
  {w:'_ema',      ans:'y',  full:'yema',       ctx:'La {w} del huevo es de color amarillo.',              hint:'y- al inicio de palabra → y'},
  {w:'_eso',      ans:'y',  full:'yeso',       ctx:'El médico le puso un {w} en el brazo roto.',          hint:'y- al inicio de palabra → y'},
  {w:'_ate',      ans:'y',  full:'yate',       ctx:'Navegaron por el mar en un gran {w}.',                hint:'y- al inicio de palabra → y'},
  {w:'_ugo',      ans:'y',  full:'yugo',       ctx:'El {w} unía a los dos bueyes.',                       hint:'y- al inicio de palabra → y'},
  {w:'_egua',     ans:'y',  full:'yegua',      ctx:'La {w} galopaba libre por la pradera.',               hint:'y- al inicio de palabra → y'},
  {w:'_odo',      ans:'y',  full:'yodo',       ctx:'Pusieron {w} en la herida para desinfectarla.',       hint:'y- al inicio de palabra → y'},
  {w:'_uca',      ans:'y',  full:'yuca',       ctx:'La {w} es una planta tropical muy nutritiva.',        hint:'y- al inicio de palabra → y'},
  {w:'_ogur',     ans:'y',  full:'yogur',      ctx:'Tomó un {w} con frutas de desayuno.',                 hint:'y- al inicio de palabra → y'},

  // ── Y en el interior de la palabra ──
  {w:'a_er',      ans:'y',  full:'ayer',       ctx:'Me contó que {w} fue al cine con su familia.',        hint:'y en el interior de sílaba → y'},
  {w:'ma_o',      ans:'y',  full:'mayo',       ctx:'En {w} hay muchas flores en el campo.',               hint:'y en el interior de sílaba → y'},
  {w:'ra_o',      ans:'y',  full:'rayo',       ctx:'Un {w} cruzó el cielo durante la tormenta.',          hint:'y en el interior de sílaba → y'},
  {w:'pla_a',     ans:'y',  full:'playa',      ctx:'Pasaron todo el verano en la {w}.',                   hint:'y en el interior de sílaba → y'},
  {w:'pa_aso',    ans:'y',  full:'payaso',     ctx:'El {w} hizo reír a todos los niños.',                 hint:'y en el interior de sílaba → y'},
  {w:'a_udar',    ans:'y',  full:'ayudar',     ctx:'Fue corriendo a {w} a su compañero.',                 hint:'y en el interior de sílaba → y'},
  {w:'le_enda',   ans:'y',  full:'leyenda',    ctx:'Le contó una {w} muy antigua del pueblo.',            hint:'y en el interior de sílaba → y'},
  {w:'pro_ecto',  ans:'y',  full:'proyecto',   ctx:'El {w} de ciencias del colegio quedó muy bien.',      hint:'y en el interior → y'},
  {w:'o_ente',    ans:'y',  full:'oyente',     ctx:'Era un buen {w} que siempre prestaba atención.',      hint:'y en el interior → y'},
  {w:'ha_a',      ans:'y',  full:'haya',       ctx:'Espero que {w} suficiente comida para todos.',        hint:'y en el interior → y (subjuntivo de haber)'},
  {w:'le_ó',      ans:'y',  full:'leyó',       ctx:'La niña {w} el libro entero en dos días.',            hint:'y en el interior → y (pretérito de leer)'},
  {w:'ca_ó',      ans:'y',  full:'cayó',       ctx:'El vaso {w} al suelo y se rompió.',                   hint:'y en el interior → y (pretérito de caer)'},
  {w:'o_ó',       ans:'y',  full:'oyó',        ctx:'De repente {w} un ruido extraño en el tejado.',       hint:'y en el interior → y (pretérito de oír)'},
  {w:'hu_ó',      ans:'y',  full:'huyó',       ctx:'El ratón {w} asustado cuando vio al gato.',           hint:'y en el interior → y (pretérito de huir)'},
  {w:'constru_ó', ans:'y',  full:'construyó',  ctx:'El señor Torres {w} una casa de madera.',             hint:'y en el interior → y (pretérito de construir)'},
  {w:'a_uda',     ans:'y',  full:'ayuda',      ctx:'Pidió {w} a sus amigos para mover los muebles.',      hint:'y en el interior → y'},
  {w:'ma_or',     ans:'y',  full:'mayor',      ctx:'El hermano {w} siempre cuidaba a los pequeños.',      hint:'y en el interior → y'},
  {w:'jo_a',      ans:'y',  full:'joya',       ctx:'Le regalaron una {w} brillante de plata.',            hint:'y en el interior → y'},
  {w:'apo_o',     ans:'y',  full:'apoyo',      ctx:'Contaba con el {w} de toda su familia.',              hint:'y en el interior → y'},
  {w:'ensa_o',    ans:'y',  full:'ensayo',     ctx:'El {w} de la obra de teatro fue muy bien.',           hint:'y en el interior → y'},
  {w:'in_ección', ans:'y',  full:'inyección',  ctx:'La enfermera le puso una {w} en el brazo.',           hint:'y en el interior → y'},
  {w:'desa_uno',  ans:'y',  full:'desayuno',   ctx:'Tomó un zumo de naranja en el {w}.',                  hint:'y en el interior → y'},
  {w:'subra_ar',  ans:'y',  full:'subrayar',   ctx:'Le pidieron {w} las palabras importantes.',           hint:'y en el interior → y'},
  {w:'bo_a',      ans:'y',  full:'boya',       ctx:'La {w} flotaba en el mar señalando el peligro.',      hint:'y en el interior → y'},
  {w:'le_es',     ans:'y',  full:'leyes',      ctx:'Las {w} del país deben respetarse.',                  hint:'y en el interior → y (plural de ley)'},
  {w:'jo_ero',    ans:'y',  full:'joyero',     ctx:'Llevó el collar roto al {w} del mercado.',            hint:'y en el interior → y'},
  {w:'pla_ero',   ans:'y',  full:'playero',    ctx:'Se puso el traje {w} antes de ir a la playa.',        hint:'y en el interior → y'},
  {w:'papa_a',    ans:'y',  full:'papaya',     ctx:'La {w} es una fruta tropical muy dulce.',             hint:'y en el interior → y'},

  // ── Y al final de la palabra ──
  {w:'ho_',       ans:'y',  full:'hoy',        ctx:'Me han dicho que {w} hace mucho sol.',                hint:'y al final de palabra → y'},
  {w:'re_',       ans:'y',  full:'rey',        ctx:'El {w} vivía en un castillo enorme.',                 hint:'y al final de palabra → y'},
  {w:'le_',       ans:'y',  full:'ley',        ctx:'Hay que respetar siempre la {w}.',                    hint:'y al final de palabra → y'},
  {w:'bue_',      ans:'y',  full:'buey',       ctx:'El {w} tiraba del arado por el campo.',               hint:'y al final de palabra → y'},
  {w:'gre_',      ans:'y',  full:'grey',       ctx:'El pastor cuidaba a su {w} con esmero.',              hint:'y al final de palabra → y'},
  {w:'esto_',     ans:'y',  full:'estoy',      ctx:'Hola, {w} muy bien, ¿y tú?',                          hint:'y al final de palabra → y'},
  {w:'vo_',       ans:'y',  full:'voy',        ctx:'Me {w} ya, llegaré tarde al colegio.',                hint:'y al final de palabra → y'},
  {w:'do_',       ans:'y',  full:'doy',        ctx:'Te {w} el libro si me lo devuelves mañana.',          hint:'y al final de palabra → y'},
  {w:'so_',       ans:'y',  full:'soy',        ctx:'Yo {w} el alumno nuevo de esta clase.',               hint:'y al final de palabra → y'},
  {w:'convo_',    ans:'y',  full:'convoy',     ctx:'El {w} de camiones cruzó la montaña.',                hint:'y al final de palabra → y'},
];
